FromDoppler/doppler-webapp

.env.qa, src/components/ContactPolicy/ContactPolicy.js, src/components/ContactPolicy/ContactPolicy.test.js, src/components/ContactPolicy/Promotional.js, src/services/doppler-user-api-client.double.ts, src/services/doppler-user-api-client.test.ts, src/services/doppler-user-api-client.ts
Fix: Set users api url in qa environment
=> feat: integrate user permissions api

src/components/ChangePlan/Checkout/ContactInformation/ContactInformation.js, src/components/ChangePlan/Checkout/ContactInformation/ContactInformation.test.js, src/services/doppler-user-api-client.double.ts, src/services/doppler-user-api-client.test.ts, src/services/doppler-user-api-client.ts
Integrate with the update ContactInformation endpoint
**Task:** [DAT-507](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-507)
=> [DAT-507] - Integrate with the update endpoint

src/components/ContactPolicy/ContactPolicy.js, src/components/ContactPolicy/ContactPolicy.test.js, src/components/form-helpers/form-helpers.js, src/i18n/en.js, src/i18n/es.js
=> feat: add list exclusion configuration section

public/index.html, public/zoho-chat.js, src/App.js, src/App.test.js, src/components/Login/Login.js, src/index.js, src/utils.ts
I will leave this PR open until 2nd of August when it's supposed to be enable in all apps.
* **Error messages are displayed**
> ![image](https://user-images.githubusercontent.com/84402180/127880053-8fff0961-5c22-4928-9d9f-45c7d4165e7c.png)
* **When error is clicked, zendesk chat is displayed**
> ![image](https://user-images.githubusercontent.com/84402180/127880221-ab4d6464-331b-49a7-88cd-0f4bcc8f48b6.png)
=> fix(chat): replace zoho chat with zendesk chat

.lintstagedrc.js, Dockerfile, Dockerfile.BUILDS_AND_CDN, Dockerfile.LOCAL, Dockerfile.RELEASES, Dockerfile.swarm, package.json, prepare.js, yarn.lock
more info: https://makingsense.atlassian.net/browse/DW-1082
**scenarios:** 
- **1. The command to run the prettier was not executed:** 
>when attempting to commit, it is verified if the files to be committed comply with the style rules
- **2. some test fails:** 
>![image](https://user-images.githubusercontent.com/84402180/127593135-8be630db-1a81-48a4-95d4-234e9736b65b.png)
=> Dw 1082 add husky and lint staged

src/components/ChangePlan/PlanCalculator/PlanAgreement/PlanAgreement.js, src/utils.ts
* fix(PlanAgreement): Add function to fix unit price decimals
=> DW-1080-Fix-decimals

package.json, src/components/ContactPolicy/ContactPolicy.js, src/components/ContactPolicy/ContactPolicy.test.js, src/components/Modal/Modal.js, src/components/SubscriberListSelector/SubscriberListSelector.js, src/components/SubscriberListSelector/SubscriberListSelector.test.js, src/hooks/useInfinitePaged/index.js, src/i18n/en.js, src/i18n/es.js, src/services/doppler-api-client.double.ts, src/services/doppler-api-client.test.ts, src/services/doppler-api-client.ts, yarn.lock
=> feat: add list selection page component

src/components/ContactPolicy/ContactPolicy.js, src/components/ContactPolicy/ContactPolicy.test.js, src/components/SubscriberListSelector/SubscriberListSelector.js, src/components/SubscriberListSelector/SubscriberListSelector.test.js, src/components/shared/Promotional/Promotional.js, src/services/doppler-api-client.double.ts, src/services/doppler-contact-policy-api-client.double.ts, src/services/doppler-contact-policy-api-client.test.ts
=> feat: load pre-selected lists

src/components/ContactPolicy/ContactPolicy.js, src/components/SubscriberListSelector/SubscriberListSelector.js, src/components/SubscriberListSelector/SubscriberListSelector.test.js, src/i18n/en.js, src/i18n/es.js
=> feat: update excluded lists when confirm selection

src/components/ChangePlan/Checkout/BillingInformation/BillingInformation.js, src/components/ChangePlan/Checkout/BillingInformation/BillingInformation.test.js, src/components/ChangePlan/Checkout/ContactInformation/ContactInformation.js, src/components/ChangePlan/Checkout/ContactInformation/ContactInformation.test.js, src/i18n/en.js, src/i18n/es.js
Removed the success message when the sumbit was succesfully.
**Changes:**
- Removed the success message in the 'Contact Information' and 'Billing Information'sections when the sumbit was succesfully.
- Updated the UTs.
**Task:** [DAT-539](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-539)
=> [DAT-539] - Removed the success message

src/components/Integrations/BigQuery/ControlPanel/AuthorizationPage.js, src/services/big-query-client.ts, src/services/pure-di.tsx
implemnted methods for integration with backend, temporal change the efect when response ok or failure
=> feat(bigquery): implement get and save method for integration with API

src/components/NewFeatures/NewFeatures.js
=> feat(bigquery): add bigquery pages to new features page

src/components/ChangePlan/Checkout/Checkout.test.js, src/components/ChangePlan/Checkout/ContactInformation/ContactInformation.js, src/components/ChangePlan/Checkout/ContactInformation/ContactInformation.test.js, src/components/ChangePlan/Checkout/Step/Step.test.js, src/i18n/en.js, src/i18n/es.js, src/services/doppler-user-api-client.double.ts, src/services/doppler-user-api-client.ts, src/services/static-data-client.double.ts, src/services/static-data-client.ts
add security question to checkout contact information section
=> feat: add security question to contact information

src/components/ContactPolicy/ContactPolicy.js, src/components/SubscriberListSelector/SubscriberListSelector.js, src/components/SubscriberListSelector/SubscriberListSelector.test.js, src/components/shared/ConfirmationBox/ConfirmationBox.js, src/components/shared/ConfirmationBox/ConfirmationBox.styles.js, src/components/shared/ConfirmationBox/ConfirmationBox.test.js, src/i18n/en.js, src/i18n/es.js, src/services/doppler-contact-policy-api-client.test.ts, src/services/doppler-contact-policy-api-client.ts
- El usuario no tiene listas de suscriptores creadas: Mostrar modal con la opción de crear listas.
- Ocurre un error al cargar las listas: Mostrar mensaje de error en el modal.
=> feat: integrate no list component and error message

.github/workflows/codeql-analysis.yml
Add Code QL analyzer tool.
More information [here](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning)
=> feat: add code analyzer workflow

src/components/ChangePlan/ChangePlan.js, src/components/ChangePlan/ChangePlan.test.js, src/components/ChangePlan/Checkout/PaymentMethod/PaymentMethod.test.js, src/components/FAQ/constants.js, src/i18n/en.js, src/i18n/es.js
* feat(ChangePlan): add final content in doppler-plus --> https://makingsense.atlassian.net/wiki/spaces/DOP/pages/521666590/Selecci+n+de+Plan
* Fix paymentmethod.test bug
* Modify some code to add new final content.
=> DW-498-Doppler-plus-content

package.json
This PR is based [on this other PR.](https://github.com/FromDoppler/unlayer-editor/pull/31)
To force an amount of testing per feature, this seems to be a good idea.
`yarn test:ci` gives this result
```
-----------------------------------------------------------------------|---------|----------|---------|---------|--------------------------------------------
File                                                                   | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
-----------------------------------------------------------------------|---------|----------|---------|---------|--------------------------------------------
All files                                                              |   79.45 |    69.02 |   79.24 |   79.43 | 
src …
```
=> feat: add test coverage for webapp.

src/services/doppler-legacy-client.ts
* fix(doppler-legacy-client): fix upgrade form endpoint
=> DW-1116-fix-form-upgrade-endpoint

package.json, src/components/ChangePlan/Checkout/CheckoutSummary.js, src/components/Login/Login.js, src/components/Signup/Signup.js, src/hooks/useLinkedingInsightTag/index.js, yarn.lock
Add linkedin insight tag to track conversions between linkedin ads campaigns and doppler. We have the campaigns but not yet the conversions.
=> DW-1119 linkedin tag

src/components/DopplerPlus/AgenciesForm.test.js, src/components/DopplerPlus/ExclusiveForm.js, src/components/DopplerPlus/ExclusiveForm.test.js, src/components/DopplerPlus/UpgradeSuggestionForm.js, src/components/DopplerPlus/UpgradeSuggestionForm.test.js
* fix(testForms): perform unit form tests, using this advices: https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#not-using-screen
=> DW-1044-perform-test-forms

src/components/Header/HeaderUserMenu/HeaderUserMenu.js, src/components/Header/HeaderUserMenu/HeaderUserMenu.test.js
=> refactor: move buy link to up in header menu

src/i18n/en.js, src/i18n/es.js
**Update exclude list content in contact policy**
**scenario:**
- The user navigates to `/sending-preferences/contact-policy`
- The user in 1920x1080 resolution sees the content in 2 lines
**Spanish**
**English**
=> refactor: update excluded list content

src/components/ChangePlan/PlanCalculator/BannerUpgrade/BannerUpgrade.js, src/components/ChangePlan/PlanCalculator/BannerUpgrade/BannerUpgrade.test.js
* fix(BannerUpgrade): fix object links
=> fix(BannerUpgrade): fix object links

src/App.js, src/components/ControlPanel/ControlPanel.js, src/components/ControlPanel/ControlPanel.test.js
I'm adding a new component to start working with the new ControlPanel styles.
=> feat(ControlPanel) : Add new component

src/doppler-types.ts, src/services/doppler-legacy-client.test.js, src/services/doppler-legacy-client.ts
It seems that in DB there are some discounts for monthly plans, that is not correct. But also it is not correct to do the mapping. So I've removed the mapping and then added a test as documentation for the future.
=> DW-1141: fix(PlanCalculator): for monthly plans there shouldn't be discounts

src/components/DopplerPlus/AgenciesForm.js, src/components/DopplerPlus/AgenciesForm.test.js, src/components/DopplerPlus/ExclusiveForm.js, src/components/DopplerPlus/ExclusiveForm.test.js, src/components/DopplerPlus/UpgradeSuggestionForm.js, src/components/DopplerPlus/UpgradeSuggestionForm.test.js, src/i18n/en.js, src/i18n/es.js
_fix(breadcrumbs): Fix breadcrumb form links in:_
- _Agencies Form_
- _Upgrade Suggestion Form_
- _Exclusive Form_
=> fix(breadcrumbs): Fix breadcrumb form links

src/components/DopplerPlus/UpgradeSuggestionForm.js, src/i18n/en.js, src/i18n/es.js
https://makingsense.atlassian.net/browse/DW-1149
* fix(forms): Fix doppler plus forms content
=> DW-1149-Fix-doppler-plus-forms-content

src/components/ChangePlan/Checkout/PaymentMethod/CreditCard.test.js, src/components/ChangePlan/PlanCalculator/PlanAgreement/PlanAgreement.js, src/components/ChangePlan/PlanCalculator/PlanCalculator.test.js, src/services/doppler-legacy-client.ts
* feat(PlanAgreement): Add cost per mail in prepaid plans
* Fix some Creditcard test wich was using an all function called _replaceAll_
=> DW-1148-cost-per-email-credits-plan

src/components/ChangePlan/PlanCalculator/BannerUpgrade/BannerUpgrade.js, src/components/ChangePlan/PlanCalculator/BannerUpgrade/BannerUpgrade.test.js, src/components/ChangePlan/PlanCalculator/PlanCalculator.js, src/i18n/en.js, src/i18n/es.js
* fix(BannerUpgrade): Show correct message when subscriber plan is higher than monthly
* Fix deprecated function in CreditCard.test
**Top of Plan:**
**Top of slider:**
=> DW-1155-top-of-subscriber-plan

src/components/ChangePlan/ChangePlan.js, src/components/ChangePlan/ChangePlan.test.js
* Fix(ChangePlan): redirect to upgradeform if exclusive clien
=> DW-1159-exclusive-clients

src/components/Integrations/BigQuery/AuthorizationPage.js, yarn.lock
remove validation for notification messages.
--> this change will be included when the messages logic be implement
=> chore(bigquery): remove notification messages for demo in production

src/components/NewFeatures/NewFeatures.js
- Dashboard added to New Features
=> DW-1192-New-feature

src/App.js, src/components/NewFeatures/NewFeatures.js, src/components/Plans/PlanCalculator/NavigatorTabs/NavigatorTabs.js, src/components/Plans/PlanCalculator/NavigatorTabs/NavigatorTabs.test.js, src/doppler-types.ts
**details task:** https://makingsense.atlassian.net/browse/DW-1235
/plan-selection/standard/subscribers => **/plan-selection/premium/by-contacts:**
/plan-selection/standard/monthly-deliveries => **/plan-selection/premium/by-emails:**
/plan-selection/standard/prepaid => **/plan-selection/premium/by-credits:**
=> Dw 1235 update new plan calculator urls

src/components/ChangePlanDeprecated/Checkout/PurchaseSummary/PurchaseSummary.js, src/components/ChangePlanDeprecated/Checkout/PurchaseSummary/PurchaseSummary.test.js, src/i18n/en.js, src/i18n/es.js
Replace **STANDARD** by **PREMIUM**
**Before:**
**After:**
**Task:** [DAT-668](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-668)
=> [DAT-668]- Replace STANDARD by PREMIUM

src/components/Plans/PlanCalculator/BannerUpgrade/BannerUpgrade.js, src/components/Plans/PlanCalculator/BannerUpgrade/BannerUpgrade.test.js, src/components/Plans/PlanCalculator/BannerUpgrade/getUpgradeInfo.js
* Feat(BannerUpgrade): Add bannerUpgrade component
=> DW-1252-Banner-update-component

src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.js, src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.styles.js, src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.test.js, src/components/Plans/PlanCalculator/index.js, src/components/Plans/PlanCalculator/index.styles.js, src/components/Plans/PlanCalculator/index.test.js, src/hooks/useQuery/index.js, src/hooks/useQueryParams/index.js
**details task:** https://makingsense.atlassian.net/browse/DW-1256
**CDN**: https://cdn.fromdoppler.com/doppler-webapp/build4076/#/plan-selection/premium/by-contacts?promo-code=fake-promo-code
**Result:**
**With promo-code query param:**
=> Dw 1256 create back and buy buttons

src/components/Integrations/BigQuery/AuthorizationPage.js
fix console error on test execution
=> fix: error on test

src/components/ChangePlanDeprecated/Checkout/PurchaseSummary/PurchaseSummary.js, src/services/doppler-billing-user-api-client.double.ts, src/services/doppler-billing-user-api-client.test.ts, src/services/doppler-billing-user-api-client.ts
We need to send this information to create new agreement to the user
```
{
total: 23
discountId: "2"
planId: "3"
}
```
=> feat: [DAT-598] Integrate with POST agreement service

src/components/Plans/PlanCalculator/Slider/index.js, src/components/Plans/PlanCalculator/Slider/index.test.js, src/components/Plans/PlanCalculator/index.js, src/components/Plans/PlanCalculator/index.test.js
**details task:** https://makingsense.atlassian.net/browse/DW-1259
**CDN:** 
Hides the slider when the user's active plan is the highest plan
=> Dw 1259 add is visible property to slider component

src/components/Plans/PlanCalculator/NavigatorTabs/PlanPrice/PlanPricePerMonth.js, src/components/Plans/PlanCalculator/NavigatorTabs/PlanPrice/PlanPricePerMonth.test.js
* feat(PlanPricePerMonth): Add PlanPricePerMonth component and its tests
=> DW-1254-Price-per-month-component

src/components/Plans/PlanCalculator/BannerUpgrade/BannerUpgrade.js, src/components/Plans/PlanCalculator/index.js, src/components/Plans/PlanCalculator/index.test.js
**details task:** https://makingsense.atlassian.net/browse/DW-1258
CDN: https://cdn.fromdoppler.com/doppler-webapp/int-build4090/#/plan-selection/premium/by-contacts?promo-code=fake-promo-code
**Show the banner**
**When plans are by contacts:**
**When plans are by emails:**
**When plans are by credits:**
=> Dw 1258 aplly banner upgrade component to plan calculator

src/components/ChangePlanDeprecated/Checkout/Checkout.js
Apply background styles regarding UI library
**Before:**
**After:**
=> feat(checkout): Apply background styles regarding UI library

src/components/Signup/Signup.js, src/components/Signup/Signup.test.js, src/services/doppler-legacy-client.ts
details task: https://makingsense.atlassian.net/browse/DW-1142
save Origin_Inbound parameter into cookie
=> chore: added Origin_Inbound parameter

src/components/Plans/PlanCalculator/Discounts/index.js, src/components/Plans/PlanCalculator/Discounts/index.test.js, src/components/Plans/PlanCalculator/index.js, src/components/Plans/PlanCalculator/reducers/plansByTypeReducer.js, src/components/Plans/PlanCalculator/reducers/plansByTypeReducer.test.js, src/doppler-types.ts
**details task:** https://makingsense.atlassian.net/browse/DW-1255
**Production URL:** https://cdn.fromdoppler.com/doppler-webapp/build4122/#/plan-selection/premium/by-contacts?promo-code=ALLPLANS
**Result**
=> Dw 1255 create discount component

src/components/Plans/PlanCalculator/PlanPrice/PricePerExtraEmail/index.js, src/components/Plans/PlanCalculator/PlanPrice/PricePerExtraEmail/index.test.js, src/components/Plans/PlanCalculator/PlanPrice/PriceWithDiscount/index.js, src/components/Plans/PlanCalculator/PlanPrice/PriceWithDiscount/index.test.js, src/components/Plans/PlanCalculator/PlanPrice/index.js, src/components/Plans/PlanCalculator/PlanPrice/index.test.js
**Details task:** https://makingsense.atlassian.net/browse/DW-1265
- add price with discount
- add price per extra email
=> Dw 1265 create plan price

src/components/Plans/PlanPrice/PlanPriceWithoutDiscounts.js, src/components/Plans/PlanPrice/PlanPriceWithoutDiscounts.test.js
* feat(PlanPriceWithoutDiscounts): Add PlanPriceWithoutDiscounts component
* Add tests
=> DW-1262-PriceWithoutDiscount-component

src/components/Plans/PlanCalculator/PlanPrice/PricePerMonth/index.js, src/components/Plans/PlanCalculator/PlanPrice/PricePerMonth/index.test.js, src/components/Plans/PlanCalculator/PlanPrice/PriceWithDiscount/index.js, src/components/Plans/PlanCalculator/PlanPrice/PriceWithDiscount/index.test.js, src/components/Plans/PlanCalculator/PlanPrice/PriceWithoutDiscount/index.js, src/components/Plans/PlanCalculator/PlanPrice/PriceWithoutDiscount/index.test.js, src/components/Plans/PlanCalculator/PlanPrice/index.js, src/components/Plans/PlanCalculator/PlanPrice/index.test.js, src/components/Plans/PlanCalculator/index.js
**details task:** https://makingsense.atlassian.net/browse/DW-1266
**CDN integration:** https://cdn.fromdoppler.com/doppler-webapp/int-build4142/#/plan-selection/premium/by-contacts 
**Result:**
=> Dw 1266 apply plan price to plan calculator

src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.js
We need to create a new feature flag "newCheckoutEnabled" to show the new checkout for the moment
[Documentation](https://github.com/FromDoppler/doppler-webapp/blob/01ce0ff67c8de962fe76cdf96a42c020c0e57b03/README.md#about-partial-functionalities)
We use the local storage to set the newCheckoutEnabled flag with the next command
`localStorage.setItem('dopplerExperimental', JSON.stringify({newCheckoutEnabled : true}));`
Pseudocode
newCheckout = true → show new checkout
newCheckout = false or undefined → show oldCheckout
=> feat: [DAT-555] Add experimental feature "newCheckoutEnabled" for the new checkout

src/components/ChangePlanDeprecated/Checkout/PaymentMethod/CreditCard.test.js
Remove warning test
**Task:** No task
=> fix(checkout): Remove warning test

src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.js
**details task:**  https://makingsense.atlassian.net/browse/DW-1276
Allowed to accept `?promo-code` and `?PromoCode` query params in Plan Calculator.
=> feat: add PromoCode to PlanCalculator

src/components/Dashboard/FirstSteps/ActionBox/index.js, src/components/Dashboard/FirstSteps/ActionBox/index.test.js, src/components/Dashboard/FirstSteps/Notification/index.js, src/components/Dashboard/FirstSteps/Notification/index.test.js, src/components/Dashboard/FirstSteps/index.js, src/components/Dashboard/FirstSteps/index.test.js, src/components/Dashboard/FirstSteps/reducers/firstStepsReducer.js, src/components/Dashboard/FirstSteps/reducers/firstStepsReducer.test.js, src/i18n/en.js, src/i18n/es.js
**details task:** https://makingsense.atlassian.net/browse/DW-1291
Create First Steps section:
=> Dw 1291 create first steps

src/components/Dashboard/FirstSteps/ActionBox/index.js, src/components/Dashboard/FirstSteps/ActionBox/index.test.js, src/components/Dashboard/FirstSteps/Notification/index.js, src/components/Dashboard/FirstSteps/Notification/index.test.js, src/components/Dashboard/FirstSteps/index.js, src/components/Dashboard/FirstSteps/index.test.js, src/components/Dashboard/FirstSteps/reducers/firstStepsReducer.js, src/components/Dashboard/FirstSteps/reducers/firstStepsReducer.test.js, src/i18n/en.js, src/i18n/es.js
**details task:** https://makingsense.atlassian.net/browse/DW-1308
**data received from the back:**
```
{
hasListsCreated: true,  
hasCampaingsCreated: true,
hasDomainsReady: false,  
hasCampaingsSent: true,
}
```
**is mapped to:**
```
{
completed: false,
firstSteps: [
{
status: PENDING_STATUS,
title: 'dashboard.first_steps.has_list_created_title',
description: 'dashboard.first_steps.has_list_created_description_MD',
textStep: 1,
},
{
status: WARNING_STATUS,
title: 'dashboard.first_steps.has_domains_ready_title',
description: 'dashboard.first_steps.has_domains_ready_description_MD',
textStep: null,
},
{
status: PENDING_STATUS,
title: 'dashboard.first_steps.has_campaings_created_title',
description: 'dashboard.first_steps.has_campaings_created_description_MD',
textStep: 2,
},
{
status: …
```
=> feat: apply back information mapping

src/components/ControlPanel/ControlPanel.js, src/i18n/en.js, src/i18n/es.js
=> [DOI-373] Add subtitle description into Control Panel

src/components/Plans/Checkout/Discounts/Discounts.js, src/components/Plans/Checkout/PaymentMethod/PaymentMethod.js, src/components/Plans/Checkout/PaymentMethod/PaymentMethod.test.js
Change "tooltip" and use "Info message"
**Screenshot:**
**Before:**
**After:**
**Task:** [DAT-705](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-705)
=> feat(checkout): Change "tooltip" and use "Info message"

src/components/Plans/Checkout/PaymentMethod/PaymentMethod.js
Change style class for the considerations section.
**Before:**
**After:**
**Task:** [DAT-706](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-706)
=> feat(checkout): Change style class for the considerations section

src/i18n/en.js, src/i18n/es.js
Update texts for the 'extra credits'
**Before:**
**After:**
**Task:** [DAT-707](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-707)
=> [DAT-707] - Update texts for the 'extra credits'

src/components/Dashboard/Dashboard.js, src/components/Dashboard/FirstSteps/ActionBox/index.js, src/components/Dashboard/FirstSteps/Notification/index.js, src/components/Dashboard/FirstSteps/index.js, src/components/Dashboard/FirstSteps/index.test.js, src/components/Dashboard/FirstSteps/reducers/firstStepsReducer.js, src/i18n/en.js, src/i18n/es.js
**details task:** https://makingsense.atlassian.net/browse/DW-1322
**Before**
**After**
=> Dw 1322 apply first steps in dashboard

src/doppler-types.ts, src/services/doppler-user-api-client.double.ts, src/services/doppler-user-api-client.test.ts, src/services/doppler-user-api-client.ts
I recently added this new endpoint:
So now I'm adding a method to the dopplerUserApiClient service to consume that endpoint.
Looking forward to your review!!
=> [DOI-360] Add new method in dopplerUserApiClient service to get integrations status

src/components/Dashboard/CampaignSummary/index.js, src/components/Dashboard/CampaignSummary/index.test.js, src/components/Dashboard/CampaignSummary/reducers/campaignSummaryReducer.js, src/components/Dashboard/CampaignSummary/reducers/campaignSummaryReducer.test.js, src/components/Dashboard/ContactSummary/index.js, src/components/Dashboard/ContactSummary/index.test.js, src/components/Dashboard/ContactSummary/reducers/contactSummaryReducer.js, src/components/Dashboard/ContactSummary/reducers/contactSummaryReducer.test.js, src/components/Dashboard/Dashboard.js, src/components/Dashboard/Dashboard.test.js, src/components/Dashboard/Kpis/Kpi.js, src/components/Dashboard/Kpis/Kpi.test.js, src/components/Dashboard/LearnWithDoppler/index.js, src/i18n/en.js, src/i18n/es.js
**details task:** https://makingsense.atlassian.net/browse/DW-1327
a general refactor of the dashboard is made and translations are added
=> Dw 1327 refactor my campaigns and my contacts

src/components/Dashboard/ContactSummary/index.js, src/components/Dashboard/ContactSummary/index.test.js, src/components/Dashboard/ContactSummary/reducers/contactSummaryReducer.js, src/components/Dashboard/ContactSummary/reducers/contactSummaryReducer.test.js, src/components/Dashboard/Dashboard.test.js, src/services/contactSummary.test.ts, src/services/contactSummary.ts, src/services/pure-di.tsx, src/services/reports/index.double.ts, src/services/reports/index.test.ts, src/services/reports/index.ts
**details task:** https://makingsense.atlassian.net/browse/DW-1057
Connects the contacts summary component with the back
=> Dw 1057 add contact report service

src/components/Dashboard/FirstSteps/index.js, src/components/Dashboard/FirstSteps/index.test.js, src/components/Dashboard/FirstSteps/reducers/firstStepsReducer.js, src/components/Dashboard/FirstSteps/reducers/firstStepsReducer.test.js, src/services/dashboardService/SystemUsageSummary.double.ts, src/services/dashboardService/SystemUsageSummary.ts, src/services/pure-di.tsx
* Add System Usage Summary service and service.double
=> DW-1294-System-usage-summary-service

src/components/Plans/Checkout/CheckoutSummary.js
Use useQueryParams hooks to get the parameters
=> feat(checkout): Use useQueryParams hooks to get the parameters

src/services/campaignSummary.ts, src/services/contactSummary.ts, src/services/reports/index.test.ts
**details task:** https://makingsense.atlassian.net/browse/DW-1336
Fix date in campaign and contact services
=> fix: fix date in campaign and contact services

src/components/Plans/Checkout/Checkout.js, src/i18n/en.js, src/i18n/es.js
Add 'back' button in the checkout page
Screenshot:
**Task:** [DAT-716](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-716)
=> [DAT-716] - Add 'back' button in the checkout page

src/App.js, src/components/SafeRedirect.js, src/components/SafeRedirect.test.js
* fix:dashboard as default page
=> dashboard-as-default-page  [TO BE PROOVED IN QA ENVIROMENT ]

src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
Refresh page when the buy was succeed.
**Task:** [DAT-723](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-723)
=> [DAT-723] - Refresh page when the buy was succeed

src/services/doppler-billing-user-api-client.ts
Include the promocode in the purchase endpoint
**Task:** [DAT-724](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-724)
=> [DAT-724] - Include the promocode in the purchase endpoint

src/services/campaignSummary.test.ts, src/services/campaignSummary.ts, src/services/reports/index.double.ts, src/services/reports/index.ts
Calculate Open Rate
**details task:** https://makingsense.atlassian.net/browse/DW-1339
calculate open rate based on totalOpenClicks & totalSentEmails
=> feat: add calculate open rate

src/i18n/en.js, src/i18n/es.js
**details task:** https://makingsense.atlassian.net/browse/DW-1340
change contacts summary URL to https://app2.fromdoppler.com/Lists/MasterSubscriber/
=> fix: fix contacts summary url

.env.production, src/components/Header/Header.js
* fix: set to true prod enviroment var
* feat: add dashboard link to icon
=> DW-1331-set-to-true-enviroment-prod-var [⚠️ DO NOT MERGE UNTIL RELEASE 23.6⚠️ ]

src/App.js
=> fix: first fix #, then check newdashboard

src/i18n/en.js, src/i18n/es.js
**details task:** https://makingsense.atlassian.net/browse/DW-1348
Fix demo day link in learn with doppler section
=> fix: fix demo day link

src/services/campaignSummary.ts
**details task:** https://makingsense.atlassian.net/browse/DW-1349
**Before:**
**After:**
=> fix: fix decimals

src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js, src/services/doppler-billing-user-api-client.ts
Include the 'origin_inbound' parameter in the buy of the plan
**Task:** [DAT-728](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-728)
=> [DAT-728] - Include the 'origin_inbound' parameter in the buy of the plan

src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
Fix issue when the promocode is passed by querystring
**Issue:** [DAT-730](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-730)
=> [DAT-730] - Fix issue when the promocode is passed by querystring

src/components/Plans/Checkout/PurchaseSummary/PlanPurchase/index.js, src/components/Plans/Checkout/PurchaseSummary/PlanPurchase/index.test.js, src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
**details task:** https://makingsense.atlassian.net/browse/DAT-733
- Refactor PlanPurchase component
- Refactor test of the purchase process
=> refactor: refactor PlanPurchase component

src/components/Plans/Checkout/PaymentMethod/CreditCard.js
Fix issue when the user copy and paste the credit card number
**Bug:** [DAT-656](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-656)
=> [DAT-656] - Fix issue when the user copy and paste the credit card number

src/components/Plans/Checkout/PaymentMethod/CreditCard.js
Clear CreditCard's fields when the user edit the credit card information
**Before:**
**After:**
**Bug:** [DAT-745](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-745)
=> [DAT-745] - Clear CreditCard's fields when the user edit the credit card information

src/services/control-panel-service.ts
Display connection icons in Control Panel.
DO NOT MERGE UNTIL RELEASE 23.7
=> ⚠️  [No-Ticket] Show connection status for Integrations [DO NOT MERGE UNTIL RELEASE 23.7] ⚠️

src/services/control-panel-service.ts
The issue with the users api is fixed, I'm activating it again.
=> Activate control panel status

src/i18n/en.js, src/i18n/es.js
=> fix: fix in url dashboard

src/services/doppler-legacy-client.ts, src/services/session-manager.ts
Expose data for hotjar.
This code is the same that in https://github.com/FromDoppler/doppler-webapp/pull/1839 but by mistake i created the branch with a wrong name.
=> feat: expose data to be used by hotjar

src/App.js, src/components/Plans/PlanCalculator/GoToUpgrade/index.js, src/components/Plans/PlanCalculator/GoToUpgrade/index.test.js
**Jira ticket:**  https://makingsense.atlassian.net/browse/DW-1359
- The user navigates to **`/plan-selection/premium/by-contacts?PromoCode=S4NV4L3NT1N&origin_inbound=fake`** with a **Credit Account**. The user is redirected to buy credit page (**`https://appqa.fromdoppler.net/ControlPanel/AccountPreferences/BuyCreditsStep1?PromoCode=S4NV4L3NT1N&origin_inbound=fake`**)
- The user navigates to **`/plan-selection/premium/by-contacts?PromoCode=S4NV4L3NT1N&origin_inbound=fake`**  with **a contact or a Email Account**. The user is redirected to upgrade page (**`https://appint.fromdoppler.net/ControlPanel/AccountPreferences/GetAccountInformation?origin_inbound=fake`**)
- The user navigates to **`/plan-selection/premium/by-contacts?PromoCode=S4NV4L3NT1N&origin_inbound=fake`** …
=> feat: redirect in paids account

src/components/Plans/Checkout/PurchaseSummary/Promocode.js, src/components/Plans/Checkout/PurchaseSummary/Promocode.test.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-764
- Refactor PromoCode component. 
- Refactor tests
=> refactor: refactor PromoCode component

src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
**Jira ticket:** https://makingsense.atlassian.net/browse/DAT-765
- Separate unrelated useEffect logic into multiple useEffects
- Change way of getting url parameters
=> Dat 765 refactor purchase summary

commitlint.config.js, package.json, prepare.js, yarn.lock
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-766
1. **Example commit message:** `add new component`  ❌
2.  **Example commit message:** `foo: add new component` ❌
3. **Example commit message:** `feat:add new component` ❌
4. **Example commit message:** `feat: add new component` ✅✅
=> chore: conventional commits

src/components/Plans/Checkout/CheckoutSummary.js
Fix issue when redirect checkout summary from old checkout
**Bug:** [DAT-780](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-780)
=> fix(checkout-summary): Fix issue when redirect checkout summary from old checkout

src/components/Plans/PlanCalculator/PlanPrice/OldPrice/index.js, src/components/Plans/PlanCalculator/PlanPrice/OldPrice/index.test.js, src/components/Plans/PlanCalculator/PlanPrice/PricePerExtraEmail/index.js, src/components/Plans/PlanCalculator/PlanPrice/PricePerExtraEmail/index.test.js, src/components/Plans/PlanCalculator/PlanPrice/PriceWithDiscount/index.js, src/components/Plans/PlanCalculator/PlanPrice/PriceWithDiscount/index.test.js, src/components/Plans/PlanCalculator/PlanPrice/PriceWithoutDiscount/index.js, src/components/Plans/PlanCalculator/PlanPrice/TotalPrice/index.js, src/components/Plans/PlanCalculator/PlanPrice/TotalPrice/index.test.js, src/components/Plans/PlanCalculator/PlanPrice/index.js
**Jira ticket:** https://makingsense.atlassian.net/browse/DAT-795
Refactor PlanPrice component
=> Dat 795 refactor plan price component

src/components/Login/Login.js, src/index.js
**Important!!** it's only for testing purposes, it's not necessary a review yet because it will not be merged.
related to [DOP-930](https://makingsense.atlassian.net/browse/DOP-930)
**UPDATE**: now these changes can be reviewed in order **to be merged**.
=> feat(login): modify user input to capture email using datahub

src/components/Plans/PlanCalculator/Discounts/index.js, src/components/Plans/PlanCalculator/Discounts/index.test.js, src/components/Plans/PlanCalculator/PlanPrice/OldPrice/index.js, src/components/Plans/PlanCalculator/PlanPrice/index.js, src/components/Plans/PlanCalculator/PlanPrice/index.test.js, src/components/Plans/PlanCalculator/Slider/index.js, src/components/Plans/PlanCalculator/Slider/index.test.js, src/components/Plans/PlanCalculator/index.js, src/components/Plans/PlanCalculator/reducers/promocodeReducer.js, src/components/Plans/PlanCalculator/reducers/promocodeReducer.test.js, src/i18n/en.js, src/i18n/es.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-783
**Note:** missing define invalid promocode message
=> Dat 783 apply promocode to plan calculator

src/components/Plans/PlanCalculator/PlanPrice/index.js, src/components/Plans/PlanCalculator/PlanPrice/index.test.js, src/components/Plans/PlanCalculator/index.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-804
Remove warning message when there is not promocode
=> fix: remove warning message when there is not promocode

src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.js
Update logic to include the plan by contacts to redirect new checkout
**Task:** [DAT-803](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-803)
=> [DAT-803] - Update logic to include the plan by contacts to redirect new checkout

src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.js
Integrate the buy the plan by emails for the final users.
**Task:** [DAT-814](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-814)
=> [DAT-814] - Integrate the buy the plan by emails for the final users

src/i18n/es.js
**Jira ticket:** https://makingsense.atlassian.net/browse/DAT-825
**Spanish content**
**English content**
=> feat: add spanish content for demoday

src/components/ControlPanel/ControlPanel.js, src/services/control-panel-service.ts
=> [DOI-472] Add anchor links for control panel sections

src/components/Plans/PlanCalculator/index.js, src/components/Plans/PlanCalculator/index.test.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-839
**Test the scenarios:**
- When the user has a plan by email
- When the user has a contact plan for 1/3/6/12 month(s)
=> test: add test to plan calculator

package.json, src/components/ForgotPassword/ForgotPassword.js, src/components/Login/Login.js, src/components/Signup/Signup.js, src/i18n/en.js, src/i18n/es.js
Remove noreferrer attribute for doppler urls
=> chore: remove noreferrer attribute for doppler urls

src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.js
Allow purchases plan by credits, emails or contacts for free users and that their country is not in AR/MX/CO
**Task:** [DAT-832](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-832)
=> [DAT-832] - Allow purchases plan by credits, emails or contacts for free users and that their country is not in AR/MX/CO

src/App.test.js, src/components/Signup/Signup.js, src/components/Signup/Signup.test.js, src/services/doppler-legacy-client.ts, src/services/pure-di.tsx, src/services/utm-cookies-manager.js, src/services/utm-cookies-manager.test.js
Replace localstorage with cookie. [DAT-785](https://makingsense.atlassian.net/browse/DAT-785)
=> chore: replace localstorage with cookie

src/components/Plans/Checkout/PaymentMethod/PaymentMethod.js, src/components/Plans/Checkout/PaymentMethod/Transfer/Transfer.js, src/components/Plans/Checkout/PaymentMethod/Transfer/Transfer.test.js
Remove an unnecessary service call in the Transfer component
**Task:** No task
=> [No-Task] - Remove an unnecessary service call in the Transfer component

src/components/Plans/Checkout/CheckoutSummary.js, src/components/Plans/Checkout/CheckoutSummary.test.js, src/components/Plans/Checkout/PurchaseSummary/PlanPurchase/index.js
Update checkout summary page to support transfer with promocode of the 100% discount
**Task:** [DAT-851](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-851)
=> [DAT-851] - Update checkout summary page to support transfer with promocode of the 100% discount

src/services/utm-cookies-manager.js
Fix: remove duplicate cookie entry when referrer is fromdoppler
=> fix: avoid duplicating cookie entry on same session

src/components/Plans/Checkout/PaymentMethod/PaymentMethod.js, src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js, src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.test.js
fix issue when the user changes the renovation
Bug: [DAT-863](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-863)
=> [DAT-863] - fix issue when the user changes the renovation

src/components/Reports/Reports.js, src/components/Reports/Reports.test.js, src/components/SiteTrackingRequired/SiteTrackingRequired.js, src/components/SiteTrackingRequired/SiteTrackingRequired.test.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-869
When the user navigates to /reports , he sees the typeform survey
=> feat: add typeform in report page

src/components/Plans/Checkout/PaymentMethod/Transfer/Colombia/index.js, src/i18n/en.js, src/i18n/es.js, src/validations.ts
Add validations for the NIT
**Task:** [](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-874)
=> [DAT-874] - Add validations for the NIT

src/components/Plans/Checkout/PaymentMethod/Transfer/Argentina/index.js, src/components/Plans/Checkout/PaymentMethod/Transfer/Transfer.js, src/components/Plans/Checkout/PaymentMethod/Transfer/Transfer.test.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-879
Make refactor in transfer component
=> refactor: make refactor in transfer component

src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.js
Integrate colombia users to use the new checkout
Task: [DAT-831](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-831)
=> [DAT-831] - Integrate colombia users to use the new checkout

src/i18n/en.js, src/i18n/es.js, src/validations.test.js, src/validations.ts
Add RFC validation for the Mexico transfer
**Invalid:**
**Valid:**
**Task:** [DAT-884](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-884)
=>  [DAT-884] - Add RFC validation for the Mexico transfer

src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
fix issue when the state.discount is undefined
=> [No-ticket] - fix issue when the state.discount is undefined

src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
Add asteric in the next billing information.
**Task:** [DAT-892](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-892)
=> [DAT-892] - Add asteric in the next billing information

src/components/Plans/Checkout/PaymentMethod/Transfer/Mexico/index.js
Fix issue when the user changes the renovation type.
**Bug:** [DAT-891](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-891)
=> [DAT-891] - fix issue when the user changes the renovation type

src/i18n/es.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-894
**Before:** 
**After:**
=> feat: add content to dashboard. Replace demo day content in spanish

src/components/Plans/Checkout/PaymentMethod/Transfer/Mexico/index.test.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-898
It is wanted to have more complete tests that prove the behavior of the component of transfer mexico
=> refactor: refactor test to transfer mexico

src/components/Plans/Checkout/PaymentMethod/PaymentMethod.test.js, src/components/Plans/Checkout/PaymentMethod/Transfer/Argentina/index.js, src/components/Plans/Checkout/PaymentMethod/Transfer/Argentina/index.test.js, src/components/Plans/Checkout/PaymentMethod/Transfer/Transfer.test.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-897
**Result:**
=> feat: add transfer argentina

src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.js
Integrate the free mexican users to use the new checkout
**Task:** [DAT-899](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-899)
=> [DAT-899] - Integrate the free mexican users to use the new checkout

src/components/Plans/Checkout/PaymentMethod/Transfer/Argentina/index.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-902
Remove CUIT validation when the consumer type is Final Consumer
=> feat: remove cuit validation when consumer type is final consumer

src/App.test.js, src/components/Reports/Reports.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-903
**Description** 
I was missing some dependencies because of the typeform that was added to the report page
=> fix: remove warning in console

src/services/doppler-account-plans-api-client.ts
Encode promocode parameter because sometimes this contains special characters
**Bug:** [DAT-905](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-905)
=> [DAT-905] - Encode promocode parameter because sometimes this contains special characters

src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
Fix issue when the promotion is undefined
=> [No-ticket] fix issue when the promotion is undefined

src/services/static-data-client.double.ts, src/services/static-data-client.test.ts, src/services/static-data-client.ts
Create endpoint to retrieve the document types from cdn
**Task:** [DAT-916](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-916)
=> [DAT-916] - Create endpoint to retrieve the document types from cdn

src/components/ControlPanel/ControlPanel.js, src/hooks/useHashScrollHandler/index.js
Kudos to @jcamposmk, he gave me a huge help and came up with this solution.
The anchor links weren't making focus when accessing from outside the control panel.
Thanks a lot Junior!!
=> [DOI-505] Fix anchor links in control panel

src/components/Plans/Checkout/PaymentMethod/Transfer/Argentina/index.js, src/components/Plans/Checkout/PaymentMethod/Transfer/Argentina/index.test.js, src/components/Plans/Checkout/PaymentMethod/Transfer/Transfer.js, src/components/Plans/Checkout/PaymentMethod/Transfer/Transfer.test.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-924
Add DNI field to Transferencia Argentina
=> feat: add dni a transfer

src/services/doppler-billing-user-api-client.ts
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-927
Add MercadoPago to map
=> feat: add mercadopago to map

src/services/doppler-billing-user-api-client.ts
Send document number as string when the payment method is transfer
=> [No-Ticket] Send document number as string when the payment method is transfer

src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.js, src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.test.js
Integrate new checkout with argentinian user and free
**Task:** [DAT-920](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-920)
=> [DAT-920] - Integrate new checkout with argentinian user and free

src/components/Plans/Checkout/Checkout.js, src/components/Plans/Checkout/Checkout.test.js, src/services/doppler-billing-user-api-client.double.ts, src/services/doppler-billing-user-api-client.test.ts, src/services/doppler-billing-user-api-client.ts
When loading the checkout we need to update the "LastPurchaseIntentionDate" of the user.
=> [DOI-581] Update purchase intention in checkout

src/components/Plans/Checkout/PaymentMethod/PaymentMethod.js, src/doppler-types.ts
Add more exception errors from first data
=> [No-Ticket] - Add more exception error from first data

src/components/Plans/Checkout/ContactInformation/ContactInformation.js
Remove sorting in the industries
**Task:** [DAT-949](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-949)
=> [DAT-949] - Remove sorting in the industries

src/components/Plans/Checkout/PaymentMethod/PaymentMethod.js, src/components/Plans/Checkout/PurchaseSummary/PlanPurchase/index.js, src/components/Plans/Checkout/PurchaseSummary/PlanPurchase/index.test.js, src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.test.js, src/doppler-types.ts
Show first data message when the buy process fail.
Currently the Checkout page show a generic error message, now the firstdata's error is showing to the user.
**Task:** [DAT-958](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-958)
=> [DAT-958] - Show first data message when the buy process fail

src/i18n/en.js, src/i18n/es.js
it was necessary to change the content of the cards in both English and Spanish
Task: [DAT-970](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-970)
=> [DAT-970] - Modify card content

src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.js, src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.test.js, src/components/Plans/Checkout/CheckoutSummary/CheckoutSummaryButton/index.js, src/components/Plans/Checkout/CheckoutSummary/CheckoutSummaryButton/index.test.js, src/components/Plans/Checkout/CheckoutSummary/CheckoutSummaryTitle/index.js, src/components/Plans/Checkout/CheckoutSummary/CheckoutSummaryTitle/index.test.js, src/services/doppler-legacy-client.ts
Update checkout summary when the user has upgrade pending
**Task:** [DAT-975](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-975)
=> [DAT-975] - Update checkout summary when the user has upgrade pending

src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.js
Fix issue in the checkout summary in the title section
=> [No-Ticket] Fix issue in the checkout summary in the title section

src/components/Plans/Checkout/PaymentMethod/MercadoPagoArgentina/index.js
Update security code field in mercado pago because we have an issue when the field type is `tel`
Task: [DAT-977](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-977)
=> [DAT-977] - Update security code field in mercado pago

src/components/Plans/Checkout/PurchaseSummary/PlanPurchase/index.js, src/doppler-types.ts, src/i18n/en.js, src/i18n/es.js
Show Mercadopago's error in the purchase
Task: [DAT-978](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-978)
=> [DAT-978] - Show Mercadopago error in the purchase

src/components/Plans/Checkout/PurchaseSummary/InvoiceRecipients/index.js, src/components/Plans/Checkout/PurchaseSummary/InvoiceRecipients/index.test.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-925
When the user does not have added recipients. The email user is used by default.
=> feat: add user email by default to invoice recipients

src/components/Plans/Checkout/CheckoutSummary/MercadoPagoInformation/index.js, src/components/Plans/Checkout/CheckoutSummary/TransferInformation/index.js
=> fix icons in checkout

src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.js, src/components/Plans/Checkout/CheckoutSummary/MercadoPagoInformation/index.js
Update checkou summary page when the payment method is MP
Task: [DAT-1000](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1000)
=> [DAT-1000] - Update checkou summary page when the payment method is MP

src/i18n/es.js
Jira ticket: [DAT-1042](https://makingsense.atlassian.net/browse/DAT-1042)
Changes to spanish card content.
=> [DAT-1042] - change Aprende con Doppler spanish card content.

src/components/Dashboard/CampaignSummary/index.js, src/components/Dashboard/ContactSummary/index.js, src/components/Dashboard/FirstSteps/ActionBox/index.js, src/components/Dashboard/FirstSteps/index.js, src/components/Dashboard/LearnWithDoppler/Carousel/Slide/Slide.js, src/components/Dashboard/LearnWithDoppler/index.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1039
Add tracking ids to dashboard for google analytics
=> Dat 1039 add tracking ids to dashboard

src/components/ValidateSubscribers/ValidateMaxSubscribersConfirm/index.js, src/components/ValidateSubscribers/ValidateMaxSubscribersConfirm/index.test.js, src/components/ValidateSubscribers/ValidateMaxSubscribersForm/index.js, src/components/ValidateSubscribers/index.js, src/components/ValidateSubscribers/index.test.js, src/i18n/en.js, src/i18n/es.js, src/services/doppler-legacy-client.doubles.ts, src/services/doppler-legacy-client.test.js, src/services/doppler-legacy-client.ts
Jira Ticket: [DAT-1032](https://makingsense.atlassian.net/browse/DAT-1032)
Related to: https://github.com/FromDoppler/doppler-webapp/pull/2030
This PR adds submit logic to Validate max subscribers form.
Also adds confirmation component to show after submit
=> [DAT-1032] - Handle submit logic

src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
Fix issue when show the next invoice amount
=> [No-Ticket] fix issue when show the next invoice amount

src/components/Header/Header.js, src/components/Header/HeaderMessages/HeaderMessages.js, src/components/Header/HeaderMessages/HeaderMessages.test.js, src/components/ValidateSubscribers/ValidateMaxSubscribersForm/index.js, src/components/ValidateSubscribers/index.js, src/services/doppler-legacy-client.doubles.ts, src/services/doppler-legacy-client.ts
Jira ticket: [DAT-999](https://makingsense.atlassian.net/browse/DAT-999)
Related To: https://github.com/FromDoppler/doppler-webapp/pull/2033
This PR resolves banner not showing and adds validate subscribers form
=> [DAT-999] - Add banner and validate subscribers form

src/components/Header/HeaderUserMenu/HeaderUserMenu.js, src/components/Header/HeaderUserMenu/HeaderUserMenu.test.js
Cuando se tienen habilitado la opción sms (_smsEnabled_) se debe de mostrar para todos los tipos de usuarios
=> Mostrar opción sms en el menu de usuario 

src/components/Dashboard/CampaignSummary/index.js, src/components/Dashboard/ContactSummary/index.js, src/components/Dashboard/FirstSteps/ActionBox/index.js, src/components/Dashboard/FirstSteps/index.js, src/components/Dashboard/Kpis/KpiGroup.js, src/components/Dashboard/LearnWithDoppler/Carousel/Slide/Slide.js, src/components/Dashboard/LearnWithDoppler/TextPreviewPost/TextPreviewPost.js, src/components/Dashboard/LearnWithDoppler/index.js, src/i18n/en.js, src/i18n/es.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1039
Add tracking ids to dashboard for google analytics
=> Dat 1039 add id to dashboard

src/components/Plans/Checkout/Checkout.js, src/components/Plans/Checkout/PurchaseSummary/PlanPurchase/index.js, src/components/Plans/Checkout/PurchaseSummary/PlanPurchase/index.test.js, src/components/Plans/PlanCalculator/index.js, src/hooks/useUserTypeAsQueryParam/index.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1045
**With Free Account**
- The user navigates to /plan-selection/premium/by-contacts 
- The accountType with value FREE is added to the URL
**With Paid Account**
- The user navigates to /plan-selection/premium/by-contacts 
- The accountType with value PAID is added to the URL
These actions are applied in Plan calculator, Checkout & Checkout summary
**Example:**
=> feat: add account type query param by default in upgrade proccess

src/components/Plans/PlanCalculator/BannerUpgrade/getUpgradeInfo.js, src/hooks/useUserTypeAsQueryParam/index.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1054
**Before**: The account type query param is lost
**After**
=> fix: fix error when the user has account type query param

src/services/control-panel-service.ts
**Before:**
**After:**
related to DOP-1069
=> feat(control panel): remove unopened mails section

Dockerfile, Dockerfile.BUILDS_AND_CDN, Dockerfile.LOCAL, Dockerfile.RELEASES, Dockerfile.swarm, build-w-docker.sh
Bumps node from 15.14.0 to 16.16.0
=> chore(deps): bump node from 15.14.0 to 16.16.0

public/index.html
Related to https://github.com/FromDoppler/mfe-loader/pull/13
=> DE-666 - Update MFE loader

src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js, src/i18n/en.js, src/i18n/es.js
Integrate update between contacts plan
**Task:** [DAT-984](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-984)
=> [DAT-984] - Integrate update between contacts plan

src/components/shared/Promotions/Promotions.js, src/services/doppler-sites-client.doubles.ts
Add HTML support for content description in Login Page
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1077
=> feat: add HTML support for content description

src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js, src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.test.js, src/services/doppler-account-plans-api-client.double.ts, src/services/doppler-account-plans-api-client.ts
Integrate new checkout with buy credits
**Task:** [DAT-1067](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1067)
=>  [DAT-1067] - Integrate new checkout with buy credits

src/services/planService/index.test.ts, src/services/planService/index.ts
Filter plan tabs depending the current plan of the user.
**Task:** [DAT-1083](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1083)
=> [DAT-1083] - Filter plan tabs depending the current plan of the user

Jenkinsfile
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1084
Slack thread: https://makingsense.slack.com/archives/CGN03EBDM/p1660752202600589
Remove `confirmation` step in Continuos Integration
=> ci(confirmation): remove confirmation step in CI

src/i18n/en.js, src/i18n/es.js
Update content to "months to pay" legend
**Task:** [DAT-1085](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1085)
=> [DAT-1085] - Update content to 'months to pay' legend

src/components/Signup/Signup.js, src/components/Signup/Signup.test.js, src/components/Signup/SignupConfirmation.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1095
**Slack:**  https://makingsense.slack.com/archives/C023YV1B7B6/p1661288780470949
=> fix: from state to query params

src/i18n/en.js, src/i18n/es.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1115
**English**
**Spanish**
=> feat: add new content to email field in signup

Jenkinsfile, build-n-publish.sh
**Jira Task:** https://makingsense.atlassian.net/browse/DAT-1057
- When merging master, deploy qa
- When genereting a tag, deploy a prod
- When merge INT, deploy int
=> chore: update jenkinsfile

src/components/SiteTrackingRequired/SiteTrackingRequired.js
=> fix: remove class bg message grey

src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
Add promocode in the promotion object when it is passed from url
**Task:** [DAT-1136](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1136)
=> [DAT-1136] - Add promocode in the promotion object when it is passed from url

src/App.js, src/App.test.js, src/components/EditorsDemo/EditorsDemo.js, src/components/MenuDemo/MenuDemo.js, src/components/NewFeatures/NewFeatures.js, src/components/PrivateRoute.js
It replaces the Doppler WebApp implementation of the Doppler Menu with the Menu MFE.
JIRA: [https://makingsense.atlassian.net/browse/DE-720](https://makingsense.atlassian.net/browse/DE-720)
Related: https://github.com/MakingSense/Doppler/pull/9587
=> DE-720 - Use Menu MFE in Doppler WebApp

src/services/doppler-legacy-client.ts
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1171
=> fix: add try catch to mapIdUserToken

src/components/Plans/PlanCalculator/index.js, src/components/Plans/PlanCalculator/reducers/plansByTypeReducer.js
Disabled the renovation type component when the current plan of user is the same that it selected.
**Task:** [DAT-1169](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1169)
=> [DAT-1169] - Disabled the renovation type component when the current plan of user is the same that it selected

src/components/Plans/Checkout/PurchaseSummary/PlanPurchase/index.js, src/components/Plans/Checkout/PurchaseSummary/PlanPurchase/index.test.js, src/doppler-types.ts, src/i18n/en.js, src/i18n/es.js
Show a message to indicate that only support upselling when the does not change the plan in the checkout.
**ES:**
**EN:**
Task: [DAT-1127)](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1127)
=> [DAT-1127)] - Show a message to indicate that only support upselling when the does not change the plan in the checkout

src/components/Reports/Subscribers/Subscribers.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1178
**slack:** https://makingsense.slack.com/archives/CRXR62TC2/p1664291637841269
=> fix: fix tabs urls

public/index.html
I do the same that `index.js`: 
https://github.com/FromDoppler/doppler-webapp/blob/master/src/index.js#L39-L41
=> Fix local environment behavior with dummy session

src/components/Plans/PlanCalculator/Slider/index.js, src/components/Plans/PlanCalculator/Slider/index.test.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1139
**Result**
=> feat: add marks to slider

src/components/Dashboard/LearnWithDoppler/Carousel/Carousel.js, src/components/Dashboard/LearnWithDoppler/Carousel/Carousel.test.js, src/components/Dashboard/LearnWithDoppler/TextPreviewPost/TextPreviewPost.js, src/components/Dashboard/LearnWithDoppler/index.js, src/components/Dashboard/LearnWithDoppler/index.test.js, src/hooks/useInterval/index.js, src/hooks/useInterval/index.test.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1140
**Result**
=> Dat 1140 dinamic carousel

src/components/Integrations/Shopify/Shopify.js, src/components/Integrations/Shopify/Shopify.test.js, src/utils.test.js, src/utils.ts
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1193
**Before:**
**After:**
=> DAT-1193 - Fix Shopify page

src/i18n/en.js, src/i18n/es.js
=> DOI-743 Replace data studio for Looker Studio

src/components/Plans/PlanCalculator/index.js, src/components/shared/Promotional/Promotional.js
=> fix: remove background grey on plan calculator

src/i18n/es.js
Correct gramatical and spelling mistakes for the spanish content.
Jira Ticket: [DAT-1197](https://makingsense.atlassian.net/browse/DAT-1197)
=> fix: Correct grammatical and spelling errors

src/components/Signup/Signup.js, src/components/Signup/Signup.test.js, src/services/doppler-legacy-client.ts
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1191
**Result**
=> feat: add page parameter in registration user

src/components/Signup/SignupConfirmation.js
Update content for the confirmation page
=> [DAT-1198] - Update content for the confirmation page

src/components/Login/Login.js, src/components/form-helpers/form-helpers.js
Update the type of messages instead of show warning should show error.
**Task:** [DAT-1207](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1207)
**Before:**
**After:**
=> [DAT-1207] - Update the type of messages instead of show warning should show error

src/components/Integrations/Shopify/Shopify.js, src/components/Integrations/Shopify/Shopify.test.js, src/components/shared/HeaderSection/HeaderSection.js, src/components/shared/UnexpectedError/index.js, src/components/shared/UnexpectedError/index.test.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1194
**BEFORE:**
**AFTER:**
**BEFORE:**
**AFTER:**
**BEFORE:**
**AFTER:**
=> Dat 1194 apply new layout to shopify

.env.development, .env.int, .env.production, .env.qa, src/index.js, src/services/doppler-system-usage-api-client.double.ts, src/services/doppler-system-usage-api-client.test.ts, src/services/doppler-system-usage-api-client.ts, src/services/pure-di.tsx
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1210
Create doppler system usage client
=> Dat 1210 create doppler usage system service

src/components/Login/Login.js, src/components/Login/LoginErrorAccountNotValidated.js, src/components/Signup/SignupConfirmation.js, src/i18n/en.js, src/i18n/es.js
Update content of the messages in the login page.
**ES:**
**EN:**
**Task:**[DAT-1212](https://makingsense.atlassian.net/browse/DAT-1212)
=> [DAT-1212] - Update content of the messages in the login page

src/components/ForgotPassword/ForgotPassword.js
Update message component for the ForgotPassword
**Before:**
**After:**
**Task:** [DAT-1221](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1221)
=> [DAT-1221] - Update message component for the ForgotPassword

src/i18n/en.js, src/i18n/es.js
Add new messages to show the link to update payment details.
**Task:** [DAT-1218](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1218)
=> [DAT-1218] - Add new messages to show the link to update payment details

src/components/Login/Login.js
Create a BlockedAccountNotPayed component to show message when the user is blocked by not paid.
**Task:**[DAT-1231](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1231)
=> [DAT-1231] - Create a BlockedAccountNotPayed component to show message when the user is blocked by not paid

.env.int, .env.qa
Change the environment variables to point to the respective environments of the sites api to test new features
=> fix: change the environment variables

src/index.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1235
**Before:**
**After:**
=> feat: add HardcodedSystemUsageSummaryClient in index.js

src/i18n/en.js, src/i18n/es.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1244
**RESULT:**
**Spanish**
**English**
=> feat: change content in Learn with Doppler section

src/components/Dashboard/FirstSteps/index.js, src/components/Dashboard/FirstSteps/index.test.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1105
**Note**: this is a quick fix to the crossed in `step 4`. Ideally all data will come from the new [system summary api](https://github.com/FromDoppler/doppler-system-usage)
When an user visited the `reports` page and has sent campaigns, the `step 4 `is crossed ..
=> feat: apply dopplerSystemUsage in firstSteps section

src/components/Dashboard/Dashboard.js, src/components/Dashboard/Dashboard.test.js, src/components/Dashboard/QuickActions/index.js, src/components/Dashboard/QuickActions/index.test.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1248
=> feat: hide SMS option when the user hasn't sms enabled

src/App.js, src/components/Plans/UpdatePaymentInformation/Reducers/reprocessReducer.js, src/components/Plans/UpdatePaymentInformation/Reducers/updatePaymentInformationReducer.js, src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformation/Reprocess/index.js, src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformation/Reprocess/index.test.js, src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformation/UpdatePaymentMethod/index.js, src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformation/UpdatePaymentMethod/index.test.js, src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformation/index.js, src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformation/index.test.js, src/i18n/en.js, src/i18n/es.js, src/services/doppler-billing-user-api-client.double.ts, src/services/doppler-billing-user-api-client.ts
Create a new page to update the payment information and reprocess the pending invoices.
**Update payment method:**
**Reprocess pending invoices:**
**Task:** [DAT-1133](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1133)
=> [DAT-1133] - Create a new page to update the payment information and reprocess the pending invoices

src/App.test.js
**Jira TIcket:** https://makingsense.atlassian.net/browse/DAT-1260
=> fix: fix warning in App.test.js

src/components/Plans/Checkout/PaymentMethod/PaymentMethod.js
Redirect to the login when the user is cancelated
**Task:** [DAT-1269](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1269)
=> [DAT-1269] - Redirect to the login when the user is cancelated

src/services/control-panel-service.ts
The Facebook card was on the "external integrations" section but since it's actually an app of our own we are moving it to "native integrations".
=> [DOI-820] Move facebook card to native integrations

src/services/doppler-billing-user-api-client.double.ts, src/services/doppler-billing-user-api-client.test.ts, src/services/doppler-billing-user-api-client.ts
add new method in billing api service to get invoices
=> feat: add new method in billing api service

src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformation/ContactInformation/StatusMessage/index.js, src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformation/ContactInformation/StatusMessage/index.test.js, src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformation/ContactInformation/index.js, src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformation/ContactInformation/index.test.js, src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformation/index.js, src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformation/index.test.js, src/components/Plans/UpdatePaymentInformation/index.styles.js, src/i18n/en.js, src/i18n/es.js, src/services/doppler-billing-user-api-client.double.ts, src/services/doppler-billing-user-api-client.ts
Add contact information page when the user has transfer as payment method.
**Task:** [DAT-1273](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1273)
=> [DAT-1273] - Add contact information page when the user has transfer as payment method

src/components/Signup/Signup.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1307
=> feat: add classname to field group

src/components/Signup/Signup.js, src/components/form-helpers/form-helpers.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1307
**Before:**
**After:**
=> feat: add inline error

src/components/Signup/Signup.js, src/components/Signup/Signup.styles.js, src/i18n/en.js, src/i18n/es.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1302
**Result**
=> feat: add accordion

src/components/Login/Login.js, src/components/Login/Login.test.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1314
**More details in Slack**: https://makingsense.slack.com/archives/CRXR62TC2/p1672922750017419
**PREVIEW**
=> fix: fix redirect to webapp pages after login

src/components/Signup/Signup.styles.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1315
**BEFORE:** 
**AFTER:**
=> fix: fix link privacy policy in signup

src/services/control-panel-service.ts
I merged https://github.com/FromDoppler/doppler-webapp/pull/2210 by mistake 🤦‍♂️. This shouldn't be in production yet.
=> [No-Ticket] Remove Jumpseller from integrations section

src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformation/index.js, src/i18n/en.js, src/i18n/es.js
Update content of the transfer component
Screenshot:
**Before:**
**After:**
**Task:** [DAT-1317](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1317)
[DAT-1317]: https://makingsense.atlassian.net/browse/DAT-1317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-1317] - Update transfer component

src/components/Login/Login.js, src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformationSummary/index.js
Integrate update payment method with login
**Screenshot:**
**Before:**
**After:**
**Task:** [DAT-1284](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1284)
[DAT-1284]: https://makingsense.atlassian.net/browse/DAT-1284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-1284] - Integrate update payment method with login

src/components/DopplerPlus/AgenciesForm.test.js, src/components/Integrations/BigQuery/AuthorizationPage.test.js, src/components/Integrations/Shopify/Shopify.test.js, src/components/shared/Breadcrumb/Breadcrumb.js, src/components/shared/Breadcrumb/Breadcrumb.test.js
These changes are related to [this discussion](https://github.com/FromDoppler/doppler-webapp/pull/2221#discussion_r1062365354) we had.
Looking forward to your review!
=> [DOI-842] Use Link component when redirecting inside Webapp for breadcrumb

src/components/Dashboard/Dashboard.js, src/components/Dashboard/QuickActions/index.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1321
=> feat: add ids to quick actions

src/App.js, src/components/Plans/UpdatePaymentInformation/ContactInformation/StatusMessage/index.js, src/components/Plans/UpdatePaymentInformation/ContactInformation/StatusMessage/index.test.js, src/components/Plans/UpdatePaymentInformation/ContactInformation/index.js, src/components/Plans/UpdatePaymentInformation/ContactInformation/index.test.js, src/components/Plans/UpdatePaymentInformation/Reprocess/index.js, src/components/Plans/UpdatePaymentInformation/Reprocess/index.test.js, src/components/Plans/UpdatePaymentInformation/UpdatePaymentMethod/index.js, src/components/Plans/UpdatePaymentInformation/UpdatePaymentMethod/index.test.js, src/components/Plans/UpdatePaymentInformation/index.js, src/components/Plans/UpdatePaymentInformation/index.test.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1266
=> feat: refactor update payment information

src/components/Dashboard/QuickActions/index.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1334
=> feat: remove target of quick actions

src/components/Signup/DefaultConfirmationContent/index.js, src/components/Signup/DefaultConfirmationContent/index.test.js, src/components/Signup/DynamicConfirmationContent/index.js, src/components/Signup/DynamicConfirmationContent/index.test.js
Jira Ticket: [DAT-1338](https://makingsense.atlassian.net/browse/DAT-1338)
Change the resend limit of the confirmation email to 2
[DAT-1338]: https://makingsense.atlassian.net/browse/DAT-1338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: change confirmation email resend limit

src/i18n/es.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1346
=> feat: change label of button

src/components/Plans/UpdatePaymentInformation/Reprocess/index.js, src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformationSummary/index.js
Include failed status to get invoices.
**Task:** [DAT-1350](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1350)
[DAT-1350]: https://makingsense.atlassian.net/browse/DAT-1350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-1350] - Include failed status to get invoices

src/components/shared/Promotions/Promotions.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1336
=> feat: remove background image in promotion component

src/components/shared/Promotions/Promotions.js
This reverts commit 6f83ed0b3319e3208384c3d151a42186303fd56d.
=> Revert "feat: remove background image in promotion component"

src/components/Plans/Checkout/PaymentMethod/PaymentMethod.js, src/components/Plans/UpdatePaymentInformation/UpdatePaymentMethod/index.test.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1372
=> fix: update payment method after save

src/components/Plans/Checkout/Discounts/Discounts.js, src/components/Plans/Checkout/PaymentMethod/PaymentMethod.js, src/components/Plans/PlanCalculator/index.js
Disabled renovation when the user is not a free.
**Task:** [DAT-1380](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1380)
[DAT-1380]: https://makingsense.atlassian.net/browse/DAT-1380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-1380] - Disabled renovation when the user is not a free

package.json, yarn.lock
This reverts commit 7139361adb74f883bfbab2b1497989ef95792938.
=> Revert "chore(deps): update dependency @testing-library/dom to v9"

src/components/Dashboard/CompleteSteps/index.js, src/components/Dashboard/Dashboard.js
Jira Ticket: [DAT-1407](https://makingsense.atlassian.net/browse/DAT-1407)
Remove CompleteSteps button and automatically show Quick Actions if the 4 steps are completed.
Evidence:
https://user-images.githubusercontent.com/113532222/226430177-7c67e9bf-8602-4a1c-aed5-d66173505fe8.mp4
[DAT-1407]: https://makingsense.atlassian.net/browse/DAT-1407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: remove CompleteSteps button

src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1426
**Before:**
**After:**
=> feat: add zigzag

src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1429
=> feat: add taxes-excluded class to li and delete span

src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js, src/i18n/en.js, src/i18n/es.js
Add new message when the user has positive balance
**Task:** [DAT-1412](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1412)
[DAT-1412]: https://makingsense.atlassian.net/browse/DAT-1412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-1412] - Add new message when the user has positive balance

public/index.html
Related to https://github.com/FromDoppler/doppler-style-guide/pull/271 and https://github.com/FromDoppler/doppler-webapp/pull/2285
=> Remove Style Guide deprecated flag

src/components/Plans/Checkout/BillingInformation/BillingInformation.js, src/components/Plans/Checkout/BillingInformation/InvoiceRecipients/index.js, src/components/Plans/Checkout/BillingInformation/InvoiceRecipients/index.test.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1440
**BEFORE:**
**AFTER:**
=> feat: modify invoice recipipients in billing information section

src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js, src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.test.js, src/components/Plans/PlanCalculator/index.js, src/i18n/en.js, src/i18n/es.js, src/services/planService/index.test.ts, src/services/planService/index.ts
Allow to the users change the credits plans to contacts or emails plans.
**Before:**
**After:**
**Task:** [DAT-1399](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1399)
[DAT-1399]: https://makingsense.atlassian.net/browse/DAT-1399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-1399] - Integrate change credit plans to contacts or email plans

src/components/Plans/Checkout/BillingInformation/BillingInformation.js, src/components/Plans/Checkout/BillingInformation/BillingInformation.test.js, src/components/Plans/Checkout/PaymentMethod/PaymentMethod.js, src/components/Plans/Checkout/PaymentMethod/Transfer/Mexico/index.js, src/components/Plans/Checkout/PaymentMethod/Transfer/Mexico/index.test.js, src/i18n/en.js, src/i18n/es.js, src/services/doppler-billing-user-api-client.double.ts, src/services/doppler-billing-user-api-client.ts, src/services/static-data-client.double.ts, src/services/static-data-client.test.ts, src/services/static-data-client.ts
Jira ticket: https://makingsense.atlassian.net/browse/DAT-1439
Add Tax Regime field in the checkout when the payment method is TRANSFER and is from Mexico.
Evidence
-
Payload of the PUT request made to billing-user-api
=> [DAT-1439] - add tax regime field for mex transf

src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.js, src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.test.js, src/i18n/en.js, src/i18n/es.js
Show new message when the user buys a new plan and it is monthly
**Before:**
**After:**
**Task:** [DAT-1490](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1490)
[DAT-1490]: https://makingsense.atlassian.net/browse/DAT-1490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-1490]- Show new message when the plan is monthly

src/components/Plans/Checkout/BillingInformation/BillingInformation.js, src/components/Plans/Checkout/ContactInformation/ContactInformation.js, src/components/Plans/Checkout/PaymentMethod/PaymentMethod.js, src/components/Plans/Checkout/Step/Step.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1418
**Related UI PR:** https://github.com/FromDoppler/doppler-style-guide/pull/285
=> feat: add container to save and continue button

src/App.js, src/utils.ts
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1482
=> feat: add new zendesk

src/components/Plans/UpdatePaymentInformation/Reprocess/index.js, src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformationSummary/index.js, src/components/Plans/UpdatePaymentInformation/UpdatePaymentMethod/index.js
Pass the new payment status error (ClientFailed) to the api and apply new styles.
Task: [DAT-1527](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1527)
[DAT-1527]: https://makingsense.atlassian.net/browse/DAT-1527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-1527] - Pass the new payment status error to the api and apply new styles

src/components/ForgotPassword/ForgotPassword.js, src/components/Login/Login.js, src/components/form-helpers/form-helpers.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1530
**Note:** some styles are missing from the password field
=> Dat 1530 add accessible fields

src/components/BuyProcess/Slider/index.js, src/components/BuyProcess/Slider/index.test.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1574
**More details about this component**: https://makingsense.atlassian.net/browse/DAT-1574
=> feat: create new slider component

src/components/Plans/Checkout/PaymentMethod/PaymentMethod.js, src/components/Plans/Checkout/PurchaseSummary/PlanPurchase/index.js, src/components/Plans/UpdatePaymentInformation/DeclinedInvoicesList/index.js, src/components/Plans/UpdatePaymentInformation/index.js, src/doppler-types.ts
Add clover error messages in the new checkout and the reprocess invoices.
Task: [DAT-1580](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1580)
[DAT-1580]: https://makingsense.atlassian.net/browse/DAT-1580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-1580] - Add clover error messages

src/components/Signup/Signup.js, src/components/Signup/Signup.test.js, src/components/form-helpers/form-helpers.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1553
=> feat: add accessible fields to signup form

src/components/Plans/Checkout/Discounts/Discounts.js
=> fix: add null validation to description in discount component

src/components/Plans/Checkout/Discounts/Discounts.js
=> fix: fix discount percentage in discount component

src/components/BuyProcess/ShoppingCart/BuyButton/index.js, src/components/BuyProcess/ShoppingCart/BuyButton/index.test.js, src/components/BuyProcess/ShoppingCart/Clarification/index.js, src/components/BuyProcess/ShoppingCart/Clarification/index.test.js, src/components/BuyProcess/ShoppingCart/ItemCart/index.js, src/components/BuyProcess/ShoppingCart/ItemCart/index.test.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1581
=> Dat 1581 create shopping cart component

src/components/Plans/Checkout/PaymentMethod/CreditCard.js, src/components/form-helpers/form-helpers.js, src/i18n/en.js, src/i18n/es.js, src/validations.ts
Jira Ticket: [DAT-1585](https://makingsense.atlassian.net/browse/DAT-1585)
**Note**: error message updated to -> **spanish**: Ingresa una fecha de expiración válida / **english**: Enter a valid expiry date
Add frontend level validation to the date expiry field in the credit card form.
Evidence
-
https://github.com/FromDoppler/doppler-webapp/assets/113532222/de3cb0d2-7d98-47d1-a117-aa6be361278e
[DAT-1585]: https://makingsense.atlassian.net/browse/DAT-1585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add front end validation to expiry date

package.json, public/index.html, src/components/shared/C3Chart/C3Chart.styles.js, yarn.lock
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1604
=> Dat 1604 upgrade prettier

src/components/Plans/Checkout/PaymentMethod/PaymentMethod.js, src/components/Plans/Checkout/PurchaseSummary/PlanPurchase/index.js, src/components/Plans/UpdatePaymentInformation/DeclinedInvoicesList/index.js, src/components/Plans/UpdatePaymentInformation/index.js, src/doppler-types.ts
Map new clover error
**Task:** [DAT-1609](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1609)
[DAT-1609]: https://makingsense.atlassian.net/browse/DAT-1609?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-1609] - Map new clover error

src/components/Plans/Checkout/ContactInformation/ContactInformation.js, src/components/Plans/Checkout/ContactInformation/ContactInformation.test.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1598
=> Dat 1598 zip code required

src/components/shared/BreadcrumbNew/index.js, src/components/shared/BreadcrumbNew/index.test.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1610
**Related task:** https://cdn.fromdoppler.com/doppler-style-guide/documentation/main/storybook/?path=/story/components-new-breadcrumb--default
=> feat: add new breadcrumb

src/components/BuyProcess/PaymentFrequency/index.js, src/components/BuyProcess/PaymentFrequency/index.test.js, src/components/BuyProcess/RadioBox/index.js, src/components/BuyProcess/RadioBox/index.test.js, src/i18n/en.js, src/i18n/es.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1614
**RESULT:**
=> Dat 1614 create create new discount component

src/validations.test.js, src/validations.ts
Add new prefix to validate cuit.
**Task:** [DAT-1622](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1622)
[DAT-1622]: https://makingsense.atlassian.net/browse/DAT-1622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-1622] - Add new prefix to validate cuit

src/components/BuyProcess/NavigationTabs/index.js, src/components/BuyProcess/NavigationTabs/index.test.js, src/components/BuyProcess/RadioBox/index.js, src/components/BuyProcess/RadioBox/index.test.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1617
=> Dat 1617 create navigation tab component

src/components/BuyProcess/Slider/index.js, src/components/BuyProcess/Slider/index.test.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1627
**Result (example to use):**
https://github.com/FromDoppler/doppler-webapp/assets/84402180/aa4a1916-e7ea-4d19-8b32-c056c42ff402
=> feat: adjust slider to new design

src/components/Plans/UpdatePaymentInformation/Reprocess/index.js, src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformationSummary/index.js
Task: [DAT-1631](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1631)
[DAT-1631]: https://makingsense.atlassian.net/browse/DAT-1631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-1631] chore: add a new status to the invoices query

src/components/Plans/UpdatePaymentInformation/UpdatePaymentMethod/index.js
Task: [DAT-1649](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1649)
[DAT-1649]: https://makingsense.atlassian.net/browse/DAT-1649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-1649] chore: set default id selected plan value

src/components/ContactPolicy/ContactPolicy.js, src/components/ContactPolicy/ContactPolicy.test.js, src/i18n/en.js, src/i18n/es.js
Added validation for the entered data:
- **hour from** and **hour to** can not be empty.
- **hour from** and **hour to** must be in range between 0 and 23.
=> Dop 1445 add submit form validations

package.json, yarn.lock
Update dependency typescript to v4.5
=> fix(deps): update dependency typescript to v4.5

src/components/BuyProcess/NavigationTabs/index.js, src/components/BuyProcess/NavigationTabs/index.test.js
**Jira Ticket / Subtask:** https://makingsense.atlassian.net/browse/DAT-1678
=> chore(NavigationTabs): update component

src/components/BuyProcess/PaymentFrequency/index.js, src/components/BuyProcess/PaymentFrequency/index.test.js
**Jira Ticket / Subtask:** https://makingsense.atlassian.net/browse/DAT-1679
=> chore(PaymentFrequency): update component

src/components/BuyProcess/ShoppingCart/ItemCart/index.js, src/components/BuyProcess/ShoppingCart/ItemCart/index.test.js
**Jira Ticket / Subtask:** https://makingsense.atlassian.net/browse/DAT-1681
=> chore(ItemCart): update item cart component

src/services/doppler-account-plans-api-client.double.ts, src/services/doppler-account-plans-api-client.ts
**Jira Ticket / Subtask:** https://makingsense.atlassian.net/browse/DAT-1682
=> feat: add get plan billing details data endpoint

src/hooks/usePaymentMethodData/index.js, src/hooks/usePaymentMethodData/index.test.js
**Jira Ticket / Subtask:** https://makingsense.atlassian.net/browse/DAT-1687
=> feat: create use payment method data hook

src/components/BuyProcess/ShoppingCart/CheckoutLink/index.js, src/components/BuyProcess/ShoppingCart/CheckoutLink/index.style.js
**Jira ticket / subtask:** https://makingsense.atlassian.net/browse/DAT-1688
=> feat: create checkout link component

src/components/BuyProcess/PlanTypes/PlanTypeCard/index.js, src/components/BuyProcess/PlanTypes/index.js, src/components/Plans/Checkout/Checkout.js, src/components/Plans/PlanCalculator/BannerUpgrade/BannerUpgrade.js, src/components/Plans/PlanCalculator/BannerUpgrade/getUpgradeInfo.js, src/components/Plans/PlanCalculator/NavigatorTabs/NavigatorTabs.js, src/components/Plans/PlanCalculator/NavigatorTabs/NavigatorTabs.test.js, src/components/Plans/PlanCalculator/index.js, src/components/Plans/PlanCalculator/index.test.js, src/utils.ts
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1699
=> feat: change account type in plan selection and checkout

src/components/BuyProcess/PlanTypes/index.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1707
=> fix: add redirect when the user is not a free user

src/components/Plans/UpdatePaymentInformation/Reducers/reprocessReducer.js, src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformationSummary/UpdatePaymenInformationSummaryTitle/index.js, src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformationSummary/index.js, src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformationSummary/index.test.js, src/components/Plans/UpdatePaymentInformation/UpdatePaymentMethod/index.js, src/i18n/en.js, src/i18n/es.js
Allow change the payment method to AR transfer when the user is canceled and it has CC or MP.
**Task:** [DAT-1704](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1704)
[DAT-1704]: https://makingsense.atlassian.net/browse/DAT-1704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-1704] - Support change the payment method to Ar transfer

src/components/BuyProcess/NavigationTabs/index.js, src/components/BuyProcess/RadioBox/index.js, src/components/BuyProcess/RadioBox/index.test.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1721
=> feat: add info about plan to radio to plan-selection

src/components/Integrations/Shopify/Shopify.js, src/services/shopify-client.ts
The [last PR](https://github.com/FromDoppler/doppler-webapp/pull/2269) added an issue on the rendering of the lists status.
I'm fixing that.
=> [DOI-894] Fix issues in shopify UI

src/components/ContactPolicy/ContactPolicy.js, src/components/ContactPolicy/ContactPolicy.test.js
The contact policy time restriction section must be available now for all users.
=> feat: enable contact policy time restriction section

src/components/BuyProcess/PaymentFrequency/SubscriptionType/index.js, src/components/BuyProcess/PaymentFrequency/SubscriptionType/index.test.js, src/components/BuyProcess/PaymentFrequency/index.js, src/components/BuyProcess/PaymentFrequency/index.test.js, src/components/BuyProcess/PaymentFrequency/reducers/paymentFrequencyReducer.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1740
=> feat: add new payment frequency component

src/components/Login/Login.js, src/components/form-helpers/form-helpers.js, src/i18n/en.js, src/i18n/es.js, src/services/doppler-legacy-client.ts
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1762
=> feat: add ip notification to login

src/i18n/en.js, src/i18n/es.js
=> [No-Task] - Update message content

src/components/Login/Login.js, src/services/doppler-legacy-client.ts
Show a new message when the user is pending to confirmation
**Task:** [DAT-1766](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1766)
[DAT-1766]: https://makingsense.atlassian.net/browse/DAT-1766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-1766] Show a new message when the user is pending to confirmation

src/components/Login/Login.js
Remove disabled for the login button.
**Task:** [DAT-1773](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1773)
[DAT-1773]: https://makingsense.atlassian.net/browse/DAT-1773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-1773] - Remove disabled login button

src/components/Login/Login.js
Change componet for the access denied message
Task: [DAT-1768](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1768)
[DAT-1768]: https://makingsense.atlassian.net/browse/DAT-1768?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-1768] - Change componet for the access denied message

src/components/form-helpers/form-helpers.js
=> [No-Task] Change size error message

src/components/BuyProcess/PlanTypes/FeaturesPlanTypes/index.js, src/components/BuyProcess/PlanTypes/index.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1771
**Related Task:** https://cdn.fromdoppler.com/doppler-style-guide/documentation/main/types-of-plans.html
=> feat: add anchor to plan types

src/components/form-helpers/form-helpers.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1777
=> fix: remove inline style in messages

src/doppler-types.ts
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1787
=> feat: add number format option global variable

src/components/Plans/UpdatePaymentInformation/UpdatePaymentMethod/index.js
Include automatic debit when the user is blocked.
**Task:** [DAT-1695](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1695)
[DAT-1695]: https://makingsense.atlassian.net/browse/DAT-1695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-1695] - Include automatic debit when the user is blocked

package.json, src/components/Dashboard/reducers/firstStepsReducer.js, src/components/ForgotPassword/ForgotPassword.js, src/components/Integrations/index.js, src/components/Login/Login.js, src/components/Plans/PlanCalculator/reducers/plansByTypeReducer.js, src/components/RedirectWithQuery.js, src/components/Signup/Signup.js, src/components/form-helpers/form-helpers.js, src/components/shared/ControlPanelBox/ControlPanelBox.js, src/components/shared/Pagination/Pagination.js, src/components/shared/Promotions/Promotions.js, src/services/shopify-client.ts, yarn.lock
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1826
https://github.com/FromDoppler/doppler-webapp/assets/84402180/acdbd593-c80c-4746-8e2f-66f469a5c7d4
=> feat: add christmas to login signup and forgot

src/components/ForgotPassword/ForgotPassword.js, src/components/Login/Login.js, src/components/Signup/Signup.js, src/components/shared/Promotions/Promotions.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1844
=> chore: remove christmas logo

src/i18n/en.js, src/i18n/es.js
Task: [DAT-1846](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1846)
[DAT-1846]: https://makingsense.atlassian.net/browse/DAT-1846?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-1846] Update message content

src/i18n/en.js, src/i18n/es.js
Update content on the dasboard
**Task:** [DAT-1847](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1847)
[DAT-1847]: https://makingsense.atlassian.net/browse/DAT-1847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-1847] - Update content

src/i18n/en.js, src/i18n/es.js
=> [DOI-1174] Change dkim section name

src/components/BuyProcess/ShoppingCart/NextInvoices/index.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1875
**English**
**Spanish**
=> fix: adjust next invoice date

src/components/BuyProcess/Stepper/index.js, src/components/BuyProcess/Stepper/index.test.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1871
=> feat: create stepper component

src/components/BuyProcess/ShoppingCart/index.js, src/components/BuyProcess/ShoppingCart/utils.js, src/i18n/en.js, src/i18n/es.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1879
=> feat: add discount for admin

package.json, src/components/Login/Login.js, src/hooks/useFingerPrinting/index.js, src/services/doppler-legacy-client.ts, yarn.lock
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1841
**More about finger printing here:** https://makingsense.atlassian.net/browse/DAT-1820
=> Dat 1841 add finger printing

src/components/Plans/Checkout/PaymentMethod/CreditCard.js, src/components/Plans/Checkout/PaymentMethod/MercadoPagoArgentina/index.js
Task: [DAT-1747](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1747)
[DAT-1747]: https://makingsense.atlassian.net/browse/DAT-1747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DAT-1747 Prevent CC and MERCADO PAGO payment method form fields from resetting

src/components/BuyProcess/ShoppingCart/Promocode/index.js, src/components/BuyProcess/ShoppingCart/index.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1887
=> feat: payment frecuency is enabled when the user apllies a promocode

src/components/Login/Login.js, src/hooks/useFingerPrinting/fingerprintV2.js, src/hooks/useFingerPrinting/index.js, src/services/doppler-legacy-client.ts
Task: [DAT-1891](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1891)
[DAT-1891]: https://makingsense.atlassian.net/browse/DAT-1891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-1891] Add fingerprintv2

src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformationSummary/index.js, src/components/Plans/UpdatePaymentInformation/UpdatePaymentMethod/index.js, src/components/Plans/UpdatePaymentInformation/index.js, src/i18n/en.js, src/i18n/es.js
Task: [DAT-1904](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1904)
[DAT-1904]: https://makingsense.atlassian.net/browse/DAT-1904?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-1904] Allow change redirection on updating payment information

src/components/BuyProcess/ShoppingCart/Promocode/index.js, src/components/BuyProcess/ShoppingCart/Promocode/reducers/promocodeReducer.js, src/components/BuyProcess/ShoppingCart/Promocode/reducers/promocodeReducer.test.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1957
=> fix: fix promo argentina

src/i18n/en.js, src/i18n/es.js
Merge and publish after Doppler's release
=> [DOI-1335] Rename landings option in control panel

package.json, src/components/BuyProcess/LandingPacksSelection/index.js, src/components/BuyProcess/PlanTypes/PlanTypeCard/index.test.js, src/components/BuyProcess/PlanTypes/index.js, src/components/BuyProcess/PlanTypes/index.test.js, src/components/BuyProcess/ShoppingCart/CheckoutButton/LandingPackCheckoutButton.js, src/components/BuyProcess/ShoppingCart/CheckoutButton/LandingPackCheckoutButton.test.js, src/components/BuyProcess/ShoppingCart/CheckoutLink/LandingPackCheckoutLink.js, src/components/BuyProcess/ShoppingCart/CheckoutLink/LandingPackCheckoutLink.test.js, src/hooks/useFetchtLandingPacks/index.test.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-2007
=> feat: add tests

src/App.js, src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.js
**JIRA TICKET:** https://makingsense.atlassian.net/browse/DAT-2018
=> Revert "feat: add comments to landing plan"

src/App.js, src/components/BuyProcess/ShoppingCart/index.js, src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-2037
=> Dat 2037 fix total field

src/App.js, src/components/BuyProcess/LandingPacksSelection/index.js, src/components/BuyProcess/LandingPacksSelection/reducers/deleteLandingPagesReducer.js, src/components/BuyProcess/LandingPacksSelection/reducers/deleteLandingPagesReducer.test.js, src/components/BuyProcess/ShoppingCart/CheckoutButton/LandingPackCheckoutButton.js, src/components/BuyProcess/ShoppingCart/CheckoutButton/LandingPackCheckoutButton.test.js, src/components/BuyProcess/ShoppingCart/index.js, src/components/BuyProcess/ShoppingCart/utils.js, src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.js, src/i18n/en.js, src/i18n/es.js, src/services/doppler-legacy-client.ts
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-2045
=> Dat 2045 improve landing packs

src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-2049
=> fix: fix modal landing plan

.env.development, .env.int, .env.production, .env.qa, src/components/BuyProcess/LandingPacksSelection/LandingPacksMessages/index.js
Change correct my landings url
=> [No-Task] Change correct my landings url

src/components/BuyProcess/LandingPacksSelection/LandingPacksMessages/index.js, src/i18n/en.js, src/i18n/es.js
Update message component.
**Task:** [DAT-2055](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2055)
[DAT-2055]: https://makingsense.atlassian.net/browse/DAT-2055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=>  [DAT-2055] - Update message component

src/components/BuyProcess/LandingPacksSelection/index.js, src/components/BuyProcess/ShoppingCart/CheckoutButton/LandingPackCheckoutButton.js, src/components/BuyProcess/ShoppingCart/index.js, src/components/BuyProcess/ShoppingCart/utils.js
Change position cancel message
Task: [DAT-2056](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2056)
[DAT-2056]: https://makingsense.atlassian.net/browse/DAT-2056?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2056] Change position cancel message

src/App.js, src/components/ControlPanel/ColaboratorsSections/Modal/index.js, src/components/ControlPanel/ColaboratorsSections/index.js, src/i18n/en.js, src/i18n/es.js
This adds a new section to manage colaborators.
https://github.com/FromDoppler/doppler-webapp/assets/34007887/19ff9fe6-b50e-49e4-8d62-69576a0da987
=> [DOI-1314] Add colaborators section

src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.js
Change type message
**Task:** [DAT-2059](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2059)
[DAT-2059]: https://makingsense.atlassian.net/browse/DAT-2059?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2059] - Change type message

src/components/Signup/Signup.js, src/components/Signup/Signup.test.js, src/services/doppler-legacy-client.ts
Task: [DAT-2064](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2064)
[DAT-2064]: https://makingsense.atlassian.net/browse/DAT-2064?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2064] Send fingerprint when user is created

src/i18n/es.js
=> [No Task] - Fix typo issue

src/i18n/en.js, src/i18n/es.js
Update landings card url
**Task:** [DAT-2072](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2072)
[DAT-2072]: https://makingsense.atlassian.net/browse/DAT-2072?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=>  [DAT-2072] - Update landings card url

src/components/BuyProcess/LandingPacksSelection/index.js
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-2073
=> feat: redirect to plan ypes

src/i18n/es.js
Update content for the landing pop up.
**Task:** [DAT-2085](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62/backlog?selectedIssue=DAT-2085)
[DAT-2085]: https://makingsense.atlassian.net/browse/DAT-2085?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2085] - Update content for the landing pop up

src/components/Dashboard/Dashboard.js, src/components/TypeformSurvey/index.js
Task: [DAT-2070](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2070)
[DAT-2070]: https://makingsense.atlassian.net/browse/DAT-2070?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2070] Remove overflow hidden style from body after survey form is closed

src/components/ControlPanel/CollaboratorsSections/Forms/CollaboratorInviteForm.js, src/components/ControlPanel/CollaboratorsSections/Forms/CollaboratorInviteForm.test.js, src/components/ControlPanel/CollaboratorsSections/index.js, src/components/ControlPanel/CollaboratorsSections/index.test.js, src/services/doppler-user-api-client.double.ts, src/services/doppler-user-api-client.test.ts, src/services/doppler-user-api-client.ts
I'm adding the request for invite cancelation and re-send email invitation.
Also removed the edition obtion since it won't be used for now.
=> [DOI-1394] Add functiotionality to dropdown menu

src/components/CollaborationInvite/index.js
Restart session manager on successful response and then redirect to dashboard.
=> [DOI-1524] Add session restart after successful invite

src/components/BuyProcess/ShoppingCart/CheckoutButton/index.js, src/components/BuyProcess/ShoppingCart/CheckoutButton/index.test.js, src/components/Plans/Checkout/Checkout.js, src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.js, src/components/Plans/Checkout/CheckoutSummary/PlanChatInformation/index.js, src/components/Plans/Checkout/Reducers/checkoutSummaryReducer.js, src/i18n/en.js, src/i18n/es.js, src/services/doppler-billing-user-api-client.double.ts, src/services/doppler-billing-user-api-client.ts
Integrate with the success page
Task: [DAT-2106](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2106)
[DAT-2106]: https://makingsense.atlassian.net/browse/DAT-2106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2106] Integrate with the success page

src/components/BuyProcess/PlanChat/index.js, src/components/BuyProcess/PlanChat/index.test.js, src/components/BuyProcess/ShoppingCart/index.js, src/hooks/useFetchConversationPlans/conversationPlansReducer/index.js, src/hooks/useFetchConversationPlans/conversationPlansReducer/index.test.js, src/hooks/useFetchConversationPlans/index.js, src/hooks/useFetchConversationPlans/index.test.js, src/services/doppler-legacy-client.test.js, src/services/doppler-legacy-client.ts
Set the current chat plan.
**Task:** [DAT-2115](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2115)
[DAT-2115]: https://makingsense.atlassian.net/browse/DAT-2115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2115] - Set the current chat plan

src/App.js, src/components/ControlPanel/CollaboratorEditionSection/index.js, src/components/ControlPanel/CollaboratorEditionSection/index.test.js, src/components/form-helpers/form-helpers.js, src/i18n/en.js, src/i18n/es.js
=> [DOI-1375] Add Collaborator edition section

src/components/BuyProcess/BuyProcessLayout/index.js
=> [No-Task] - Fix issue

src/components/ControlPanel/CollaboratorEditionSection/index.js, src/components/Login/Login.js, src/i18n/en.js, src/i18n/es.js, src/services/doppler-legacy-client.ts
This will display a proper message when the userAccount doesn't have any user associated.
=> [DOI-1547] Add missing login rejection status

src/components/BuyProcess/PlanChat/index.js, src/components/BuyProcess/ShoppingCart/CheckoutButton/index.js, src/components/BuyProcess/ShoppingCart/index.js, src/components/BuyProcess/ShoppingCart/utils.js
Send total buy conversation plan
**Task:** [DAT-2140](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2140)
[DAT-2140]: https://makingsense.atlassian.net/browse/DAT-2140?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2140] - send total buy conversation plan

src/components/shared/Promotional/Promotional.js
Adds spinner and disable button while request is in progress
=> [DOI-1558] Add button spinner for promotional pages

src/components/shared/Promotional/Promotional.js
To avoid executing an undefined func I need to pass it as parameter.
=> [DOI-1558] Send func as parameter

.env.qa, src/services/doppler-legacy-client.ts
Set in true to buy conversation plan in qa
=> [No-Task] Set in true to buy conversation plan in qa

src/App.js, src/components/BuyProcess/PlanChat/index.js, src/components/BuyProcess/ShoppingCart/CheckoutButton/index.js, src/components/BuyProcess/ShoppingCart/index.js, src/components/Plans/BuyConversation/index.js, src/components/Plans/BuyConversation/index.test.js, src/components/Plans/Checkout/Checkout.js, src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.js, src/i18n/en.js, src/i18n/es.js, src/services/doppler-legacy-client.ts
Include page for buy only chat plan
Task: [DAT-2151](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2151)
[DAT-2151]: https://makingsense.atlassian.net/browse/DAT-2151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2151] - Include page for buy only chat plan

src/components/Plans/Checkout/Checkout.js
=> [No-ticket] Fix issue when show summary

src/components/BuyProcess/ShoppingCart/utils.js
fix issue when redirect to the summary page
Task: [DAT-2151](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2151)
[DAT-2151]: https://makingsense.atlassian.net/browse/DAT-2151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2151] - fix issue when redirect to the summary page

package.json, src/components/BuyProcess/LandingPacksSelection/LandingPacks/index.js, src/components/BuyProcess/ShoppingCart/utils.js
Fix issue when try to buy landings
=> [No-Task] Fix issue when try to buy landings

src/components/BuyProcess/ShoppingCart/CheckoutLink/index.js
Task: [DAT-2155](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2155)
[DAT-2155]: https://makingsense.atlassian.net/browse/DAT-2155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Allow skip marketing step

src/i18n/es.js
Task: [DAT-2150](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2150)
[DAT-2150]: https://makingsense.atlassian.net/browse/DAT-2150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: update first dashboard card content

.env.production
Set in true buy conversations plan in the PROD environment
**Task:** [DAT-2161](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2161)
[DAT-2161]: https://makingsense.atlassian.net/browse/DAT-2161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2161] Set in true buy conversations plan in the PROD environment

src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.js
Task: [DAT-2157](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2157)
[DAT-2157]: https://makingsense.atlassian.net/browse/DAT-2157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Change landing plans modal opacity

src/components/Signup/Signup.js, src/services/doppler-legacy-client.doubles.ts, src/services/doppler-legacy-client.ts
If the colaborator has already validate his account, it will not be necesary sent the verification email
=> [DOI-1389] Complete registration of colaborator 

src/i18n/es.js
Task: [DAT-2180](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?assignee=5f4e5c31fdc3f5003f312f2e%2C712020%3Ac04bfb53-891e-479b-8644-963a49902e8d%2Cunassigned&selectedIssue=DAT-2180)
[DAT-2180]: https://makingsense.atlassian.net/browse/DAT-2180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update card content

src/components/BuyProcess/PlanChat/PlanBenefits/index.js, src/i18n/en.js, src/i18n/es.js
Add new translations for the WhatsApp benefits
**Task:** [DAT-2190](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2190)
[DAT-2190]: https://makingsense.atlassian.net/browse/DAT-2190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2190] - Add new translations for the WhatsApp benefits

src/components/BuyProcess/PlanChat/BannerUpgrade/index.js, src/components/BuyProcess/PlanChat/PlanBenefits/index.js, src/components/BuyProcess/PlanChat/SelectedPlanChat/index.js, src/components/BuyProcess/PlanChat/index.js, src/components/BuyProcess/PlanChat/index.test.js, src/components/BuyProcess/Slider/index.js, src/hooks/useFetchConversationPlans/conversationPlansReducer/index.js, src/hooks/useFetchConversationPlans/index.js, src/hooks/useFetchConversationPlans/index.test.js, src/i18n/en.js, src/i18n/es.js, src/services/doppler-account-plans-api-client.double.ts, src/services/doppler-account-plans-api-client.ts, src/services/doppler-legacy-client.ts
Support plan more 2000 conversations
Task: [DAT-2133](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2133)
[DAT-2133]: https://makingsense.atlassian.net/browse/DAT-2133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2133] - Support plan more 2000 conversations

src/components/BuyProcess/BuyProcessLayout/index.js, src/components/BuyProcess/ShoppingCart/CheckoutButton/index.js, src/components/BuyProcess/ShoppingCart/CheckoutLink/index.js, src/components/BuyProcess/ShoppingCart/utils.js, src/components/Plans/Checkout/Checkout.js
Task: [DAT-2158](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2158)
[DAT-2158]: https://makingsense.atlassian.net/browse/DAT-2158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Always allow buy conversation plan

src/components/Conversations/index.js, src/components/Conversations/index.test.js
Task: [DAT-2199](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2199)
[DAT-2199]: https://makingsense.atlassian.net/browse/DAT-2199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2199] Redirect users with convertsetion active or cms

src/i18n/es.js
Task: [DAT-2229](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2229)
[DAT-2229]: https://makingsense.atlassian.net/browse/DAT-2229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2229] Uppdate dashboard's slider content

src/components/Conversations/index.js, src/components/Conversations/index.test.js
Task: [DAT-2271](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2271)
[DAT-2271]: https://makingsense.atlassian.net/browse/DAT-2271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2271]

public/index.html
Task: [DAT-2277](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2277)
[DAT-2277]: https://makingsense.atlassian.net/browse/DAT-2277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Task-2277] Update zendesk script

src/i18n/es.js
Task: [DAT-2284](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2284)
[DAT-2284]: https://makingsense.atlassian.net/browse/DAT-2284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2284] Update card content

src/components/Plans/Checkout/PaymentMethod/CreditCard.js, src/components/Plans/Checkout/PaymentMethod/MercadoPagoArgentina/index.js, src/components/Plans/Checkout/PaymentMethod/PaymentMethod.test.js, src/components/Plans/UpdatePaymentInformation/UpdatePaymentMethod/index.test.js, src/components/form-helpers/form-helpers.js, src/i18n/en.js, src/i18n/es.js, src/validations.test.js, src/validations.ts
Add check digit verification for the credit card
**Task:** [DAT-1961](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1961)
[DAT-1961]: https://makingsense.atlassian.net/browse/DAT-1961?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-1961] - Add check digit verification for the credit card

src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.js, src/i18n/en.js, src/i18n/es.js
Add slider for the onsite plan
**Task:** [DAT-2265](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2265)
[DAT-2265]: https://makingsense.atlassian.net/browse/DAT-2265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2265] - Add slider for the onsite plan

src/i18n/en.js, src/i18n/es.js
Update message for the invalid credit card.
Task: [DAT-1961](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1961)
[DAT-1961]: https://makingsense.atlassian.net/browse/DAT-1961?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-1961] - Update message for the invalid credit card

src/components/Plans/Checkout/PaymentMethod/CreditCard.js, src/components/Plans/Checkout/PaymentMethod/MercadoPagoArgentina/index.js, src/components/form-helpers/form-helpers.js, src/i18n/en.js, src/i18n/es.js, src/validations.test.js, src/validations.ts
Fix issue validate credit card
=> [no-task] - Fix issue validate credit card

src/components/BuyProcess/ShoppingCart/CheckoutButton/OnSite/index.js, src/components/BuyProcess/ShoppingCart/utils.js
pass discount parameter to the checkout summary
=> fix: pass discount parameter to the checkout summary

src/components/ForgotPassword/ForgotPassword.js, src/components/Login/Login.js, src/components/Signup/Signup.js, src/components/shared/Promotions/Promotions.js
** 🎄 🎁 Add christmas to login, signup and forgot** 🎁 🎄
Task: [DAT-2299](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2299)
[DAT-2299]: https://makingsense.atlassian.net/browse/DAT-2299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2299] - Add christmas to login signup and forgot 

src/components/OnSite/index.js, src/components/OnSite/index.test.js
Redirect create widget when the user active onsite plan
**Task:** [DAT-2301](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2301)
[DAT-2301]: https://makingsense.atlassian.net/browse/DAT-2301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2301] - Redirect create widget when the user active onsite plan

src/components/ForgotPassword/ForgotPassword.js, src/components/Login/Login.js, src/components/Signup/Signup.js, src/components/shared/Promotions/Promotions.js
Remove christmas logo
**Task:** [DAT-2310](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2310)
[DAT-2310]: https://makingsense.atlassian.net/browse/DAT-2310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2310] - Remove christmas logo

src/hooks/useFetchOnSitePlans/index.js
Fix issue when the user has the free plan
=> [no-task] - Fix issue when the user has the free plan

src/hooks/useFetchOnSitePlans/index.js
=> [no-task] - Rename Fee property to fee

src/components/Plans/Checkout/PaymentMethod/PaymentMethod.js, src/i18n/en.js, src/i18n/es.js
Task: [DAT-2326](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2326)
[DAT-2326]: https://makingsense.atlassian.net/browse/DAT-2326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2326] Add new error message

src/i18n/en.js, src/i18n/es.js
=> Update error message

src/components/Plans/Checkout/PaymentMethod/PaymentMethod.js, src/i18n/en.js, src/i18n/es.js
Update content of the error about invalid credit card.
Task: [DAT-2356](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2356)
[DAT-2356]: https://makingsense.atlassian.net/browse/DAT-2356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2356] - Update content of the error about invalid credit card

src/components/Dashboard/LearnWithDoppler/TextPreviewPost/TextPreviewPost.js, src/components/Dashboard/LearnWithDoppler/index.js
Remove target blank for the app url
=> [no-task] - Remove target blank for the app url

src/components/OnSite/index.js, src/components/shared/Promotional/Promotional.js
Add class for the item in the Promotional page.
**Task:** [DAT-2366](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2366)
[DAT-2366]: https://makingsense.atlassian.net/browse/DAT-2366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2366] - Add class for the item in the Promotional page

src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.js, src/i18n/en.js
Task: [DAT-2280](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2280)
[DAT-2280]: https://makingsense.atlassian.net/browse/DAT-2280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2280]

src/App.js, src/components/MyPlan/index.js, src/components/MyPlan/index.test.js
Add basic my-plan page.
Task: [DAT-2391](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2391)
[DAT-2391]: https://makingsense.atlassian.net/browse/DAT-2391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2391] - Add basic my-plan page

src/components/Dashboard/LearnWithDoppler/index.js, src/i18n/en.js, src/i18n/es.js
Task: [DAT-2398](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2398)
[DAT-2398]: https://makingsense.atlassian.net/browse/DAT-2398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2398]

src/components/SiteTrackingRequired/SiteTrackingRequired.js
Task: [DAT-2325](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2325)
[DAT-2325]: https://makingsense.atlassian.net/browse/DAT-2325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2325]

src/components/MyPlan/AddOns/index.js, src/components/MyPlan/BillingHistory/index.js, src/components/MyPlan/Header/index.js, src/components/MyPlan/PaymentMethod/index.js, src/components/MyPlan/SubscriptionDetails/index.js, src/components/MyPlan/Tabs/index.js, src/components/MyPlan/index.js
Add tabs component in the my-plan page.
**Task:** [DAT-2395](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2395)
[DAT-2395]: https://makingsense.atlassian.net/browse/DAT-2395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2395] - Add tabs component in the my-plan page

src/components/Dashboard/LearnWithDoppler/TextPreviewPost/TextPreviewPost.js, src/components/Dashboard/LearnWithDoppler/index.js
Task: [DAT-2403](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2403)
[DAT-2403]: https://makingsense.atlassian.net/browse/DAT-2403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2403] add params to the dashboard card

src/components/BuyProcess/ShoppingCart/Promocode/index.js
The promocode is not showing in the different sections in the checkout.
**Bug:** [](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2382)
=> [DAT-2382] - fix issue with promocode

src/components/BuyProcess/ShoppingCart/CheckoutButton/index.js
Task: [DAT-2445](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2445)
[DAT-2445]: https://makingsense.atlassian.net/browse/DAT-2445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2445]

src/components/Dashboard/Dashboard.js, src/components/Dashboard/Dashboard.test.js
Show first steps in the dashboard page.
**Task:** [DAT-2452](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2452)
[DAT-2452]: https://makingsense.atlassian.net/browse/DAT-2452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2452] - Show first steps in the dashboard page

src/services/doppler-billing-user-api-client.ts
Integrate with the activate ednpoint.
**Task:** [DAT-2448](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2448)
[DAT-2448]: https://makingsense.atlassian.net/browse/DAT-2448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2448] - Integrate with the activate ednpoint

public/index.html
Task: [DAT-2450](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2450)
[DAT-2450]: https://makingsense.atlassian.net/browse/DAT-2450?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2450] Update zendesk script

src/i18n/es.js
Update card about EMMS is about to begin
=> Update card about EMMS is about to begin

src/i18n/en.js
=> fix issue with english

src/i18n/en.js, src/i18n/es.js
Update card for the EMMS in progress.
**Task:** [DAT-2470](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2470)
[DAT-2470]: https://makingsense.atlassian.net/browse/DAT-2470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2470] - Update card for the emms in progress

src/i18n/en.js, src/i18n/es.js
Update EMMS card when the event is ended.
**Task:** [DAT-2471](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2471)
[DAT-2471]: https://makingsense.atlassian.net/browse/DAT-2471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2471] - Update EMMS card when the event is ended

src/components/PushNotifications/index.js, src/components/PushNotifications/index.test.js
Update url to redirect after acitvate push.
**Task:** [DAT-2476](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2476)
[DAT-2476]: https://makingsense.atlassian.net/browse/DAT-2476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2476] - Update url to redirect after acitvate push

src/components/Plans/Checkout/PaymentMethod/AutomaticDebit/Argentina/index.js, src/components/Plans/Checkout/PaymentMethod/PaymentMethod.js, src/doppler-types.ts, src/i18n/en.js, src/i18n/es.js
Add CBU validations in the checkout.
**Task:** [DAT-2454](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2454)
[DAT-2454]: https://makingsense.atlassian.net/browse/DAT-2454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2454] - Add CBU validations in the checkout

src/components/BuyProcess/ShoppingCart/ItemCart/index.js, src/components/BuyProcess/ShoppingCart/ItemCart/index.test.js, src/components/BuyProcess/ShoppingCart/index.js, src/components/BuyProcess/ShoppingCart/utils.js, src/i18n/en.js, src/i18n/es.js, src/services/doppler-account-plans-api-client.test.ts
Update legend for the buy credits
**Task:** [DAT-2508](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2508)
[DAT-2508]: https://makingsense.atlassian.net/browse/DAT-2508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2508] - Update legend for the buy credits

src/components/BuyProcess/NavigationTabs/index.js, src/components/BuyProcess/PlanSelection/index.js, src/components/BuyProcess/PlanSelection/reducers/plansByTypeReducer.js, src/components/BuyProcess/ShoppingCart/index.js, src/hooks/useDefaultPlanType/index.js, src/hooks/useDefaultPlanType/index.test.js
Fix issue when the user select contacts plan
**Task:** [DAT-2517](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2517)
[DAT-2517]: https://makingsense.atlassian.net/browse/DAT-2517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2517] - Fix issue when the user select contacts plan

src/components/BuyProcess/BuyProcessLayout/index.js
Fix issue in the stepper when buyType is null
**Task:** [DAT-2511](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2511)
[DAT-2511]: https://makingsense.atlassian.net/browse/DAT-2511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2511] - Fix issue in the stepper when buyType is null

src/components/BuyProcess/ShoppingCart/utils.js, src/i18n/es.js
Show information for the addon when the plan is by credits
=> [no-task] - Show information for the addon when the plan is by credits

src/components/BuyProcess/PlanChat/PlanBenefits/index.js, src/components/BuyProcess/PlanChat/index.js, src/i18n/en.js, src/i18n/es.js
Update messages for the conversations section
=> [no-task] Update messages for the conversations section

src/components/MyPlan/AddOns/TransactionalEmails/index.js
Change url when buy transactional emails from addons.
**Task:** [DAT-2563](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2563)
[DAT-2563]: https://makingsense.atlassian.net/browse/DAT-2563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2563] - Change url when buy transactional emails from addons

src/components/MyPlan/AddOns/Conversations/index.js, src/components/MyPlan/AddOns/DedicatedEnvironment/index.js, src/components/MyPlan/AddOns/DedicatedIP/index.js, src/components/MyPlan/AddOns/LandingPages/index.js, src/components/MyPlan/AddOns/ListConditioning/index.js, src/components/MyPlan/AddOns/OnSite/index.js, src/components/MyPlan/AddOns/PushNotification/index.js, src/components/MyPlan/AddOns/Sms/index.js, src/components/MyPlan/AddOns/TransactionalEmails/index.js, src/components/MyPlan/AddOns/index.js, src/components/MyPlan/SubscriptionDetails/index.js, src/i18n/es.js
Update class for the price section
=> [no-task] - Update class for the price section

src/components/MyPlan/SubscriptionDetails/EmailMarketingPlan/index.js
Update messages when the plan is by emails
=> [no-task] - Update messages when the plan is by emails

src/components/MyPlan/SubscriptionDetails/EmailMarketingPlan/index.js, src/i18n/en.js
Supports free user to the MyPlan page
=> [no-task] - Supports free user

src/components/MyPlan/SubscriptionDetails/EmailMarketingPlan/index.js
Add new classes for the cards.
**Task:** [DAT-2568](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2568)
[DAT-2568]: https://makingsense.atlassian.net/browse/DAT-2568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2568 - Add new classes for the cards

src/components/MyPlan/AddOns/Collaborators/index.js, src/components/MyPlan/AddOns/Collaborators/index.test.js, src/components/MyPlan/AddOns/index.js, src/components/MyPlan/AdditionalServices/Form/index.js, src/i18n/en.js, src/i18n/es.js
=> [no-task] - Add collaborators card

src/components/MyPlan/AddOns/Sms/index.js, src/components/MyPlan/AddOns/index.js
Redirect buy email plan when the user is free and want buy sms
=> [on-task] - Redirect buy email plan when the user is free and want buy sms

src/components/MyPlan/SubscriptionDetails/index.js
Redirect to demo when the user is free
=> [no-task] - Redirect to demo when the user is free

src/components/MyPlan/CancellationAccount/Modals/SuccessAccountCancellation/index.js, src/components/MyPlan/CancellationAccount/index.js, src/i18n/en.js, src/i18n/es.js
Add success cancellation account modal
=> [no-task] - Add success cancellation account modal

src/components/MyPlan/CancellationAccount/Modals/AccountCancellationRequest/index.js, src/components/MyPlan/CancellationAccount/Modals/CancellationWithoutRetention/index.js
=> [no-task] - Add loading in the button

src/components/MyPlan/CancellationAccount/Modals/CancellationWithoutRetention/index.js, src/components/MyPlan/CancellationAccount/Modals/SuccessAccountCancellation/index.js, src/i18n/en.js, src/i18n/es.js
=> [no-task] - Update title modal

src/components/MyPlan/CancellationAccount/Modals/CancellationWithoutRetention/index.test.js, src/components/MyPlan/CancellationAccount/Modals/ConsultingOffer/index.js, src/components/MyPlan/CancellationAccount/Modals/ConsultingOffer/index.test.js, src/components/MyPlan/CancellationAccount/Modals/SuccessAccountCancellation/index.test.js, src/components/MyPlan/CancellationAccount/Modals/SuccessScheduledCancellation/index.test.js, src/services/doppler-billing-user-api-client.double.ts, src/services/doppler-billing-user-api-client.ts
Update logic when set the schedule cancellation request
=> [no-task] - Update logic when set the schedule cancellation request

src/components/MyPlan/CancellationAccount/Modals/ConsultingOffer/index.js, src/services/doppler-billing-user-api-client.double.ts, src/services/doppler-billing-user-api-client.test.ts, src/services/doppler-billing-user-api-client.ts
Send consulting offer notification to the customer experience.
**Task:** [DAT-2633](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2633)
[DAT-2633]: https://makingsense.atlassian.net/browse/DAT-2633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2633] - Send consulting offer notification to the customer experience

src/components/MyPlan/CancellationAccount/Modals/AccountCancellationRequest/index.js, src/components/MyPlan/CancellationAccount/Modals/AccountCancellationRequest/index.test.js, src/components/MyPlan/CancellationAccount/index.js, src/doppler-types.ts, src/i18n/en.js, src/i18n/es.js
Update flow for the users with contacts plan or monthly.
**Task:** [DAT-2638](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2638)
[DAT-2638]: https://makingsense.atlassian.net/browse/DAT-2638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2638] - Update flow for the users with contacts plan or monthly

src/i18n/en.js, src/i18n/es.js
task: [DAT-2676](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2676)
[DAT-2676]: https://makingsense.atlassian.net/browse/DAT-2676?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2676] Update Mi Plan content
