FromDoppler/doppler-webapp

- .travis.yml
- build-w-docker.sh
- package.json
- Add run test in build
- Add travis configuration inital settings
- Add docker and jenkings configuration
> [no ticket] Add Travis configuration

- package.json
- src/App.js
- src/components/Header/Nav.js
- src/serviceWorker.js
- yarn.lock
- Add Prettier to format code formatter (https://prettier.io/)
- Add Prettier settings https://prettier.io/docs/en/configuration.html
- Add Prettier in build to correct files
> [no ticket] Add Prettier configuration

- src/components/Header/Nav.js
- Add service test method to test cors in doppler app
- Obtain user data from doppler and show in screen
> [no ticket] Add service method to test cors in doppler

- watch-w-docker.sh
Add hot reload to change the files and see it reflected in localhost. For local development using docker.
> fix(docker): add hot reload to watch

- watch-w-docker.sh
Inline comment caused script not working.
> fix(docker): move comment up

- package.json
- src/App.js
- src/App.test.js
- src/i18n/en.json
- src/i18n/es.json
- src/index.js
- yarn.lock
At the request of the audience 🥁 
- Add React Intl package
Documentation:
https://github.com/yahoo/react-intl/wiki
> feat: add react-intl package

- .env
- .env.development
- src/components/Header/Nav.js
- Add `.env` for build variables
- Add `.env.development` for develop variables
based on https://facebook.github.io/create-react-app/docs/adding-custom-environment-variables
Then maybe need for int or qa.
- Add redirect to doppler login page when can't get user data
> [No ticket] Add environments variables

- package.json
- src/App.js
- src/components/Header/Nav.js
- Add login methods in app.js
- Add jwt-decoder library
> [No ticket] Add jwt initial configuration

- src/App.js
- yarn.lock
- Add doppler login cookie in local storage to mantein session.
> [No ticket] Add doppler cookie

- src/App.js
- src/components/Header/Nav.js
- remove cookie code
- add parameter redirect when redirect to doppler login
> clean cookie and redirect to login

- src/App.js
- Separate jwt token from user data to use user data method to keep alive session
> separate token from user data

- src/App.js
- Add  setinterval every 60 seconds to call getUserdata method to get user information data and keep session alive in doppler
> keep session alive

- package.json
- src/App.test.js
- src/setupTest.js
- Add react testing library to test in react
https://github.com/kentcdodds/react-testing-library
-Add one sample test to test the library
> [No ticket] Add react-testing-library

- package.json
- src/App.js
- src/App.test.js
- Add axios library to test BE api
https://github.com/axios/axios
- Add one test to test getUserData and user data.
- Add one task in package.json to debug test
> Add library to test BE

- src/App.js
- src/App.test.js
- Add local storage mocks to test happy path
- Add jwt decode mock to works decode jwt token functionality
- Change fetch request to axios token
> [No ticket] Add more functionality in testing

- src/App.js
- src/App.test.js
- src/components/Footer/Footer.js
- src/components/Footer/Footer.test.js
- src/components/Header/Header.js
- src/components/Header/HeaderNav/HeaderNav.js
- src/i18n/en.json
- src/i18n/es.json
- src/index.js
- src/utils.js
- fixed https://github.com/FromDoppler/doppler-webapp/pull/25 comments
- Remove unused .css files
- Add utils.js file with flattenMessages function to "es.json" and "en.json" format 
https://github.com/yahoo/react-intl/wiki/Upgrade-Guide#flatten-messages-object
- Remove css classes
> [No ticket] Footer branch pr corrections

- .env
- package.json
Hi @FromDoppler/doppler-webapp and team, 
I am introducing a very minor improvement in build, I introduced the issue in a bad rebase, sorry.
I have also added an empty `.env` file for common configurations. 
> Minor fixes in build

- src/App.js
Hi @FromDoppler/doppler-webapp and team, 
It will allow redirecting back to the original WebApp URL after login.
It is related to https://github.com/MakingSense/Doppler/pull/5673
Could you kindly review?
> Send complete WebApp URL to Doppler login

- src/headerData.json
Use INT environment in demo data. Nothing else.
> Use INT environment in demo data

- public/index.html
- src/components/Header/Header.js
- src/components/Header/HeaderNav/HeaderNav.js
- src/components/Header/HeaderUserMenu/HeaderUserMenu.js
- Change markup to adapt header with styles
- Use logic defined in library
> [feat] Integrate Doppler UI system header

- public/index.html
- src/components/Header/HeaderUserMenu/HeaderUserMenu.js
- src/headerData.json
- Add datahub in header and selected option
- Add last doppler ui system build to fix header navigation
> [fix] add datahub in header

- src/components/Footer/Footer.js
- Integrate doppler ui system footer
> [feat] integrate footer

- src/components/Footer/Footer.js
- Add translate footer privacy link
- Research how could translate html properties
> fix: footer privacy link

- public/index.html
- src/components/Header/Header.js
- src/components/Header/HeaderMessages/HeaderMessages.js
- src/components/Header/HeaderMessages/HeaderMessages.test.js
- src/i18n/en.json
- src/i18n/es.json
WIP
- Add new component HeaderMessages to manage the alerts in header
- TO DO add test
> feat: add header messages

- package.json
- src/App.js
- src/i18n/en.json
- src/i18n/es.json
- src/index.js
Hi team, this PR is only to move localization behavior inside our app, if you change _componentWillMount_ in the following way you will be able to verify it
```js
componentWillMount() {
this.interval = setInterval(() => {
const locale = 'es';
this.setState({
i18n: {
locale: locale,
messages: flattenMessages(messages[locale]),
},
});
}, 3000);
```
> Move i18n inside app

- public/index.html
- src/components/Header/Header.js
- src/components/Header/HeaderUserMenu/HeaderUserMenu.js
- src/components/Modal/Modal.js
- src/components/UpgradePlanForm/UpgradePlanForm.js
- src/headerData.json
- src/i18n/en.json
- src/i18n/es.json
WIP
- Add modal component to renderize modal
- Add UpgradePlanForm component to manage form
> feat: add upgrade plan modal

- .env
- package.json
- src/App.js
- src/App.test.js
- src/index.js
- src/services/doppler-legacy-client.doubles.ts
- src/services/doppler-legacy-client.ts
- src/services/session-manager.ts
- yarn.lock
Hi team (and mainly @fcoronelmakingsense),
I am moving the logic inside the new abstraction `DopplerSessionManager`. By the moment I removed JWT related logic but I will re-introduce soon in a new PR.
Also @fcoronelmakingsense, could you test it in your local environment?
> Session abstraction

- src/components/Header/Header.js
> fix: mobile menu

- src/App.js
- src/components/Header/Header.js
- src/components/Header/HeaderMessages/HeaderMessages.js
- src/components/Header/HeaderNav/HeaderNav.js
- src/components/Modal/Modal.js
> Very minor and small: Use deconstructing to simplify code

- src/services/doppler-legacy-client.ts
Sorry guys, I have broken the running app, but it should fix it making our parsing process more robust.
> fix(session): make HeaderData parsing more robust

- src/App.js
- src/App.test.js
Hi team, I am updating the App language based on HeaderData, could you review?
> Use user language

- src/App.js
- src/index.js
- src/services/pure-di.test.ts
- src/services/pure-di.ts
Hi team,
I know that it could be difficult to understand at the beginning, but I am sure that it will be very useful. 
> "Dependency injection is a tough problem. Especially in JavaScript. Lots of people didn't realize that but putting a proper dependency management is a key process of every development cycle. JavaScript ecosystem offers different tools and we as developers should pick the one that fits in our needs."
> _from [React in patterns](https://krasimir.gitbooks.io/react-in-patterns/chapter-10/#final-thoughts)_
I still need to add a _new helper component_ or _component wrapper_ to allow using it easily in any part of the system, in a way similar that we are doing with DopplerIntlProvider and FormattedMessage. I will do that in future PR to keep it small.
I am adding some comments …
> Add di container

- .gitignore
- src/services/doppler-legacy-client.test.js
- src/services/doppler-legacy-client.ts
Added get from doppler correct url, and removed hardcoded data for other enviroments that are not local. 
Also added some tests for doppler legacy client.
> Get header and user data from Doppler

- public/index.html
- src/headerData.json
> chore(header): add alert into mocked data and update library

- public/index.html
Update ui library to reflect alert header changes
> chore(uilibrary): update

- Dockerfile
- build-n-create-docker-image.sh
- build-w-docker.sh
- run-docker-container.sh
- verify-w-docker.sh
- watch-w-docker.sh
Hi @FromDoppler/doppler-webapp 
In this pr Im adding a Dockerfile to the project, to allow building it in a docker image.
This will be of use to get the project running as a service in the server.
Please have a look at it, any review is welcome. 😄
> Add Dockerfile to project

- package.json
- src/App.js
- yarn.lock
Yes, another PR.
I am introducing [React Router](https://reacttraining.com/react-router/), by the moment I am not doing more than redirect to _reports_ page when the root path is open.
> YAPR - Add routing

- src/services/datahub-client.doubles.ts
- src/services/doppler-legacy-client.doubles.ts
Hi team, this is only a thing that I consider useful when we run this project locally.
What do you think?
> Add console log to doubles

- src/components/UpgradePlanForm/UpgradePlanForm.js
- src/i18n/en.json
- src/i18n/es.json
Hi @cbernat, @fcoronelmakingsense and also @GusBaamonde and @damianmuti (because I am making some minor changes in HTML structure),
I was working on another task, and these changes come alone, I tried to split each different improvement in a different commit. 
> Improve buy form

- src/components/Header/Header.js
- src/components/Header/HeaderMessages/HeaderMessages.js
- src/headerData.json
- src/services/doppler-legacy-client.ts
- add modal when alert if type of upgrade plan
- add validation to not show alert when if to verify suscribers
- fix prettier
> fixed: to do header messages

- src/components/Header/HeaderMessages/HeaderMessages.js
- src/components/Header/HeaderMessages/HeaderMessages.test.js
> fix: header messages tests

- public/index.html
- src/components/UpgradePlanForm/UpgradePlanForm.js
**Add styles for button disabled inside modal form**
_The build 102 has updated_
> fix: button styles

- Dockerfile
- Dockerfile.INT
- Dockerfile.QA
hi @FromDoppler/doppler-webapp team, im adding dockerfiles for int and qa.
> [DBR-112] Add Dockerfiles for int and qa

- src/components/UpgradePlanForm/UpgradePlanForm.js
- src/services/doppler-legacy-client.doubles.ts
- src/services/doppler-legacy-client.ts
I have broken it:
I am fixing that in this PR:
> fix: fix data mapping after call SendUpgradePlanContactEmail/GetUpgradePlanData

- src/App.js
- src/App.test.js
- src/components/Loading.js
- src/components/UpgradePlanForm/UpgradePlanForm.js
- src/services/session-manager.ts
Hi team, 
I was working in another task related to login form, and I have detected these refactorings. 
So, in order to keep the other PR clean, I am proposing these changes to review in advance.
Could you kindly review them?
> Minor refactorings

- public/index.html
- src/App.js
- src/components/Loading/Loading.js
Add element loading page in webapp
> Loading page

- src/components/Header/HeaderUserMenu/HeaderUserMenu.js
* Updated styles and logic regarding ellipsis.
* Removed unused style specificity.
* Cleaned up styles.
> fix: issues with user menu

- src/components/Reports/Reports.js
- src/components/Reports/ReportsBox/ReportsBox.js
- Add validation when user data change and domain or period selected not change not calls BE
> fix: fetch visits when user data update

- src/components/Reports/Reports.js
- src/components/Reports/ReportsBox/ReportsBox.css
- src/components/Reports/ReportsBox/ReportsBox.js
- src/i18n/en.json
- src/i18n/es.json
- src/services/datahub-client.doubles.ts
- Add property to distinguish visits with email to without
- Add styles to show in the same row
- Fix the texts
> Reports visits withmail

- .gitignore
Very minor change in `.gitignore` file.
> chore: ignore .vscode folder completely

- public/index.html
- src/components/Reports/Reports.js
- src/components/Reports/ReportsBox/ReportsBox.css
- src/components/Reports/ReportsPageRanking/ReportsPageRanking.css
- src/components/Reports/ReportsPageRanking/ReportsPageRanking.js
- src/i18n/en.json
- src/i18n/es.json
- src/services/datahub-client.doubles.ts
- Add ReportsPageRanking component to show top pages 
- Add initial styles to show "decent" report
- Add method in dataHub client to get pages ranking
> feat: add page ranking reports

- src/components/Reports/Reports.test.js
- src/components/Reports/ReportsPageRanking/ReportsPageRanking.test.js
- Add 2 test in page ranking reports
> add: test in reports page ranking

- src/components/Reports/ReportsBox/ReportsBox.js
- src/components/Reports/ReportsPageRanking/ReportsPageRanking.js
> fix: remove wrong code related to cancel requests on unmounting components

- public/index.html
- src/components/Footer/Footer.js
the link - footer class was removed to apply generic styles
> Remove link footer

- src/components/Reports/ReportsPageRanking/ReportsPageRanking.test.js
- remove dependecies attr because dont need
> fix: reports page ranking test

- src/components/Reports/ReportsFilters/ReportsFilters.js
- src/i18n/en.json
- src/i18n/es.json
- src/services/datahub-client.doubles.ts
- Disabled dropdown all pages until implemented in datahub
> fix: disabled all pages dropdown

- public/index.html
- src/components/Login/Login.js
- src/components/form-helpers/form-helpers.js
- src/i18n/en.json
- src/i18n/es.json
- Apply final styles
- Add final html 
- Add initial form validations 
- Add texts
> add: login page FE

- package.json
- src/App.js
- Add query-string library to manage and parse query string from location
https://github.com/sindresorhus/query-string
- Change languague by url `lang` parameter
> add: change language by url parameter

- yarn.lock
Quick fix, I will merge it without reviews...
> chore(dependencies): update yarn.lock

- public/index.html
- src/App.js
- src/components/Login/Login.js
- src/i18n/DopplerIntlProvider.js
- Refactor change language method
- Add html in login
- TODO add the final styles
> add: change language in login

- src/components/Login/Login.js
- src/components/Signup/Signup.js
- Add change language in signup. replicate for login
> add: change language Signup

- src/components/Login/Login.js
- src/i18n/DopplerIntlProvider.js
Hi Team, 
Based on our conversations with @fcoronelmakingsense, I applied a refactoring in order to allow less disruptive language changes.
> Fix language on the fly

- public/index.html
- src/App.js
- src/components/ForgotPassword/ForgotPassword.js
- src/components/Login/Login.js
- src/components/Signup/Signup.js
- src/i18n/en.json
- src/i18n/es.json
- Add new page and new route
- Add texts
- TODO add final change language styles.
> add: forgot password

- public/index.html
- src/components/ForgotPassword/ForgotPassword.js
- src/components/Login/Login.js
- src/components/Signup/Signup.js
- src/components/shared/LanguageSelector/LanguageSelector.js
Created a simple component to handle language selector.
> DBR-153 Language selector component

- public/index.html
This PR is just to bump library version 👍
> Bumped library deployment version

- src/components/ForgotPassword/ForgotPassword.js
- src/components/Login/Login.js
- src/components/Signup/Signup.js
- src/validations.js
- Add new validations file with common validations
- Talk with @mvillaseco and update Email validation regex
- Apply validation in signup, login and forgot password
> add: email validations

- src/components/Reports/Reports.js
- src/components/Reports/Reports.test.js
- src/components/Reports/ReportsFilters/ReportsFilters.js
- src/i18n/en.json
- src/i18n/es.json
Hi team, 
I fixed this scenario:
I am creating a new task to improve it in the future.
> fix: add missing behavior when domain list is empty

- src/components/Reports/ReportsFilters/ReportsFilters.js
- src/components/Reports/ReportsFilters/ReportsFilters.test.js
- src/i18n/en.json
- src/i18n/es.json
It allows rendering not verified domains.
> fix: accept null verification dates

- src/components/Signup/Signup.js
- src/components/form-helpers/form-helpers.js
- src/i18n/en.json
- src/i18n/es.json
- src/validations.js
Added password validation for signup only. 
I thought to add validations in validations file when ready. 
Is not ready for merge because it's pending to add this validation in forgot password.
Not touched
Completed
Autocompleted
Failed
Could you please review? Maybe some things are not as you are used to work. @andresmoschini @fcoronelmakingsense 
--- 
https://cdn.fromdoppler.com/doppler-webapp/int-build316/#/signup
> Dplr-163: password form validation

- src/components/Signup/Signup.js
- src/components/form-helpers/form-helpers.js
Very simple change, I will merge it soon.
> fix: change class by className to avoid JSX error

- src/components/Reports/Reports.js
- src/components/Reports/ReportsFilters/ReportsFilters.js
- src/services/datahub-client.doubles.ts
Hi team, 
There was a problem using real Datahub domains data because it does not contain id field.
I fixed it, and also removed all page related logic because it is not being used.
> Fix change domain

- public/index.html
- src/components/DatahubRequired/DatahubRequired.js
- src/i18n/en.json
- src/i18n/es.json
- Add the message to users who have not enabled the on-site behavior function in Spanish and English.
- Add the message to users who have not added a domain in both languages in Spanish and English.
-
> Datahub message not available

- public/index.html
- src/components/form-helpers/form-helpers.js
- src/i18n/en.json
- src/i18n/es.json
- src/validations.test.js
- src/validations.ts
- Added letter validator
- Added tests for letter, number and empty password
- Changed digit to number as requested by mkt
> chore: add letter validation for password field and tests

- src/components/Signup/Signup.js
- src/services/doppler-legacy-client.ts
These changes allow us to send language and client time zone to the backend.
It is pending dealing with origin field, I have created a ticket for that.
Check it out! https://cdn.fromdoppler.com/doppler-webapp/int-build384/#/signup
> Send more data in signup

- src/components/Signup/Signup.js
- src/services/doppler-legacy-client.ts
Hi team, 
I think that this way of representing error results is more natural and extensible.
I have also prepared the types for other kinds of results.
> Refactor error result model

- package.json
- src/components/Login/Login.js
- src/components/Signup/Signup.js
- src/i18n/en.json
- src/i18n/es.json
- yarn.lock
In this commit, we add that a package called "React-Helmet" is a reusable React component that manages changes in the header of the document and with this, the content of the meta description is added in the login and registration page.
> Add dynamic meta description in page Signup and Login

- public/index.html
- src/components/ForgotPassword/ForgotPassword.js
- src/components/Login/Login.js
- src/components/Signup/Signup.js
- src/i18n/en.json
- src/i18n/es.json
- Create the necessary keys for each entry in ES / EN (Login signup forgot)
- Add the necessary content for each screen ES / EN (Login signup forgot)
- Add the necessary classes to show the backgrounds (Login signup forgot)
- Update the build version
> feat: updating Backgrounds and contents in sign-up, login and forgot

- public/index.html
- src/components/ForgotPassword/ForgotPassword.js
- src/components/Login/Login.js
- src/components/Signup/Signup.js
- src/components/Signup/SignupConfirmation.js
- src/i18n/en.json
- src/i18n/es.json
- link footer on the page thanks signup and update version build
> Link footer privacy policy

- public/index.html
- src/components/Signup/SignupConfirmation.js
Fix background in signup confirmation page
> Fix background in signup confirmation page

- src/components/Login/Login.js
- src/services/doppler-legacy-client.doubles.ts
- src/services/doppler-legacy-client.ts
- src/services/session-manager.ts
Hi team,
Well, I have reduced the scope of this PR.
By the moment, I am calling _DopplerLegacyClient_, and I am ready to get expected errors, but I am not dealing with them yet (See TODO notes).
I am also sending captcha to backend and restarting the session.
Basically, the pending work is dealing with expected errors. 
> DBR-198 - Login client

- public/index.html
- src/components/Header/HeaderUserMenu/HeaderUserMenu.js
Utilizaremos class name en lugar de id para expandir el menu de usuario y poder reutilizar esa lógica.
PR relacionado: https://github.com/FromDoppler/Doppler-UI-System/pull/93
> feat: open menu user

- src/components/Signup/Signup.js
Just that. 
Good catch @lucianaDilizio !
> fix: restore email required validation in signup

- src/components/Login/Login.js
- src/components/Signup/SignupConfirmation.js
- src/components/form-helpers/captcha-utils.tsx
- src/services/doppler-legacy-client.ts
Hi team,
I fixed the URL of _SendRegistrationEmail_ backend action, and I have also applied some minor changes:
* Log errors if something goes wrong with SendRegistrationEmail.
* Add type=button for SendRegistrationEmail button (in order to allow reusing it inside a form)
* Include reCaptcha object ref in _useCaptcha_ result (in order to allow extension and better debugging experience)
* Include captcha in login
> DBR-210 - Resend signup email

- src/components/Reports/ReportsFilters/ReportsFilters.js
- src/i18n/en.json
- src/i18n/es.json
Changed time filter options in reports. 
Issue: DBR-184
> chore: change report time filter values

- public/index.html
- src/components/Header/Header.js
- src/components/Header/HeaderNav/HeaderNav.js
- src/headerData.json
- src/services/doppler-legacy-client.ts
Quick fix on the main navigation. Needs refactor for further implementations.
> Fixed issues with main navigation

- src/validations.ts
> fix: not allow dot before @

- src/components/Login/Login.js
- src/i18n/en.json
- src/i18n/es.json
- src/services/doppler-legacy-client.doubles.ts
- src/services/doppler-legacy-client.ts
Hi team, specially @carodipietro and @santiagopaolucci,
This is the error shown when the account is blocked by payment reasons, it is pending to improve the content, we could use Doppler current mesages or you can choose new ones.
Could you kindly review it?
> DBR-222 - Login error "blocked by payment"

- src/components/Signup/Signup.js
- src/i18n/en.json
- src/i18n/es.json
Add error text for checkbox validation in signup page
> Add error text for checkbox validation

- src/components/Login/Login.js
- src/components/Login/LoginErrorAccountNotValidated.js
- src/services/doppler-legacy-client.doubles.ts
- src/services/doppler-legacy-client.ts
Hi team, and specially @carodipietro and @santiagopaolucci,
This is the error when the user did not finish the registration process because he did not validate the email.
We are using captcha in all actions (login and resend email), the message disappears when the user does something in the login form fields and when the user clicks in the action, the email is resent.
Again, in this case, you can propose quick improvements in the content, or better enhancements could be done in future PR.
> DBR-213 - Login error "Email not validated"

- src/services/doppler-legacy-client.doubles.ts
- src/services/doppler-legacy-client.ts
This is the service method to activate the site tracking feature
> DBR-220-service

- src/components/Login/Login.js
- src/components/Login/LoginErrorCancelatedAccount.js
- src/i18n/en.json
- src/i18n/es.json
- src/services/doppler-legacy-client.doubles.ts
- src/services/doppler-legacy-client.ts
Catch error in login when the account is canceled:
> feat: deal with account canceled error

- src/i18n/en.json
- src/i18n/es.json
feat(content): update content in login and forgotpassword
> DBR-229 Update content in login and forgotpassword

- src/components/ForgotPassword/ForgotPassword.css
- src/components/ForgotPassword/ForgotPassword.js
- src/i18n/en.json
- src/i18n/es.json
- src/services/doppler-legacy-client.doubles.ts
- src/services/doppler-legacy-client.ts
Hi team, 
I was working on forgot password but I got stuck with the UI, so @GusBaamonde will help me on this.
This is the current status:
> DBR-158 - Forgot password

- src/i18n/en.json
- src/i18n/es.json
- Any paid account can enable the trial (ES/EN)
> feat: content in trial not active on account pay

- public/index.html
- src/components/Reports/ReportsBox/ReportsBox.js
- src/components/Reports/ReportsFilters/ReportsFilters.js
- src/components/Reports/ReportsPageRanking/ReportsPageRanking.js
- src/i18n/en.json
- src/i18n/es.json
related to https://github.com/FromDoppler/Doppler-UI-System/pull/100
> Content of the report page

- public/index.html
- src/components/ForgotPassword/ForgotPassword.css
- src/components/ForgotPassword/ForgotPassword.js
- src/i18n/en.json
- src/i18n/es.json
> feat: show link to return to login after forgot password

- src/components/ForgotPassword/ForgotPassword.js
- src/components/Reports/Reports.js
Hi team,
I am using Helmet to update the title in _reports_ and _forgot-password_ pages.
Could you take a look?
> DBR-203 - Helmet title

- src/App.js
Hi team, 
In this case, I am taking advantage of Helmet to update lang metadata when the user changes his language.
> DBR-204 - Update lang metadata based on selected language

- src/components/ForgotPassword/ForgotPassword.js
- src/components/Login/Login.js
- src/components/Signup/Signup.js
- src/components/form-helpers/form-helpers.js
> Show button-round class only for public pages

- src/i18n/en.js
- src/i18n/es.js
> feat: add content forgot password

- src/i18n/en.js
- src/i18n/es.js
> feat: add content login

- src/components/ForgotPassword/ForgotPassword.js
- src/i18n/en.js
- src/i18n/es.js
> fix: fix login button content

- src/components/Signup/Signup.js
- src/i18n/en.js
- src/i18n/es.js
- src/services/doppler-legacy-client.doubles.ts
- src/services/doppler-legacy-client.ts
Catch denied register error:
To test it: https://cdn.fromdoppler.com/doppler-webapp/int-build648/#/signup
> feat: deal with register denied error

- src/components/SiteTrackingRequired/SiteTrackingRequired.js
- src/i18n/en.js
- src/i18n/es.js
> feat: add button domains

- src/i18n/en.js
- src/i18n/es.js
Hi team, I am applying the change that we have talked with @carodipietro, @santiagopaolucci and @ mfantinims.
> fix: use "last visit registered" in place of "last verification"

- public/index.html
- src/components/Header/Header.js
- src/components/Header/HeaderNav/HeaderNav.js
Updated logic to emulate Doppler App menu. Fixed issues with classes and elements being generated based on a statement that was always returning true.
> fix: issues with main menu

- src/components/ForgotPassword/ForgotPassword.js
- src/components/Login/Login.js
- src/components/Signup/Signup.js
> fix: use className in place of class

- src/components/ForgotPassword/ForgotPassword.js
- src/components/Login/Login.js
- src/components/RedirectWithQuery.js
- Change links in forgot password and login to pass the email in state
- Change initial values in the email field to put the email if has in state.
> add: keep email in forgot password

- public/zoho-chat.js
> setup of chat in spanish by default

- public/index.html
- src/components/SiteTrackingRequired/SiteTrackingRequired.js
related to https://github.com/FromDoppler/Doppler-UI-System/pull/108
https://cdn.fromdoppler.com/doppler-webapp/int-build701/#/login
> homogeneous visual coherence for messages

- src/i18n/en.js
- src/i18n/es.js
Hi team, 
I have applied some minor changes in language files, removing unused entries and having a constant for Advanced Reports URL.
I have also found that the content of "activate trial" page in Spanish laked of the help link, so, I have added.
> DBR-260 - Clean language files

- public/index.html
- src/index.js
Hi team, and mainly @leoslopez,
I am including the reference to DataHub to start dog-fooding it.
Could you review my changes?
> DBR-305 - DataHub dog fooding

- public/index.html
Changed positioning of the icon. Updated border definition and added display property to prevent positioning differences between browsers.
> fix: issues with icon positioning

- src/components/Header/HeaderUserMenu/HeaderUserMenu.js
- Fix when user has a prepaid account and want to buy credits redirect to buy credits page and not show popup
> fix: header prepaid plan buy credits

- src/services/doppler-legacy-client.ts
- Remove buy credits from header menu when client is client manager
> fix: header client manager

- src/components/Signup/Signup.test.js
- src/components/UpgradePlanForm/UpgradePlanForm.js
- src/components/form-helpers/form-helpers.js
Hi team, 
As we have talked, I changed the behavior of the form in order to do not show validation errors before the first form submission.
--- 
No, no, come on @matiasbeckerle, this time I added tests!
> DBR-171 - Do not show validation errors before first submit

- public/index.html
- Update UI system library to fix webapp spinners
> fix: refactor loading spinners

- build-n-release-w-docker.sh
- package.json
- yarn.lock
Hi team,
This is an end-user application, so, maybe semantic versioning is not the best option, but maybe it is useful because we need number versions, and it is automatic and gives us some kind of information.
Following (in part) [this article](https://medium.com/@u_glow/making-sense-of-semantic-versioning-for-end-user-software-applications-a3049d97478b) we can apply these rules:
* `MAJOR` version  (`BREAKING CHANGES`): when we make changes incompatible with current Doppler Backend, DataHub ApiSec, or other backend APIs. Also when we remove or change drastically some end-user features. And also when our changes affect the installation-requirements or infrastructure.
* `MINOR` version (`feat`): when we add functionality in a backwards-compatible manner (e.g. passing additional data to an …
> DBR-313 - Semantic Release

- src/i18n/DopplerIntlProvider.js
- src/index.js
Hi team, 
I received a message from support area, about a user that cannot use our signup page. 
I am pretty sure that his browser has a different language configured than English or Spanish.
So, in my opinion, it should fix the issue.
Could you review the changes?
I promise to add a test for this issue today, but I want to merge it soon in order to deploy the fix to production ASAP.
> DBR-321 - Fix issue with browser language

- src/App.js
- src/App.test.js
- src/i18n/DopplerIntlProvider.js
- src/i18n/DopplerIntlProvider.test.js
- src/i18n/utils.js
- src/index.js
Hi team,
As I promised in #221, I am adding tests and some minor refactoring related to language behavior.
Based on a @fgchaio comment, I am also changing the default language for Spanish.
> DBR-321 - Fix issue with browser language (tests and refactoring)

- build-n-release-w-docker.sh
I knew that something was going wrong...
> chore: fix semantic release script

- src/components/Signup/Signup.test.js
- src/components/form-helpers/form-helpers.js
> feat: sort country names

- public/index.html
- src/components/ForgotPassword/ForgotPassword.js
- src/components/form-helpers/form-helpers.js
**Implemented changes in icon sizes**
> feat: modification of messages and validations

- public/index.html
- Update Doppler ui system library version
> fix: spinner in reports ranking box

- src/services/doppler-legacy-client.ts
- Change EnableSiteTracking method from get to post
> fix: change site tracking enable method to post

- public/index.html
- src/App.test.js
- src/components/Signup/Signup.test.js
- src/components/shared/LanguageSelector/LanguageSelector.js
- yarn.lock
Since we needed to improve keyboard navigation on login/reset-password pages, I've refactored the language selector to support keyboard events.
> feat: Refactored language selector

- public/index.html
- src/components/Header/Header.js
- src/headerData.json
- src/services/doppler-legacy-client.ts
**The client manager logo entered by the user or the data entered in the company name field is displayed**
**Before and after**
**Small resolution**
**Sample Logo and text Client Manager**
> Client Manager Logo and placeholder

- public/index.html
- src/components/Login/Login.js
- src/components/form-helpers/form-helpers.js
> Add mesagge warning

- src/components/form-helpers/captcha-utils.tsx
- yarn.lock
It seems that I had an error merging changes in yarn.lock file, it fixes the issue.
> fix: regenerate yarn.lock

- public/index.html
Update build version with:
http://jira.makingsense.com/browse/DBR-335
http://jira.makingsense.com/browse/DBR-339
> feat: update build version

- src/components/ForgotPassword/ForgotPassword.js
- src/components/Login/Login.js
- src/components/Signup/Signup.js
- yarn.lock
- Apply new structure from doppler ui library in webapp public pages
> fix: apply new structure styles in public pages

- src/components/Integrations/Shopify/Shopify.js
In order to have useEffect function calling itself several times, and have the correct state of view. 
Related to https://github.com/FromDoppler/doppler-webapp/pull/235#discussion_r296875387
> fix(shopify): add al possible path in getData function

- public/index.html
- src/components/Login/Login.js
- src/components/Signup/Signup.js
In this pull request, I worked to eliminate classes that are no longer useful, this is because I am working on cleaning the UI library so that the code is as clean and neat as possible. In this case, only the call to the class "link - title" was deleted
> Clear class that no use in the UI library

- src/components/Integrations/Shopify/Shopify.js
- src/components/Integrations/Shopify/Shopify.test.js
- src/services/shopify-client.doubles.ts
Add visual styles from ui library for blocks only.
> Shopify: add visual changes from ui library

- public/index.html
- src/components/Header/Header.js
- src/components/Header/Notifications.js
- src/headerData.json
- src/i18n/en.js
- src/i18n/es.js
- src/services/doppler-legacy-client.doubles.ts
- src/services/doppler-legacy-client.ts
> feat: add notifications

- src/components/Reports/ReportsPageRanking/ReportsPageRanking.js
- src/i18n/en.js
- src/i18n/es.js
- src/services/datahub-client.doubles.ts
- src/services/datahub-client.ts
- Change datahub request to obtain unique visits. related with [CDH-245](http://jira.makingsense.com/browse/CDH-245)
- Remove total visits ranking because now dont use now
> add: unique visits in reports

- src/index.js
Add data hub track for current page.
> feat: add datahub track

- build-n-publish-release-w-docker.sh
It will be useful to mitigate our issue with Docker login.
> chore: fix docker login

- public/index.html
- src/components/Signup/SignupConfirmation.js
> fix: add class dp-button and update build version

- src/components/Integrations/Shopify/Shopify.js
- src/components/Integrations/Shopify/Shopify.test.js
- src/i18n/en.js
- src/i18n/es.js
- Added multilanguage support
- Fixed tests in consequence
On general error added button to go back
> feat(shopify): add multilanguage support

- src/components/ForgotPassword/ForgotPassword.js
- src/components/Login/Login.js
- src/components/Signup/Signup.js
- src/components/form-helpers/form-helpers.js
- src/i18n/en.js
- src/i18n/es.js
WIP
- Add reset password messages in login page.
- Need apply styles in Doppler UI library maybe for better view
> fix: forgot password error messages in login page

- src/components/ForgotPassword/ForgotPassword.js
- src/components/Login/Login.js
- src/components/Signup/Signup.js
> feat: enable promotions for doppler site

- package-lock.json
- package.json
- src/components/Integrations/Shopify/Shopify.css
- src/components/Integrations/Shopify/Shopify.js
- yarn.lock
- Add styled components
- Use in shopify image logo
> Add styled components and apply in Shopify Logo

- src/services/datahub-client.doubles.ts
- src/services/datahub-client.test.ts
- src/services/datahub-client.ts
- Add service method in datahub client to get traffic sources
- Add service method in datahutb doubles to local work
> feat: add datahub methods to get traffic sources

- src/components/Reports/Reports.js
- src/components/Reports/Reports.test.js
- src/components/Reports/ReportsTrafficSources/ReportsTrafficSources.js
- src/components/Reports/ReportsTrafficSources/ReportsTrafficSources.test.js
- src/i18n/en.js
- src/i18n/es.js
- src/services/datahub-client.doubles.ts
- src/services/datahub-client.test.ts
- src/services/datahub-client.ts
- Add Traffic reports traffic source component without style
- Fix reports test
Pending:
- Disabled for not showing now
> Reports traffic source component

- src/components/Integrations/Shopify/Shopify.js
- src/components/Integrations/Shopify/Shopify.test.js
- src/i18n/en.js
- src/i18n/es.js
- src/services/shopify-client.doubles.ts
- src/services/shopify-client.ts
- Fix token parameter in call.
- Code review fixes
- Add link redirects (back connect, admin apps)
- Add breadcrumb with styled components for now
- Add mapping and format for date
- Add mapping for list name
link --> http://cdn.fromdoppler.com/doppler-webapp/build1090/#/integrations/shopify
> fix: fix authorization token for shopify client

- public/index.html
- src/components/Reports/ReportsBox/ReportsBox.js
- src/components/Reports/ReportsPageRanking/ReportsPageRanking.js
- Change reports components styles for reuses purposes in other reports components or boxes
> refactor(reports): styles to can reuse in all reports boxes

- src/components/Integrations/Shopify/Shopify.js
- src/components/Integrations/Shopify/Shopify.test.js
- src/i18n/en.js
- src/i18n/es.js
- Add table with list data:
- Add synchonizing state
- Updated UI library version
> feat(shopify): add table with list data and state

- public/index.html
- src/components/Reports/Reports.js
- src/components/Reports/ReportsTrafficSources/ReportsTrafficSources.js
- src/components/Reports/ReportsTrafficSources/ReportsTrafficSources.styles.js
- Add styles components to style the specific css for the component
- Separate styles components in other file
TODO: Apply styles in DopplerUI library
> feat(traffic sources): add styles to component

- src/components/Reports/ReportsTrafficSources/ReportsTrafficSources.js
- src/components/Reports/ReportsTrafficSources/ReportsTrafficSources.styles.js
- Remove green separator for now until have more data to show
> fix(ReportsTrafficSources): remove green separator for now 

- public/index.html
- src/components/Integrations/Shopify/Shopify.js
Add cdn breadcrumb style
Remove style-component from breadcrumb
> feat: add breadcrumb style

- src/i18n/en.js
- src/i18n/es.js
As talked with @mvillaseco some features are yet to be implemented. So I'm removing the text reference from Shopify panel.
@mfantinims
> fix(shopify): remove not implemented feature text

- public/index.html
- src/components/Integrations/Shopify/Shopify.js
> feat: Add styles for shopify error messages

- src/App.js
- src/components/Signup/Signup.js
- src/components/Signup/SignupConfirmation.js
- Add redirect to signup when access for url and signup isnt completed
> feat(SignupConfirmation): add route for datahub tracking

- public/index.html
- src/components/Integrations/Shopify/Shopify.js
related to: https://github.com/FromDoppler/Doppler-UI-System/pull/155
Let me know what you think: @mvillaseco @santiagopaolucci @andresmoschini
> fix: footer position

- public/index.html
- src/App.test.js
- src/components/Login/Login.js
- Add google adwords when come from email confirmation and have in url the parameter `activationInProgress%20=%20true`
- Reference link https://bernardodiasdacruz.com/2018/04/10/integrate-google-analytics-with-react-router-v4/
> feat(google adwords): add in login confirmation email

- public/index.html
related to: https://github.com/FromDoppler/Doppler-UI-System/pull/156
> fix: fix for footer in the report pages

- src/components/Integrations/Shopify/Shopify.js
@fcoronelmakingsense the issue you've mentioned earlier fixed here.
> chore(shopify): refactor use one map to fix test warning

- src/services/datahub-client.doubles.ts
- src/services/datahub-client.test.ts
- src/services/datahub-client.ts
- Add method in datahub client
- Add method in datahub client double to work in dev
- Add unit test
> feat(reports): add daily visits services

- src/components/Reports/ReportsTrafficSources/ReportsTrafficSources.js
- src/components/Reports/ReportsTrafficSources/ReportsTrafficSources.test.js
- src/i18n/en.js
- src/i18n/es.js
- src/services/datahub-client.doubles.ts
- fix test
- add styles when datahub fails and show error
> fix(ReportsTrafficSources): traffic sources names translate

- src/components/Reports/Reports.test.js
- src/components/Reports/ReportsPageRanking/ReportsPageRanking.js
- src/components/Reports/ReportsPageRanking/ReportsPageRanking.test.js
- src/services/datahub-client.doubles.ts
- src/services/datahub-client.ts
- add withEmail field for visitors with email
- fix test
- change service method to manage errors
> refactor(ReportsPageRanking): change service method

- src/i18n/en.js
- src/i18n/es.js
> fix(ReportsDailyVisits): change title of graphic

- src/components/Reports/ReportsPageRanking/ReportsPageRanking.js
- src/components/Reports/ReportsPageRanking/ReportsPageRanking.styles.js
- src/components/shared/Colors.js
- src/i18n/en.js
- src/i18n/es.js
- refactor component to add visits with and without email
- refactor and add styles components
- TODO test and check experimental feature
https://github.com/FromDoppler/doppler-webapp/pull/399
> feat(ReportsPageRanking): add visits with and without email

- src/components/Integrations/Shopify/Shopify.js
- src/components/Integrations/Shopify/Shopify.styles.js
To prevent unneccesary re render of component, move outside main component.
> chore(shopify): move styled component outside main component

- src/components/Reports/ReportsDailyVisits/ReportsDailyVisits.js
- change date forma to use month and day like in the example
- change configuration to show all dates when select 3 weeks for example
> fix(ReportsDailyVisits): date format and show all dates

- src/components/ForgotPassword/ForgotPassword.js
- src/components/Integrations/Shopify/Shopify.js
- src/components/Login/Login.js
- src/components/Login/LoginErrorAccountNotValidated.js
- src/components/PublicRouteWithLegacyFallback.js
- src/components/Reports/ReportsTrafficSources/ReportsTrafficSources.js
- src/components/Signup/Signup.js
- src/components/Signup/SignupConfirmation.js
- src/components/UpgradePlanForm/UpgradePlanForm.js
- src/components/form-helpers/form-helpers.js
- src/components/shared/LanguageSelector/LanguageSelector.js
- src/components/shared/Promotions/Promotions.js
- src/i18n/FormattedMessageMarkdown.js
- Change injectintl for useIntl() hook the other is obsolete and don't need anymore
> refactor(react-intl): update to use hook instead of injectintl

- src/components/Reports/ReportsDailyVisits/ReportsDailyVisits.js
> fix(ReportsDailyVisits): remove x axis for more clear show

- src/services/datahub-client.doubles.ts
- src/services/datahub-client.test.ts
- src/services/datahub-client.ts
- Add withEmail field for traffic sources method to prepare for full detail information with and without email
> refactor(datahub-client): add with email field traffic sources reports

- src/i18n/en.js
- src/i18n/es.js
This reverts commit 88d73815ab2419a5daefd6b6459a2b4eb113cff3.
Pending to be merged when all features are in place.
> Revert "fix(shopify): remove not implemented feature text"

- package.json
- src/utils.ts
- yarn.lock
Hi team, now we have types in out _utils_ package :)
> refactor(utils): convert utils.ts to typescript

- src/components/Reports/ReportsTrafficSources/ReportsTrafficSources.js
- src/components/Reports/ReportsTrafficSources/ReportsTrafficSources.styles.js
- src/i18n/en.js
- src/i18n/es.js
- change styled components names accord with discuss previously
> refactor(ReportsTrafficSources): styled components names

- src/components/Reports/Reports.test.js
- src/components/Reports/ReportsBox/ReportsBox.js
- src/components/Reports/ReportsDailyVisits/ReportsDailyVisits.js
- src/services/datahub-client.doubles.ts
- src/services/datahub-client.test.ts
- src/services/datahub-client.ts
- Change names to use this method for days and for hours too
> refactor(datahub-client): change daily visits to accept hours too

- src/components/Reports/ReportsPageRanking/ReportsPageRanking.styles.js
- src/i18n/en.js
- src/i18n/es.js
- Adjustment of margins and text correction in most visited pages
- Add the variables of fonts and spaces
> fix(most visited pages)

- public/zoho-chat.js
Related to https://github.com/MakingSense/DopplerWebsite/pull/346
> Zoho allow subdomain chat

- src/components/Reports/ReportsDailyVisits/ReportsDailyVisits.js
This fix stands for https://github.com/FromDoppler/doppler-webapp/commit/41663a22b6f9e721ef19d4cacaf4b925a085a688#commitcomment-35151207
> fix(dailyVisitReport): fix condition to take a more robust approach

- src/components/Reports/ReportsPageRanking/ReportsPageRanking.js
- src/components/Reports/ReportsTrafficSources/ReportsTrafficSources.js
- src/components/styles/messages.js
> fix: adjust margins error messages in traffic source

- src/services/datahub-client.ts
For page ranking data, add protocol if it is comming from datahub to complete full url.
> feat(datahub): add protocol if enabled

- src/components/Integrations/Shopify/Shopify.js
- src/components/Loading/Loading.js
- src/components/PrivateRoute.js
- src/components/Reports/Reports.js
- src/components/Reports/ReportsDailyVisits/ReportsDailyVisits.js
- src/components/Reports/ReportsPageRanking/ReportsPageRanking.js
- src/components/Reports/ReportsTrafficSources/ReportsTrafficSources.js
- src/components/UpgradePlanForm/UpgradePlanForm.js
- src/components/shared/Promotions/Promotions.js
- Remove export default and change for the common export which is how we use in other places
> refactor(Loading): change the mode has exported

- src/components/Reports/ReportsFilters/ReportsFilters.js
- src/components/Reports/ReportsFilters/ReportsFilters.styles.js
- src/components/Reports/ReportsFilters/ReportsFilters.test.js
- src/i18n/en.js
- src/i18n/es.js
- Add link to sitetracking when domain is non verified
- Fix styles to can show propertly with `FormattedMessageMarkdown`
> fix(ReportsFilters): add link when domain is non verified

- public/index.html
- src/components/Reports/Reports.js
- src/components/Reports/ReportsHoursVisits/ReportsHoursVisits.js
- src/components/Reports/ReportsHoursVisits/ReportsHoursVisits.styles.js
- src/components/Reports/ReportsHoursVisits/ReportsHoursVisits.test.js
- src/components/Reports/ReportsPageRanking/ReportsPageRanking.styles.js
- src/components/Reports/ReportsTrafficSources/ReportsTrafficSources.styles.js
- src/components/shared/C3Chart/C3Chart.styles.js
- src/components/styles/colors.js
- src/i18n/en.js
- src/i18n/es.js
- src/services/datahub-client.doubles.ts
- Add new component to show visits for weekdays and hours
- Add fake data in double
TODO: styles, tests, use with real data
> feat(ReportsHoursVisits): add component and show data

- public/index.html
- src/components/Reports/ReportsHoursVisits/ReportsHoursVisits.js
- src/components/Reports/ReportsHoursVisits/ReportsHoursVisits.styles.js
- src/components/Reports/ReportsHoursVisits/ReportsHoursVisits.test.js
- src/components/shared/C3Chart/C3Chart.styles.js
- src/i18n/en.js
- src/i18n/es.js
- src/services/datahub-client.ts
- Add detail with and without email 
- Add test to test functionality
- Refactor tests
> Reports visits weekdays withemail

- src/components/Reports/ReportsDailyVisits/ReportsDailyVisits.js
- src/components/Reports/ReportsDailyVisits/ReportsDailyVisits.styles.js
- src/components/Reports/ReportsHoursVisits/ReportsHoursVisits.js
- src/components/Reports/ReportsHoursVisits/ReportsHoursVisits.styles.js
- src/components/Reports/ReportsPageRanking/ReportsPageRanking.js
- src/components/Reports/ReportsPageRanking/ReportsPageRanking.styles.js
- src/components/Reports/ReportsTrafficSources/ReportsTrafficSources.js
- src/components/Reports/ReportsTrafficSources/ReportsTrafficSources.styles.js
- src/i18n/en.js
- src/i18n/es.js
- Add error messages with finish styles in daily visits and weeks and hours visits
- Add empty messages in reports traffic source and page ranking
> feat(Reports): add empty messages in boxes

- src/components/Reports/ReportsTrafficSources/ReportsTrafficSources.js
- Show empty data when don't have values
> fix(ReportsTrafficSources): when don't have quantity

- src/components/Reports/ReportsTrafficSources/ReportsTrafficSources.styles.js
> fix: remove box-shadow from traffic sources

- src/components/Reports/ReportsDailyVisits/ReportsDailyVisits.js
> fix(ReportsDailyVisits): fix width style in the graphic

- public/index.html
- src/components/Reports/ReportsHoursVisits/ReportsHoursVisits.styles.js
- Hover effect adjustment on each circle
> fix: adjust width of week chart and hours

- src/utils.test.js
- src/utils.ts
Fix: https://cdn.fromdoppler.com/doppler-webapp/build1717/#/reports
> fix(reports): return full date with days included

- src/components/Reports/ReportsPageRanking/ReportsPageRanking.js
- src/components/Reports/ReportsPageRanking/ReportsPageRanking.styles.js
- src/components/Reports/ReportsPageRanking/ReportsPageRanking.test.js
- src/i18n/en.js
- src/i18n/es.js
- src/services/datahub-client.doubles.ts
- Change useEffect method to pass to the datahub client the pageSize and pageNumber. For local testing purpose i put the pageSize in 2 but maybe need check with Martin. I think 5 it's a good number.
- Only show more results button when have more items to show.
- Pending: tests, styles, interaction
> feat(ReportsPageRanking): add pagination to the ranking

- src/components/Reports/ReportsHoursVisits/ReportsHoursVisits.js
- src/i18n/en.js
- src/i18n/es.js
> feat(ReportsHoursVisits): add dynamic ranges values

- Dockerfile.RELEASES
Move arg closer to copy command to make it work.
> fix(deploy): add enviroment to use in copy

- build-n-publish-release-w-docker.sh
Hi Team, 
I am premiering our new DockerHub organization `fromdoppler`.
By the moment, the idea is publishing to the old and the new registries.
I have used `fix` in order to force a release.
Could you review it? 
CC: @elsupergomez
> fix: publish docker images to new fromdoppler organization

- src/components/Integrations/Shopify/Shopify.js
- src/components/Reports/Reports.js
- src/components/Reports/Reports.test.js
- src/components/Reports/ReportsBox/ReportsBox.js
- src/components/Reports/ReportsDailyVisits/ReportsDailyVisits.js
- src/components/Reports/ReportsFilters/ReportsFilters.js
- src/components/Reports/ReportsHoursVisits/ReportsHoursVisits.js
- src/components/Reports/ReportsHoursVisits/ReportsHoursVisits.test.js
- src/components/Reports/ReportsPageRanking/ReportsPageRanking.js
- src/components/Reports/ReportsTrafficSources/ReportsTrafficSources.js
- src/i18n/en.js
- src/i18n/es.js
- src/services/datahub-client.doubles.ts
- src/services/datahub-client.test.ts
- src/services/datahub-client.ts
- change all utc dates to local time
- change startDate to pass datahub date with 0 minutes and 0 seconds
> fix(Reports): change dates to local time

- public/index.html
- src/components/Reports/Reports.js
- src/components/Reports/ReportsBox/ReportsBox.js
- src/components/Reports/ReportsFilters/ReportsFilters.js
Related UI Library PR: https://github.com/FromDoppler/Doppler-UI-System/pull/199
> feat(grid-system): Add the grid-system to the reports layout

- src/components/Reports/ReportsTrafficSources/ReportsTrafficSources.js
- src/components/Reports/ReportsTrafficSources/ReportsTrafficSources.styles.js
> feat: add grid system in traffic sources

- src/components/Reports/ReportsBox/ReportsBox.js
- src/components/shared/DateRangeText/DateRangeText.js
- create component in the report box component.
> feat(ReportsBox): add component to get date range text

- src/components/UpgradePlanForm/UpgradePlanForm.js
- src/components/UpgradePlanForm/UpgradePlanForm.test.js
For monthly subscriber or demo enviroment, click on buy and the popup did not show.
- Removed hook for intl
- Add test to validate correct render
> Dw 101 upgradepopup

- src/components/Reports/Reports.js
> fix(unique page views): removed unnecessary classes

- src/components/UpgradePlanForm/UpgradePlanForm.js
Components:
- UpgradePlanForm
Issue: DW-93
> refactor: change class components to functional components

- Jenkinsfile
> fix(build): fix wrong condition selecting stages for tags

- src/components/Reports/Reports.js
- src/components/Reports/Reports.test.js
- src/components/Reports/ReportsFilters/ReportsFilters.js
- src/components/Reports/ReportsFilters/ReportsFilters.test.js
- src/components/styles/messages.js
- src/i18n/en.js
- src/i18n/es.js
- src/services/datahub-client.doubles.ts
- Remove message under of dropdown and put before reports boxes with other design
- Add test to check this state
> feat(Reports): change message domain non verified

- public/index.html
- src/components/Reports/ReportsHoursVisits/ReportsHoursVisits.js
- src/components/Reports/ReportsHoursVisits/ReportsHoursVisits.styles.js
> Add grid system in day week hours

- src/components/Reports/ReportsPageRanking/ReportsPageRanking.js
- src/components/Reports/ReportsPageRanking/ReportsPageRanking.test.js
- src/services/datahub-client.doubles.ts
- src/services/datahub-client.test.ts
- src/services/datahub-client.ts
- Show more pages when have more pages, before this pr only show one time.
> fix(ReportsPageRanking): show more pages fixed

- src/components/Reports/Reports.js
- src/components/Reports/ReportsBox/ReportsBox.js
Refactor ReportBox from class component to functional component with hooks.
Issue: DW-93
> refactor(reportBox): translate to functional component with hooks

- src/components/Signup/Signup.test.js
- Change tests to async test and add wait for change because in promotions the state is modified and need to wait.
> fix(Signup): act warning tests

- src/components/shared/Promotions/Promotions.js
- src/components/shared/Promotions/Promotions.test.js
- Remove disabled content because it's old and don't use anymore
- Refactor state like other components we have
> refactor(Promotion):  remove unused functionality

- src/components/Reports/ReportsPageRanking/ReportsPageRanking.js
- src/components/Reports/ReportsPageRanking/ReportsPageRanking.styles.js
> fix: add grid system in pages ranking

- src/components/Reports/Reports.test.js
> fix(Reports): act warning in the test

- package.json
- yarn.lock
Revert formik update to prevent signup telephone bug.
> fix(signup): revert formik update to avoid telephone error

- Dockerfile
- Dockerfile.LOCAL
- Dockerfile.RELEASES
- Dockerfile.swarm
> DW-114:chore: set default nginx version alpine

- src/components/Reports/ReportsDailyVisits/ReportsDailyVisits.js
- src/components/Reports/ReportsDailyVisits/ReportsDailyVisits.styles.js
- src/components/shared/C3Chart/C3Chart.styles.js
- add grid system in unique page views
- Add the error in dp-box-shadow
> fix: add grid system in unique page views

- Jenkinsfile
- Add log for author in console (temporal for checking)
- Set regexp for author name in change request
> chore: add regex and log author data

- Jenkinsfile
> chore(jenkinsfile): add more details to regex dependabot

- package.json
- src/components/form-helpers/form-helpers.js
- disabled eslint line to remove handleChange dependency
- fix warning in tests
> fix(Formik): update version to 2.0.3

- public/index.html
- src/components/Reports/Reports.js
- src/components/Reports/ReportsBox/ReportsBox.js
- src/components/Reports/ReportsDailyVisits/ReportsDailyVisits.js
- src/components/Reports/ReportsHoursVisits/ReportsHoursVisits.js
- src/components/Reports/ReportsPageRanking/ReportsPageRanking.js
- src/components/Reports/ReportsTrafficSources/ReportsTrafficSources.js
Related to: https://github.com/FromDoppler/Doppler-UI-System/pull/213
> fix: in error messages and preload boxes

- src/components/form-helpers/form-helpers.js
- Remove listener outside effect to avoid handleChange dependency.
- Add state for set one time the listener
> fix(Formik): remove handle change for effect

- src/components/Header/HeaderMessages/HeaderMessages.js
- src/components/Header/HeaderMessages/HeaderMessages.test.js
- src/headerData-alerts.json
- Add one more header data json to test the alerts.
> refactor(HeaderMessages): update to functional component

- src/App.js
- src/components/Reports/SubscriberHistory/SubscriberHistory.js
- src/components/Reports/SubscriberHistory/SubscriberHistory.test.js
- src/i18n/en.js
- src/i18n/es.js
> feat: add component Subscriber History

- package.json
- yarn.lock
- Update formik to 2.0.6 to fix the checkbox
> fix(Formik): checkbox in signup

- public/index.html
- src/App.test.js
- src/components/Footer/Footer.js
> fix: add grid system in footer

- public/index.html
- src/components/Header/HeaderUserMenu/HeaderUserMenu.js
Related to: https://github.com/FromDoppler/Doppler-UI-System/pull/217
**No keyboard navigation**
**With keyboard navigation**
> fix: outline function enabled for keyboard navigation in reports

- Jenkinsfile
Cleanup workspace after build complete.
> DW-129 clean workspace when finished

- Dockerfile.RELEASES
Sumamos el parametro de ruteo para cdn (#)
Y necesita hacer rebuild para que lo tome
> fix: fix version release for cdn

- public/index.html
- src/components/Integrations/Shopify/Shopify.js
Related to: https://github.com/FromDoppler/Doppler-UI-System/pull/219
> Add grid system in shopify

- src/components/Reports/SubscriberHistory/SubscriberHistoryCurrentSearch/SubscriberHistoryCurrentSearch.js
- src/components/Reports/SubscriberHistory/SubscriberHistoryCurrentSearch/SubscriberHistorySentCampaigns/SubscriberHistorySentCampaigns.js
- src/components/Reports/SubscriberHistory/SubscriberHistoryCurrentSearch/SubscriberHistorySentCampaigns/SubscriberHistorySentCampaigns.test.js
- src/i18n/en.js
- src/i18n/es.js
- src/services/doppler-api-client.double.ts
- src/services/doppler-api-client.test.ts
- src/services/doppler-api-client.ts
https://cdn.fromdoppler.com/doppler-webapp/build1985/#/reports/subscriber-history
> feat(doppler-api-client): get campaigns deliveries method

- src/components/Reports/ReportsBox/ReportsBox.js
- src/components/Reports/ReportsDailyVisits/ReportsDailyVisits.js
- src/components/Reports/ReportsHoursVisits/ReportsHoursVisits.js
- src/components/Reports/ReportsHoursVisits/ReportsHoursVisits.test.js
- src/components/Reports/ReportsPageRanking/ReportsPageRanking.js
- src/components/Reports/ReportsPageRanking/ReportsPageRanking.test.js
- src/components/Reports/ReportsTrafficSources/ReportsTrafficSources.js
- src/components/Reports/ReportsTrafficSources/ReportsTrafficSources.test.js
- src/components/Reports/SubscriberHistory/SubscriberHistoryCurrentSearch/SubscriberHistoryCurrentSearch.js
- src/components/Reports/SubscriberHistory/SubscriberHistoryCurrentSearch/SubscriberHistoryCurrentSearch.test.js
- src/components/Reports/SubscriberHistory/SubscriberHistoryCurrentSearch/SubscriberHistorySentCampaigns/SubscriberHistorySentCampaigns.js
- src/components/Reports/SubscriberHistory/SubscriberHistoryCurrentSearch/SubscriberHistorySentCampaigns/SubscriberHistorySentCampaigns.test.js
- src/i18n/en.js
- src/i18n/es.js
- change the name for a common name because it's a general error message
> refactor(General): change name of general errors

- public/index.html
- src/components/Login/Login.js
- src/services/doppler-legacy-client.doubles.ts
- src/utils.ts
- Added loggly in index
- Added function to log an entry
- Added log entry in login only for unexpected error with the following information:
- account: user account for doppler
- origin: href origin to know enviroment of origin
- section: right now only login
- browser: browser in which the error occur
- error: callback result with error
[Loggly Setup](https://dopplerwebapp.loggly.com/sources/setup/js-app-setup) 
To see the log with correct credentials [here](https://dopplerwebapp.loggly.com/search#terms=&from=2019-12-20T17:52:33.937Z&until=2019-12-20T18:22:33.937Z&source_group=)
> DW-151 Add logger for log errors in login

- src/components/Reports/SubscriberHistory/SubscriberHistory.js
- src/components/Reports/SubscriberHistory/SubscriberHistoryCurrentSearch/SubscriberHistoryCurrentSearch.js
- Add formik in the subscriber search form. 
- The idea is search when have 3 or more characters and submit form when write
> fix(SubscriberHistory): add formik in search form

- public/index.html
**Update build version to correct select arrows**
> fix: update build version

- src/App.js
- src/components/Login/Login.js
- src/components/SafeRedirect.js
- src/components/SafeRedirect.test.js
- src/components/SiteTrackingRequired/SiteTrackingRequired.js
- Rename `RedirectToLegacyUrl` to `SafeRedirect`
- Detect full url in `SafeRedirect` and then redirect to this url or redirect to Doppler
- Add tests for `SafeRedirect` regarding partial and full urls
- Detect partial url
- Add whitelist and tests
> Dw-142 redirect to whitelist domain

- src/components/Reports/SubscriberHistory/SubscriberHistory.test.js
- src/components/Reports/SubscriberHistory/SubscriberHistoryCurrentSearch/SubscriberHistoryCurrentSearch.js
- src/components/Reports/SubscriberHistory/SubscriberHistoryCurrentSearch/SubscriberHistoryCurrentSearch.test.js
- src/services/doppler-api-client.double.ts
- src/services/doppler-api-client.test.ts
- src/services/doppler-api-client.ts
- Add the service method to get subscribers and the doubles and tests
> feat(SubscriberHistory): add service method to get subscribers

- public/index.html
- src/components/Reports/SubscriberHistory/SubscriberHistory.js
- src/components/Reports/SubscriberHistory/SubscriberHistoryCurrentSearch/SubscriberHistoryCurrentSearch.js
- src/i18n/en.js
- src/i18n/es.js
- accessibility tags added
- styles were added in the form and table
- update build version of the UI library
We review it with @fcoronelmakingsense
> feat: the grid system was implemented in the form

- public/index.html
- src/components/Reports/CampaignsHistory/CampaignsHistory.js
- update build version of the UI library
> fix: add grid system classes

- src/components/Reports/CampaignsHistory/CampaignsHistory.js
- src/i18n/en.js
- src/i18n/es.js
- src/services/doppler-api-client.double.ts
- src/services/doppler-api-client.test.ts
- src/services/doppler-api-client.ts
- yarn.lock
- Change service to map the subscriber status.
- Show icon in the subscriber header view
> feat(CampaignsHistory): add subscriber status icon

- yarn.lock
Reverted `yarn.lock` just by now because of this error:
> fix: revert yarn lock @semantic-release/github issue

- src/components/Reports/CampaignsHistory/CampaignsHistory.js
- src/components/Reports/SubscriberHistory/SubscriberHistoryCurrentSearch/SubscriberHistoryCurrentSearch.js
- src/utils.ts
> fix(SubscriberHistoryCurrentSearch): add correct status icon

- public/index.html
- src/components/Reports/CampaignsHistory/CampaignsHistory.js
- src/i18n/en.js
- src/i18n/es.js
> New icons subscriber history

- src/components/Reports/CampaignsHistory/CampaignsHistory.js
- src/components/Reports/SubscriberHistory/SubscriberHistoryCurrentSearch/SubscriberHistoryCurrentSearch.js
- src/components/shared/StarsScore/StarsScore.js
- src/components/shared/StarsScore/StarsScore.test.js
- src/services/doppler-api-client.double.ts
- Add star icons in subscriber search results
- Add star icons in campaigns history results
> fix(CampaignsHistory): add star icons in grid

- src/components/Reports/CampaignsHistory/CampaignsHistory.js
- src/components/Reports/CampaignsHistory/CampaignsHistory.test.js
- src/i18n/en.js
- src/i18n/es.js
- Change message
- Add tests to check the message
> fix(CampaignsHistory): grid empty message

- src/components/SafeRedirect.js
- src/components/Signup/Signup.js
- src/services/doppler-legacy-client.ts
- src/utils.test.js
- src/utils.ts
For doppler academy, we need to allow redirect after the user has signed up. 
This url we plan on use in doppler back end after user activation.
- Added redirect url parameter into signup
- Mapped redirect into legacy service to allow redirect into back end
- Before map check redirect url is whitelisted, otherwise map nothing
> DW-177 add redirect url signup

- src/components/Reports/CampaignsHistory/CampaignsHistory.js
- src/components/Reports/CampaignsHistory/CampaignsHistory.test.js
- src/components/shared/Pagination/Pagination.js
- src/services/doppler-api-client.double.ts
- src/services/doppler-api-client.test.ts
- src/services/doppler-api-client.ts
- create new component to manage the pagination
- change service method to use the current page and the quantity per page
- change page when click in numbers
> feat(CampaignsHistory): add pagination

- src/services/doppler-legacy-client.ts
> DW-171 chore: add more data to log

- src/App.js
- src/components/Reports/CampaignsHistory/CampaignsHistory.js
- src/components/Reports/MasterSubscriber/MasterSubscriber.js
- src/components/Reports/MasterSubscriber/MasterSubscriber.test.js
- src/components/Reports/MasterSubscriber/MasterSubscriberCurrentSearch/MasterSubscriberCurrentSearch.js
- src/components/Reports/MasterSubscriber/MasterSubscriberCurrentSearch/MasterSubscriberCurrentSearch.test.js
- src/components/Reports/SubscriberHistory/SubscriberHistory.js
- src/components/Reports/SubscriberHistory/SubscriberHistory.test.js
- src/i18n/en.js
- src/i18n/es.js
- Change subscriber history to master subscriber
> fix(SubscriberHistory): change component name to MasterSubscriber

- src/services/doppler-api-client.double.ts
- src/services/doppler-api-client.test.ts
- src/services/doppler-api-client.ts
- Add links mappings in service
> fix(SubscriberHistory): add link preview in campaigns history

- src/components/Reports/MasterSubscriber/MasterSubscriberCurrentSearch/MasterSubscriberCurrentSearch.js
- change link in master subscriber to go the subscriber history detail
> fix(MasterSubscriberCurrentSearch): link to subscriber history

- public/index.html
- src/components/Reports/SubscriberHistory/SubscriberHistory.js
> feat: add campaign header

- src/components/Reports/MasterSubscriber/MasterSubscriber.js
- src/components/Reports/SubscriberHistory/SubscriberHistory.js
- src/components/Reports/SubscriberHistory/SubscriberHistory.test.js
- src/i18n/en.js
- src/i18n/es.js
- src/services/doppler-api-client.double.ts
- src/services/doppler-api-client.test.ts
- src/services/doppler-api-client.ts
- show preview when has preview image if not only show the link to the campaign report.
- add test to verify the mapping when has preview
> fix(SubscriberHistory): add campaign preview in grid

- Dockerfile
- Dockerfile.BUILDS_AND_CDN
- Dockerfile.LOCAL
- Dockerfile.RELEASES
- Dockerfile.swarm
- Update node to version 12 to support new features
> feat(Node): update to version 12

- src/components/Reports/SubscriberHistory/SubscriberHistory.js
- src/i18n/en.js
- src/i18n/es.js
- src/services/doppler-api-client.double.ts
> fix(SubscriberHistory): add remotion date in subscriber detail

- public/index.html
- src/components/shared/Pagination/Pagination.js
> feat: add subscriber history pagination styles

- Dockerfile
- Dockerfile.BUILDS_AND_CDN
- Dockerfile.LOCAL
- Dockerfile.RELEASES
- build-w-docker.sh
- verify-n-generate-release-w-docker.sh
- verify-w-docker.sh
- watch-w-docker.sh
Missing updates in scripts, related PR: https://github.com/FromDoppler/doppler-webapp/pull/709
> fix: update node version in scripts to 12.14.1

- src/components/Reports/SubscriberHistory/SubscriberHistory.js
- src/components/Reports/SubscriberHistory/SubscriberHistory.test.js
- Redirect to master subscriber when you put a subscriber doesn't exist for this user
> fix(SubscriberHistory): redirect master subscriber 

- public/index.html
- src/components/Reports/SubscriberHistory/SubscriberHistory.js
> fix: subscriber history status fix and update build version

- src/components/Reports/MasterSubscriber/MasterSubscriberCurrentSearch/MasterSubscriberCurrentSearch.js
> fix(MasterSubscriber): subscriber status icon

- .env.int
- .env.qa
- change http protocol to https for the doppler api
> fix(Environment): change protocol for api int and qa

- src/components/Reports/SubscriberHistory/SubscriberHistory.test.js
- src/i18n/en.js
- src/i18n/es.js
- src/utils.ts
Fix status icon and text in master subscriber grid and subscriber history detail
> fix(SubscriberHistory): stand by status icon and text

- src/components/shared/Pagination/Pagination.js
> fix(SubscriberHistory): pagination current page style

- package.json
- src/.stylelintrc.json
- src/App.css
- src/components/ForgotPassword/ForgotPassword.styles.js
- src/components/Reports/ReportsFilters/ReportsFilters.styles.js
- src/components/Reports/ReportsPageRanking/ReportsPageRanking.styles.js
- src/components/Reports/ReportsTrafficSources/ReportsTrafficSources.styles.js
- src/components/styles/animations.js
- yarn.lock
library website: https://stylelint.io/
> Dw-102 install styleint

- src/components/Login/Login.test.js
- src/components/Reports/MasterSubscriber/MasterSubscriber.js
- src/components/Reports/MasterSubscriber/MasterSubscriberCurrentSearch/MasterSubscriberCurrentSearch.js
- src/components/Reports/ReportsPageRanking/ReportsPageRanking.js
- Fix warnings in the tests. Now only have the warnings for the Remarkable
> fix(Test): warnings in the tests

- package.json
- src/services/doppler-legacy-client.ts
- src/services/pure-di.AppCompositionRoot.test.ts
- src/services/pure-di.tsx
- yarn.lock
For network error, or timeout errors retry 3 times automatically.
> DW-186: axios retry for login only with log

- conf/site-int.conf
- conf/site-production.conf
- conf/site-qa.conf
Configure forward secrecy in nginx
https://www.digicert.com/kb/ssl-support/ssl-enabling-perfect-forward-secrecy.htm
> DW-210:feat: improve security configuration

- src/components/Header/Header.js
- src/components/Header/HeaderNav/HeaderNav.js
- src/services/doppler-legacy-client.ts
- src/utils.ts
- Refactor functionality of get the current selected menu option depend of the current url
Shopify
Reports
Subscriber History 
Master Subscriber
> fix(Header): selected menu option with differents urls

- src/components/Login/Login.js
- src/index.js
> fix(Login): show promotions depend of the page parameter

- src/components/Reports/ReportsPartialsCampaigns/ReportsPartialsCampaigns.js
- src/components/Reports/ReportsPartialsCampaigns/ReportsPartialsCampaigns.styles.js
- src/components/styles/colors.js
- src/utils.ts
- the layout proposal of partially sent campaigns was added
- red color variable added
> feat: the layout proposal of partially sent campaigns was added

- src/components/Header/Header.js
- src/utils.ts
- fix header when dont have menu for the url.
> fix(Header): inactive section fallback

- .env.development
- .env.int
- .env.production
- .env.qa
- src/components/Header/Header.js
- src/components/Reports/SubscriberHistory/SubscriberHistory.js
- src/services/pure-di.tsx
- Use env variables to get the de domain for reports
- Change in header variable name to more clear
> fix(SubscriberHistory): change reports url depend of the environment

- src/components/Reports/GDPR/SubscriberGdpr.js
- src/i18n/en.js
- src/i18n/es.js
> fix(SubscriberGdpr): add missing breadcrumb

- src/utils.ts
- Fix selected menu option and sub menu in subscriber history and gdpr
> fix(Header): selected menu in subscriber history

- src/components/Reports/GDPR/SubscriberGdpr.js
- src/components/Reports/GDPR/SubscriberGdpr.styles.js
- fix styles when have more than one permission.
> fix(SubscriberGdpr): permission styles in grid

- public/index.html
> fix(confirmation page): logo relocation on confirmation page

- src/App.test.js
- src/components/Integrations/Shopify/Shopify.test.js
- src/components/Login/Login.test.js
- src/components/Reports/GDPR/SubscriberGdpr.test.js
- src/components/Reports/MasterSubscriber/MasterSubscriberCurrentSearch/MasterSubscriberCurrentSearch.test.js
- src/components/Reports/Reports.test.js
- src/components/Reports/ReportsHoursVisits/ReportsHoursVisits.test.js
- src/components/Reports/ReportsPageRanking/ReportsPageRanking.test.js
- src/components/Reports/ReportsPartialsCampaigns/ReportsPartialsCampaigns.test.js
- src/components/Reports/ReportsTrafficSources/ReportsTrafficSources.test.js
- src/components/Reports/SubscriberHistory/SubscriberHistory.test.js
- src/components/Signup/Signup.test.js
- src/components/SiteTrackingRequired/SiteTrackingRequired.test.js
- src/components/shared/Promotions/Promotions.test.js
- change old `wait` and `waitForDomChange` to the new `waitFor`
> fix(Test): warnings for update version

- package.json
- src/components/Footer/Footer.js
- src/components/ForgotPassword/ForgotPassword.js
- src/components/Integrations/Shopify/Shopify.js
- src/components/Integrations/Shopify/Shopify.test.js
- src/components/Login/Login.js
- src/components/Login/LoginErrorAccountNotValidated.js
- src/components/Reports/Reports.test.js
- src/components/Reports/ReportsFilters/ReportsFilters.js
- src/components/Signup/Signup.js
- src/components/Signup/Signup.styles.js
- src/components/Signup/SignupConfirmation.js
- src/components/SiteTrackingRequired/SiteTrackingRequired.js
- src/components/form-helpers/form-helpers.css
- src/components/form-helpers/form-helpers.js
- src/i18n/FormattedMessageMarkdown.js
- src/i18n/en.js
- src/i18n/es.js
- yarn.lock
- Create new constants for urls in languages files to can use in the views
- Remove `FormattedHTMLMessage` elements and change to `FormattedMessage` component.
https://github.com/formatjs/react-intl/blob/master/docs/Components.md#formattedmessage
> feat(React-intl): update to version 4.2.2

- src/components/ForgotPassword/ForgotPassword.js
- src/components/Login/Login.js
- src/components/Signup/Signup.js
- src/components/Signup/Signup.test.js
- Add in signup, login and forgot password links maintain the parameters in the url.
> fix(Login): maintain parameters between login pages

- src/App.js
- src/components/NewFeatures/NewFeatures.js
Only in spanish, for not linked functionality in app, this section can inform and allow easy access.  It may help us communicate better. 
Link to this functionality: https://cdn.fromdoppler.com/doppler-webapp/int-build2275/#/new-features
> feat(new-features): add new features panel

- src/components/ForgotPassword/ForgotPassword.js
- src/components/Login/Login.js
- src/components/Login/Login.test.js
- src/components/Signup/Signup.js
- src/components/shared/LanguageSelector/LanguageSelector.js
- src/components/shared/LanguageSelector/LanguageSelector.test.js
- Refactor component to maintain de urls parameters. Remove `?` and `lang` parameter for url and then url is created again with the lang first and then the exist urls parameters
> fix(LanguageSelector): maintain url parameters

- src/App.test.js
- Fix act warnings we had in `App.test`. I used this documentation to fix that:
https://kentcdodds.com/blog/fix-the-not-wrapped-in-act-warning
> fix(App): act warnings in the tests

- src/components/Signup/Signup.test.js
- src/components/form-helpers/form-helpers.js
- src/index.js
- src/services/ipinfo-client.doubles.ts
- src/services/ipinfo-client.test.ts
- src/services/ipinfo-client.ts
- src/services/pure-di.tsx
Show flag in phone element based on user ip using ipinfo.io
> Add flag in phone input based in IP country

- src/components/Login/Login.js
- add before submit in login a trim function to remove white spaces in user name
> fix(Login): remove white spaces before send to BE

- public/index.html
- src/components/NewFeatures/NewFeatures.js
- src/components/Reports/GDPR/SubscriberGdpr.js
- src/components/Reports/MasterSubscriber/MasterSubscriber.js
- src/components/Reports/ReportsBox/ReportsBox.js
- src/components/Reports/ReportsDailyVisits/ReportsDailyVisits.js
- src/components/Reports/ReportsFilters/ReportsFilters.js
- src/components/Reports/ReportsHoursVisits/ReportsHoursVisits.js
- src/components/Reports/ReportsPageRanking/ReportsPageRanking.js
- src/components/Reports/ReportsPartialsCampaigns/ReportsPartialsCampaigns.js
- src/components/Reports/ReportsTrafficSources/ReportsTrafficSources.js
- src/components/Reports/ReportsTrafficSources/ReportsTrafficSources.styles.js
- src/components/Reports/SubscriberHistory/SubscriberHistory.js
- add the class hero-banner and the arrow of this component was fixed and the titles h3 were changed to h2
- line-heights, paddings and margins were retouched
- replace small with h6 for better semantics
related to: https://github.com/FromDoppler/Doppler-UI-System/pull/292
> Add hero banner

- src/components/Reports/ReportsPartialsCampaigns/ReportsPartialsCampaigns.js
- src/components/Reports/ReportsPartialsCampaigns/ReportsPartialsCampaigns.styles.js
- src/components/styles/fonts.js
- src/i18n/en.js
- src/i18n/es.js
> fix(ReportsPartialsCampaigns): change UI with new design

- src/components/Reports/ReportsPartialsCampaigns/ReportsPartialsCampaigns.js
- src/components/Reports/ReportsPartialsCampaigns/ReportsPartialsCampaigns.styles.js
- src/services/doppler-api-client.double.ts
- src/services/doppler-api-client.ts
> fix(ReportsPartialsCampaigns): dates when are null

- src/App.js
- src/components/NewFeatures/NewFeatures.js
- src/components/Reports/ReportsNew.js
- src/components/Reports/ReportsNew.test.js
- Add new reports page empty.
- Add test to check load ok.
- Add page in new features.
> feat(ReportsNew): add new reports page

- src/components/Reports/Reports.js
- src/components/Reports/ReportsBox/ReportsBox.js
- src/components/Reports/ReportsBox/ReportsBox.test.js
- Refactor the `Reports` component to get the data for the total visits here.
- Refactor the `ReportsBox` component to only show data.
> refactor(Reports): change the implementation to get total visits

- src/components/Reports/Reports.js
- src/components/Reports/Reports.test.js
- src/components/Reports/ReportsNew.js
- src/services/datahub-client.doubles.ts
- src/services/datahub-client.test.ts
- src/services/datahub-client.ts
- Rename old method maintain the old functionality working
- Add new method with the new datahub endpoint
- Add tests for this method
- Add the double method for this method.
---
TODO: add in the new Reports component this functionality
> feat(Reports): add new total visitors method

- src/components/Reports/Reports.js
- src/components/Reports/Reports.test.js
- src/components/Reports/ReportsNew.js
- src/components/Reports/ReportsTrafficSources/ReportsTrafficSources.js
- src/components/Reports/ReportsTrafficSources/ReportsTrafficSources.test.js
- src/components/Reports/ReportsTrafficSources/ReportsTrafficSourcesOld.js
- src/components/Reports/ReportsTrafficSources/ReportsTrafficSourcesOld.test.js
- src/services/datahub-client.doubles.ts
- src/services/datahub-client.test.ts
- src/services/datahub-client.ts
- Rename old service method.
- Add new service method
- Add new tests
- Add new service doubles method
- Add new component
> Feat(ReportsTrafficSources): add new service and new component

- public/index.html
- src/components/Reports/ReportsDailyVisits/ReportsDailyVisits.js
- src/components/Reports/ReportsPageRanking/ReportsPageRanking.styles.js
- src/components/Reports/ReportsTrafficSources/ReportsTrafficSources.styles.js
- src/components/shared/C3Chart/C3Chart.styles.js
- add ancestor
- component style adjustment
related to: https://github.com/FromDoppler/Doppler-UI-System/pull/303
> feat: add ancestor

- public/index.html
- src/components/Reports/ReportsDailyVisits/ReportsDailyVisits.js
- src/components/Reports/ReportsPageRanking/ReportsPageRanking.styles.js
- src/components/Reports/ReportsTrafficSources/ReportsTrafficSources.styles.js
- src/components/shared/C3Chart/C3Chart.styles.js
> fix: revert "Merge pull request #873 from GusBaamonde/add-ancestor-for-library-operation"

- public/index.html
- src/components/PublicRouteWithLegacyFallback.js
- src/components/Reports/ReportsDailyVisits/ReportsDailyVisits.js
- src/components/Reports/ReportsPageRanking/ReportsPageRanking.styles.js
- src/components/Reports/ReportsTrafficSources/ReportsTrafficSources.styles.js
- src/components/shared/C3Chart/C3Chart.styles.js
- component style adjustment
- update build version
https://cdn.fromdoppler.com/doppler-webapp/build2349/#/login
> feat: add ancestor for library operation

- src/components/Reports/Reports.js
- src/components/Reports/ReportsDailyVisits/ReportsDailyVisitsOld.js
- src/components/Reports/ReportsNew.js
- src/components/Reports/ReportsNew.test.js
- src/components/shared/C3Chart/C3Chart.styles.js
- src/services/datahub-client.doubles.ts
- src/services/datahub-client.test.ts
- src/services/datahub-client.ts
- Add new service method and new double service method.
- Add tests for this methods.
- Add new component and rename the old one
- Change some styles to be generic.
---
TODO add more tests
> feat(Reports): add new component and service to show daily visits

- public/index.html
> feat: library version update

- src/App.js
- src/components/NewFeatures/NewFeatures.js
- Change reports old to the `/reports-old` url
> fix(Reports): change reports page link  for the new one

- public/index.html
Temporal html for offline app.
> fix: add offline page

- public/index.html
Sorry guys, by accident I merged #899 and it is not necessary anymore.
> fix: Revert "fix: add offline page"

- public/index.html
> fix(index): add spinner when load webapp

- public/index.html
- src/components/PrivateRoute.js
- src/components/PublicRouteWithLegacyFallback.js
- fix the spinner behind the webapp when loading and when redirect another page
> fix(index): spinner behind the root component

- src/components/NewFeatures/NewFeatures.js
- src/components/Offline/Offline.js
- Add no index in offline page and in new features to search robots no index this page.
> fix(Offline): add no index in offline page

- public/index.html
- src/components/form-helpers/form-helpers.css
Related to: https://github.com/FromDoppler/Doppler-UI-System/pull/314
> fix: display dropdown of flags on mobile

- src/components/Signup/SignupConfirmation.js
- src/components/Signup/SignupConfirmation.styles.js
- fix styles to put spinner behind the page
> fix(SignupConfirmation): spinner behind content

- src/components/Reports/ReportsNew.js
- src/components/Reports/ReportsNew.test.js
- change default reports period selected from today to 3 weeks
> fix(Reports): update default weeks to 3

- src/components/Reports/GDPR/SubscriberGdpr.js
Unsubscribed Date was showed wrong. (It was showing today)
> fix: get all subscriber info

- Jenkinsfile
Add missing environments into jenkins file to replace the use of `darosw` user in docker hub. 
Then I will update the swarm services.
We had only production and demo environments published in `fromdoppler`
Issue: DW-383
> feat: add publish webapp image into fromdoppler organization

- src/components/Reports/SubscriberHistory/SubscriberHistory.js
Change hardcoded reports enviroment url when the campaign doesn't have a preview.
> chore: change hardcoded reports enviroment url

- src/i18n/en.js
- src/i18n/es.js
> fix(Login): unexpected error message

- src/App.js
I've accidentally put this section as public, now it's set to private (need to be logged in)
> fix: add push as private route

- src/components/Signup/Signup.test.js
- Fix tests in signup fail random, because the service of flag have a delay to obtain the data
> fix(Signup): flag tests

- src/components/Login/Login.js
- src/i18n/en.js
- src/i18n/es.js
- src/utils.ts
Improve blocked account error message to be more specific about the error. 
CDN: https://cdn.fromdoppler.com/doppler-webapp/int-build2530/#/login
user: lgarcia+25@makingsense.com
pass: 1qaz2wsx
Please @mrunge86 and @santiagopaolucci check this.  
To do: 
English:
Spanish:
> [feat] improve blocked account error msg

- src/services/doppler-legacy-client.ts
It adds a TODO to manage not payed cancelled accounts.
This change is to avoid show a general error in this cases. 
https://cdn.fromdoppler.com/doppler-webapp/int-build2531/#/login
> feat: add TODO to manage new error

- src/components/Login/Login.js
- src/i18n/en.js
- src/i18n/es.js
- src/services/doppler-legacy-client.doubles.ts
- src/services/doppler-legacy-client.ts
- It shows a different message if the account was canceled due to non-payment.
- It shows a general message if the account was canceled for other reasons. 
- It refact the way that the content was in intl files. 
- Update details in blocked accounts messages.  
FYI: Till the release, it will show a general canceled message for all cancellation reasons.
LinkINT: https://cdn.fromdoppler.com/doppler-webapp/int-build2535/#/login
> Dw 417 cancelated account msg

- src/components/Reports/ReportsPartialsCampaigns/ReportsPartialsCampaigns.js
- src/components/Reports/ReportsPartialsCampaigns/ReportsPartialsCampaigns.styles.js
https://cdn.fromdoppler.com/doppler-webapp/demo-build2539/#/reports/partials-campaigns
> fix: styled component and html

- src/components/Login/Login.js
- src/i18n/en.js
- src/i18n/es.js
- It add a different error message for invalid passord or max login attemps.
Test: https://cdn.fromdoppler.com/doppler-webapp/int-build2543/#/login
> feat: improve msg for invalid pass

- src/components/NewFeatures/NewFeatures.js
- src/components/PushNotifications/PushNotifications.js
- src/components/Reports/MasterSubscriber/MasterSubscriber.js
- src/components/Reports/ReportsFilters/ReportsFilters.js
- src/components/Reports/ReportsPartialsCampaigns/ReportsPartialsCampaigns.js
- src/components/Reports/Subscribers/Subscribers.js
- src/components/shared/HeaderSection/HeaderSection.js
- Create shared component with the internal header section styles and structure for reuse in internal pages.
> feat(PrivatePages): add header section template with common styles

- public/index.html
Reverts FromDoppler/doppler-webapp#1020
> chore: revert Test CloudFlare cache

- src/App.js
- src/components/DopplerPlus/PlanCalculator.js
- src/components/NewFeatures/NewFeatures.js
- src/components/shared/Slider/Slider.js
- src/components/shared/Slider/Slider.styles.js
- src/components/shared/Slider/Slider.test.js
Link test:  https://cdn.fromdoppler.com/doppler-webapp/demo-build2569/#/plan-calculator
✔️Included in this PR:
- Slider element
- basic behavior to change price based on slider value
------------------------------------------------------------------------------
⛔ Not included in this PR:
- styles
- discount element
- content
- double service to obtain data
- params
> Dw 435 plans sliders

- src/components/DopplerPlus/PlanCalculator.js
- It add a basic behavior to apply discounts.
CDN: https://cdn.fromdoppler.com/doppler-webapp/demo-build2575/#/plan-calculator
> feat: add discounts for plans

- src/App.js
- src/components/DopplerPlus/PlanCalculator.js
- src/services/doppler-legacy-client.doubles.ts
- src/services/doppler-legacy-client.ts
**In this pr:**
- Create a getPlansList method in a double service (moving hardcoded info from the element)
- Add parameters in the url: [type plan id], [discount id] and [promocode]
- Add a button with the url to buy, using values chosen by the user in the screen and promocode if exists
**Todo:**
- Obtain real data from the BE or hardcode it. 
URL DEMO: http://cdn.fromdoppler.com/doppler-webapp/demo-build2595/#/plan-calculator/1/buy?discountId=3&promoId=CUMPLE
> Dw 445 double service for plan calculator

- src/utils.ts
> feat: add whitelisted url to redirect

- src/components/Reports/Reports.js
- src/components/Reports/Reports.test.js
- src/components/Reports/ReportsPageRanking/ReportsPageRanking.js
- src/i18n/en.js
- src/i18n/es.js
- src/services/datahub-client.doubles.ts
- src/services/datahub-client.test.ts
- src/services/datahub-client.ts
- It adds ranking page in reports again.
link: http://cdn.fromdoppler.com/doppler-webapp/qa-build2612/#/reports/
> feat: add reports page ranking again

- package.json
- src/.stylelintrc.json
- src/App.css
- src/components/ChangePlan/ChangePlan.js
- yarn.lock
- Add toggle animation when compare features between plans. like in the UI library. https://cdn.fromdoppler.com/doppler-ui-library/latest/doppler-plus.html
> fix(ChangePlan): add animation in compare features plan.

- package.json
- src/services/doppler-legacy-client.doubles.ts
- src/services/doppler-legacy-client.test.js
- src/services/doppler-legacy-client.ts
- yarn.lock
Get the IdUser from JWT Token. For it we used the property **"nameId"**
``` 
jwtToken: {
"nameid": 100333,
....
}
```
Changes:
- For decode the token, we used the 'jwt_decode' library.
**Task:** [DAT-138](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-138)
> DAT-138: Get IdUser from JWT Token

- .env.development
- .env.int
- .env.production
- .env.qa
- src/App.js
- src/components/InvoicesList/InvoicesList.js
- src/components/InvoicesList/InvoicesList.test.js
- src/components/NewFeatures/NewFeatures.js
- src/i18n/en.js
- src/i18n/es.js
- src/index.js
- src/services/doppler-billing-api-client.double.ts
- src/services/doppler-billing-api-client.test.ts
- src/services/doppler-billing-api-client.ts
- src/services/pure-di.tsx
Changes:
- Included new item in the "new features". The sections is "Facturas emitidas":
- Created new component to shows the invoices given an idUser:
Task: [DAT-128](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-128)
> DAT-128-Add invoices list

- src/components/ChangePlan/PlanCalculator.js
- Create a new element to show the plan price. 
```
<PlanPrice>
<PlanPriceWithoutDiscounts planData={planData} />
<PlanPricePerMonth planData={planData} />
<PlanAgreement planData={planData} />
</PlanPrice>
```
> Dw 529 create plan price element

- src/components/shared/Slider/Slider.js
Improve slider when there are only one value:
> fix(Slider): fix UI in slider with one value

- src/components/Header/HeaderUserMenu/HeaderUserMenu.js
- src/components/Header/HeaderUserMenu/HeaderUserMenu.test.js
- src/doppler-types.ts
- src/headerData.json
- src/i18n/en.js
- src/i18n/es.js
- Apply new UI and changes in header user menu.
> feat(HeaderUserMenu): apply new ui

- Jenkinsfile
- package.json
Only two points to be modified, I will leave this pr in draft until needed. 
https://github.com/github/renaming
> feat: allow deploy from master and main

- src/components/DopplerPlus/AgenciesForm.js
- src/components/Integrations/Shopify/Shopify.js
- src/components/Reports/Subscribers/Subscribers.js
Use the Breadcrumb component in "AgenciesForm", "Subscribers" and "Shopify".
**AgenciesForm:**
Before:
```
<nav className="dp-breadcrumb">
<ul>
<li>
<a href={_('agencies.breadcrumb_url')}>{_('agencies.breadcrumb')}</a>
</li>
<li>{_('agencies.title')}</li>
</ul>
</nav>
```
Now:
```
<Breadcrumb>
<BreadcrumbItem href={_('agencies.breadcrumb_url')} text={_('agencies.breadcrumb')} />
<BreadcrumbItem text={_('agencies.title')} />
</Breadcrumb>
```
**Subscribers:**
Before:
```
<nav className="dp-breadcrumb">
<ul>
<li>
{/* TODO: rename as master_subscriber_url and master_subscriber_title */}
<a href={_('subscriber_history.subscriber_breadcrumb_url')}>
{_('subscriber_history.subscriber_breadcrumb')}
</a>
</li>
<li>{currentSection.title}</li>
</ul>
</nav>
```
Now:
```
<Breadcrumb>
{/* TODO: rename …
```
> feat(breadcrumb): Use the breadcrumb component in "AgenciesForm", "Subscribers" and "Shopify"

- public/index.html
- public/manifest.json
> fix: update manifest.json for favicon system

- src/components/Signup/SignupConfirmation.js
ReCaptcha wasn't working because there wasn't injected the dependencies in signup form.
> fix(SignupConfirmation): inject dependencies

- src/components/Signup/Signup.test.js
- It add a test to check that confirm page is showed when user submits the form.
> chore(Signup): add test

- src/i18n/en.js
- src/i18n/es.js
As it was requested in the demo, fix for content. 
@mrunge86 you can check 😄 
https://cdn.fromdoppler.com/doppler-webapp/qa-build2890/#/login
> fix(content): change user disable by cm message

- yarn.lock
- Update yarn lock to fix semantic release
> fix(yarn.lock): update file

- src/i18n/en.js
- src/i18n/es.js
When there are connection issues, or interruption by deploy now we will be showing this message in login:
> fix(login): disconnected or unexpected error change

- src/components/DopplerPlus/ExclusiveForm.js
- src/components/form-helpers/form-helpers.js
> fix(ExclusiveForm): change checkbox to formik elements

- .env
- .env.development
- .env.int
- .env.production
- .env.qa
- src/services/manual-status-client.ts
- src/services/pure-di.tsx
Added test file in cdn to test mainenance page in int or qa, right now set for testing only in qa an dev. 
So if you want the app offline: 
- Enable manual override flag must be on for env
- Contact with mvc back end severed
- And edit the correct file, setting offline to true
> feat(deploy-page): add test toggle file

- src/components/Offline/Offline.js
Changed message to avoid time and inform about campaign sending.
> fix(deploy-page): change message

- src/components/Login/Login.js
- src/services/doppler-legacy-client.ts
- On retry log only last attempt
- Remove login post logged into login component (since it will log then again on retry)
> Improve loggly log

- src/services/doppler-legacy-client.ts
- src/utils.test.js
- src/utils.ts
Reorganized data to be more useful and reduce log size:
Examples:
For signup:
```
{
"origin":"http://localhost:3000",
"account":"cbernat@makingsense.com",
"signupOrigin":"login",
"postUrl":"WebAppPublic/CreateUser",
"browser":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
"errorMessage":"Network Error"
}
```
For login: 
```
{
"origin":"http://localhost:3000",
"account":"cbernat@getcs.com",
"postUrl":"WebAppPublic/Login",
"browser":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
"errorMessage":"Network Error"
}
```
> Dw 616 improve data for log

- Jenkinsfile
- publish-commit-image-to-dockerhub.sh
We will publish images to both registries fromdoppler (current) and dopplerdock (new).
On the first commit we are checking if we can remove some steps in the current proccess
> DM-802 - New docker registry

- src/components/shared/Pagination/Pagination.js
- src/components/shared/Pagination/Pagination.test.js
- src/i18n/en.js
- src/i18n/es.js
- Add title in pagination scroll (...)
> feat(Pagination): add title in pagination scrolls

- src/components/Login/Login.js
- src/components/form-helpers/form-helpers.js
Loggly
- Add loggly for recaptcha error
- Add loggly for unexpected error
> Dw 624 add logly to analize recaptcha problems

- src/utils.ts
> feat(utils): specify section for loggly

- src/components/ChangePlan/ChangePlan.js
- src/components/ChangePlan/ChangePlan.styles.js
- src/components/styles/fonts.js
- src/i18n/en.js
- src/i18n/es.js
- Add banner in plans page to link exclusive features form
> feat(ExclusiveFeatures): add banner in plans page

- src/components/Header/HeaderUserMenu/HeaderUserMenu.js
- src/components/Signup/Signup.js
- src/i18n/en.js
- src/i18n/es.js
- src/services/doppler-legacy-client.doubles.ts
- src/services/doppler-legacy-client.ts
Add error message for invalid domain (this validates the domain exists to avoid suspicious or non existent emails)
Only for signup section.
Associated to https://github.com/MakingSense/Doppler/pull/7646
DW-649 in jira.
> feat(signup): add message for new invalid domain error

- src/utils.ts
- Add https://academyqa.fromdoppler.com in white list
- Put all academy URLs together
> [DW-659] feat: add new domain in white list

- public/index.html
> [DW-657] fix: update google tag manager scripts

- src/services/session-manager.ts
```
{
"account":"hardcoded@email.com",
"origin":"http://localhost:3000",
"section":"Login/GetUserData",
"browser":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36",
"message":"Connection timed out"
}
```
Associated to https://github.com/FromDoppler/doppler-webapp/pull/1262
> fix(log):  for getUserData call add account if user is authenticated

- src/services/session-manager.ts
If the user is already logged in, and suddenly the connection is slower, it may happen that the connection is aborted due timeout. We had some entries like this, so we decided to keep the session as it is for this case.
> fix(session-manager): if connection is aborted leave session as is

- src/services/doppler-api-client.double.ts
- src/services/doppler-api-client.test.ts
- src/services/doppler-api-client.ts
Hi @FromDoppler/doppler-webapp and @FromDoppler/kreitech teams!
This is the adapter to access our Field History API (it does not exist yet).
> [DW-751] Implement adapter and double of Field History API

- src/services/doppler-api-client.ts
> chore: delete an unnecessary console log

- src/components/Reports/GDPRPermissions/PermissionExpandableRow.js
- src/components/Reports/GDPRPermissions/PermissionExpandableRow.test.js
> feat: show the arrow button if the value of the field is none

- src/components/Reports/GDPRPermissions/PermissionExpandableRow.js
- src/components/Reports/GDPRPermissions/PermissionExpandableRow.test.js
Remove the ExperimentalFeature dependency to enable the feature for all users.
> feat: enable feature to all users

- src/components/Signup/Signup.js
- Change in signup when create user, send the last 10 utm cookies to fix the problem when the utm cookies are a lot.
> fix(Signup): send last 10 items in utm cookies

- src/components/Reports/GDPRPermissions/PermissionExpandableRow.test.js
- src/components/Reports/GDPRPermissions/SubscriberGdpr.styles.js
- src/components/Reports/GDPRPermissions/SubscriberGdprPermissions.js
- src/components/Reports/GDPRPermissions/SubscriberGdprPermissions.test.js
- src/i18n/en.js
- src/i18n/es.js
- src/services/doppler-api-client.double.ts
- src/services/doppler-api-client.test.ts
- src/services/doppler-api-client.ts
> feat: add a link at the bottom of the report to download the permission history

- src/components/Reports/GDPRPermissions/PermissionExpandableRow.js
> fix: add missing dependency to useEffect

- src/i18n/en.js
- src/i18n/es.js
Remove utm params from login and signup urls
> DW-930 remove utms from login and signup

- src/App.js
- src/components/ContactPolicy/ContactPolicy.js
- src/components/NewFeatures/NewFeatures.js
- src/i18n/en.js
- src/i18n/es.js
> feat: add Contact Policy component with breadcumb and intro text

- src/i18n/en.js
- src/i18n/es.js
**scenario**
- The user navigates to /reports with a free account
- The following screen is displayed
> feat(en,es): add text in reports

- src/components/ForgotPassword/ForgotPassword.js
- src/components/ForgotPassword/ForgotPassword.test.js
- src/components/Signup/Signup.js
- src/components/Signup/Signup.test.js
**Ticket**: https://makingsense.atlassian.net/browse/DW-948
**escenario**
- The user navigates to **/signup** and creates an account with email **'hardcoded@hardcoded.com'**
- The user confirm your account
- The user navigates to **/signup**, again. The user creates an account with email **' hardcoded@hardcoded.com'** (whitespace)
- It is not allowed to create an account, because the email already exists
> Dw 948 fix duplicate emails

- public/index.html
HU: [DE-184](https://makingsense.atlassian.net/browse/DE-184)
Add script for Google Tag Manager with code GTM-TMMV2DF.
- New container that will be used by UX team.
- Official google documentation is used to use multiple containers on the same page.
https://developers.google.com/tag-manager/devguide?hl=en#multiple-containers
> DE-184 Add UX Google Tag Manager

- src/components/SiteTrackingRequired/SiteTrackingRequired.js
Removed target+_blank from this link:
> fix: internal link with target _blank

- src/components/ChangePlan/PlanCalculator.js
- src/components/ChangePlan/PlanCalculator.styles.js
- Apply transition UI when change tab.
> [DW-991] apply transition UI in tabs

- src/components/shared/Slider/Slider.test.js
> [DW-990] fix test

- src/components/Signup/Signup.js
- src/components/Signup/Signup.test.js
- src/services/doppler-legacy-client.ts
@jcamposmk Could you help me to create a small test for this PR?
> chore: add utm_content property to CreateUser

- src/components/ChangePlan/PlanCalculator/NavigatorTabs/NavigatorTabs.js
- Implement tooltip component.
> feat(NavigatorTabs): implement tooltip component

- .doppler-ci
Add dopplerci configuration as [in MSEditor](https://github.com/MakingSense/MSEditor/pull/1446)
> feat(deploy): add dopplerci configuration

- src/services/doppler-contact-policy-api-client.double.ts
- src/services/doppler-contact-policy-api-client.test.ts
- src/services/doppler-contact-policy-api-client.ts
> feat: add function to update account settings and tests

- src/components/ChangePlan/PlanCalculator/BannerUpgrade/BannerUpgrade.js
- src/components/ChangePlan/PlanCalculator/BannerUpgrade/BannerUpgrade.test.js
- Add tests to `BannerUpgrade.js` component.
> feat(BannerUpgrade): add tests

- src/components/ContactPolicy/ContactPolicy.js
- src/components/ContactPolicy/ContactPolicy.test.js
***To make use of this feature by console it can be enabled like this:**
`localStorage.setItem('dopplerExperimental', JSON.stringify({ContactPolicy: true}));`
> feat: add experimental feature

- src/i18n/en.js
There were some utms left in english version of login.
> fix(utm): remove utms from url

- src/components/DopplerPlus/AgenciesForm.test.js
- src/components/DopplerPlus/ExclusiveForm.test.js
task: https://makingsense.atlassian.net/browse/DW-1034
**ExclusiveForm** 
**AgenciesForm**
> fix: fix test exclusive and agencies form components

- src/components/ContactPolicy/ContactPolicy.js
- src/components/form-helpers/form-helpers.js
> feat: hide success message when the value of an input is changed.

- src/components/ChangePlan/Checkout/ContactInformation/ContactInformation.js
- src/components/ContactPolicy/ContactPolicy.js
- src/components/DopplerPlus/AgenciesForm.js
- src/components/DopplerPlus/ExclusiveForm.js
- src/components/ForgotPassword/ForgotPassword.js
- src/components/Login/Login.js
- src/components/Reports/MasterSubscriber/MasterSubscriber.js
- src/components/Signup/Signup.js
- src/utils.test.js
- src/utils.ts
task: https://makingsense.atlassian.net/browse/DW-1038
Add utility getFormInitialValues to prepare initial form values
**tests:**
> feat(utils): add getFormInitialValues utility

- .env.development
- .env.int
- .env.production
- .env.qa
- src/components/Integrations/BigQuery/ControlPanel/AuthorizationForm.js
- src/components/Integrations/BigQuery/ControlPanel/AuthorizationForm.test.js
- src/components/Integrations/BigQuery/ControlPanel/AuthorizationPage.js
- src/components/Integrations/BigQuery/ControlPanel/AuthorizationPage.test.js
- src/index.js
- src/services/big-query-client.double.ts
- src/services/big-query-client.test.ts
- src/services/big-query-client.ts
- src/services/http-base-client.ts
- src/services/pure-di.tsx
Add client for big query with getEmailsData method for bigquery authorization page fetch data
> feat(big-query): add bigquery client and getEmailsData method

- src/components/Header/HeaderUserMenu/HeaderUserMenu.js
- src/i18n/en.js
- src/i18n/es.js
* fix(HeaderUserMenu): fix client manager user menu:
And if there is a user of client manager :
> DW-1019-fix-client-manager-menu

- src/components/ContactPolicy/ContactPolicy.js
- src/components/ContactPolicy/ContactPolicy.test.js
- src/components/form-helpers/form-helpers.js
- src/i18n/en.js
- src/i18n/es.js
- src/services/doppler-contact-policy-api-client.double.ts
> feat: disable save button while updating or no changes

- src/utils.ts
Use ```const``` instead of ```var```
**Task:** [DAT-500](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-500)
> [DAT-500] - fix: use 'const' instead of 'var'

- src/components/ContactPolicy/ContactPolicy.js
- src/components/form-helpers/form-helpers.js
- src/i18n/en.js
- src/i18n/es.js
> feat: validate input fields range and show error messages

- src/components/ContactPolicy/ContactPolicy.js
- src/components/ContactPolicy/ContactPolicy.test.js
- src/i18n/en.js
- src/i18n/es.js
> feat: show alert to confirm go back if there are unsaved changes

- src/i18n/es.js
* fix(agenciesForm): update features content
*
> DW-1001-fix-agencies-form-content

- src/components/ContactPolicy/ContactPolicy.js
- src/components/shared/ShowLikeFlash/ShowLikeFlash.js
- src/components/shared/ShowLikeFlash/ShowLikeFlash.test.js
- src/utils.ts
> feat: show success message and remove it after 3 seconds

- src/components/ChangePlan/Checkout/Checkout.test.js
- src/components/ChangePlan/Checkout/ContactInformation/ContactInformation.js
- src/components/ChangePlan/Checkout/ContactInformation/ContactInformation.test.js
- src/components/ChangePlan/Checkout/Step/Step.test.js
- src/services/doppler-user-api-client.double.ts
- src/services/static-data-client.double.ts
- src/services/static-data-client.test.ts
- src/services/static-data-client.ts
Change the "Province/State" field to use "Select" instead of "Text"
**Before:**
**After:**
**Task:** [DAT-496](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-496)
> [DAT-496] - Change the "Province/State" field to use "Select"

- src/services/big-query-client.double.ts
- src/services/big-query-client.ts
Method for save data emails added on http bigquery client.
> feat(BigQuery): add saveEmailsData to big query http client
