FromDoppler/doppler-webapp

build-w-docker.sh
watch-w-docker.sh

We could use docker locally and avoid having all tools installed on our local machines. I've fixed the scripts to run on windows too.
- Fixed script build-w-docker.sh to work on windows
- Added watch script with docker
With docker running locally, in git bash:
- Build: `sh build-w-docker.sh`  
- Watch: `sh watch-w-docker.sh`

[no-ticket] docker script fixes

---

src/App.test.js
src/setupTest.js
yarn.lock

Hi @fcoronelmakingsense and team,
Sadly `setupTests.js` convention is not working.
It is in the [documentation](https://facebook.github.io/create-react-app/docs/running-tests#option-2-react-testing-library) but it does not work: we need to include the references in each file.
So, at least by the moment, I think that it is better removing it.
I have also removed a redundant dependency in `App.test.js` and apply a missing update in `yarn.lock`.

Clean tests

---

package.json

Issue:
Maybe this approach is not the best since it limits us from some routing features, see https://facebook.github.io/create-react-app/docs/deployment#serving-the-same-build-from-different-paths
> If you are not using the HTML5 pushState history API or not using client-side routing at all, it is unnecessary to specify the URL from which your app will be served.
But, by the moment, it is fine. In the future, we could update _homepage_ property as part of the build process.

Fix index.html behavior in any CDN folder

---

package.json
src/react-app-env.d.ts
tsconfig.json
yarn.lock

Hi Team, 
I have upgraded dependencies to the last ones, and also moved prettier as default dependency, fix line endings and update yarn.lock.
It will allow us to [use Hooks](https://reactjs.org/docs/hooks-intro.html)!

Upgrade dependencies to the last ones

---

package.json

In Mac was necessary to install _Watchman Homebrew package_ (`brew install watchman`), I do not know if something similar is necessary for other OS.

Npm script for run tests in watch mode

---

src/App.js
src/App.test.js
src/components/Header/Header.js
src/components/Header/HeaderUserMenu/HeaderUserMenu.js
src/services/doppler-legacy-client.doubles.ts
src/services/doppler-legacy-client.ts
src/services/session-manager.ts

Hi team,
I am moving headers data inside session object and using it in header components.
I have also refined some header components in order to use a sanitized version of _DopplerLegacy's HeaderData_ object. 
In the way, I have detected that we are not paying attention to all _HeaderData_ properties, so, I changed the mappers to map only used properties so we could detect when we need something else.
Could you review it, please?
Next steps:
* Add tests.
* [DBR-94](http://jira.makingsense.com/browse/DBR-94) - Pay attention to _HeaderData_ language to translate the App.
* [DBR-81](http://jira.makingsense.com/browse/DBR-81) - Read _HeaderData_ from backend.
* [DBR-95](http://jira.makingsense.com/browse/DBR-95) - Move more AJAX calls to doppler-legacy-client
* Add tests (more yet).

Include header data in session object

---

src/App.js
src/DopplerIntlProvider.double-with-ids-as-values.js
src/DopplerIntlProvider.js
src/DopplerIntlProvider.test.js

Hi Team, I have another little refactoring...
When I tried to introduce a test for `UpgradePlanForm.js`, I realized that I need _IntlProvider_ scope.
Talking with @mvillaseco, first, we thought about having a helper for the test, but then we understood that the same helper could be useful for all the application.
It is not a nice module, it works as a singleton, with a state, but I think that for the moment it is fine, and in the future, we could refactor it.
When we need to test independent components, we could do something like this:
```js-jsx
describe('UpgradePlanForm', () => {
it('should . . . ', () => {
const { getByText } = render(
<DopplerIntlProvider>
<UpgradePlanForm isSubscriber={true} />
</IntlProvider>);
// . . .
```

refactor(localization): encapsulate IntlProvider configuration and dependencies into a component

---

src/components/Reports/ReportsService.js
src/components/UpgradePlanForm/UpgradePlanForm.js
src/services/doppler-legacy-client.doubles.ts
src/services/doppler-legacy-client.ts
src/utils.js

Finally, I am taking advantage of the dependency inversion in the following way:
I have also added the test data to _doppler-legacy-client.doubles_, and done minor fixes as _timeout_ helper.
Could you review? (@cbernat and @fcoronelmakingsense I am looking you ;), you will need to use this)

Move UpgradePlanForm's AJAX calls to DopplerLegacyClient

---

src/components/Reports/Reports.test.js
src/components/Reports/ReportsFilters/ReportsFilters.js

Hi team, 
I do not know why the tests are passing in CI, but they started to fail in my local environment and it was because I was using Dates in _Reports.test.js_'s assertions.
I fixed that, and I saw that besides that, we were rendering a wrong date because _FormattedDate_ uses current timezone by default. 
In order to avoid this problem by the moment **we should use _timeZone_ parameter** in this way:
```
<FormattedDate value={domainSelected.verified_date} timeZone="UTC" />
``` 
I have also removed some redundant assertions.
Could you kindly review it?

Fix issues with date representation

---

package.json
src/App.test.js
src/components/Reports/Reports.js
src/components/Reports/Reports.test.js

Hi team, there was an issue with prettier configuration. It seems that globs required quotes to work fine.

Fix Prettier

---

src/App.js

Sorry team, I know that it is not so fancy, but by the moment it will be a better option than slashes.
It helps us to simplify server configuration, build, deploys and testing PRs in our CDN.

Use hash routes in place of slash ones

---

package.json
src/App.js
src/App.test.js
src/components/Login/Login.js
src/components/PrivateRoute.js
src/components/RedirectToLogin.tsx
src/index.js
src/services/pure-di.tsx
src/services/session-manager.ts
yarn.lock

Hi team, 
I am still working on it because I need to add some tests.
But, I think that, besides that, it is ready to be merged. I finally resolved how to deal with many problems:
* Public and private routes
* Two different login pages (internal one and in Legacy Doppler)
* The layout that changes based on the route, redirect
I think that it is easy to review it if you read commit by commit, maybe it is difficult to understand DI related commit because I am using our DI system to inject a React component, but I think that it is the most consistent way to do that. Let me know if you need any clarification on this.
Pending tests:

Public and private routes

---

src/components/Reports/Reports.test.js

Hi @fcoronelmakingsense, 
I cannot understand how the tests are passing in our CI environment, but there was an issue reproduced in my local environment because _ReportBox_ was trying to use a dependency that was only set for _Reports_.
This should fix the issue, what do you think?

test(reports): configure dependencies at container level for reports tests

---

public/index.html
src/App.js
src/components/Signup/Signup.js
src/components/form-helpers/form-helpers.js
src/i18n/en.json
src/i18n/es.json

Hi team,
This signup page has a lot of holes yet, but I think that it could be a nice start to continue working on related things in parallel, for example, validations, tests, backend, usability, etc.
I would really appreciate if HTML/CSS guys (@GusBaamonde, @IgnacioRodrigues, @damianmuti) take a look and give me feedback about commit _"chore: add form helpers following our conventions"_ (probably _"chore: add formik with basic validation"_ could help to understand), because I want to know if the structure makes sense to be reused.
~~You can see it working at https://cdn.fromdoppler.com/doppler-webapp/build213/#/signup~~
**UPDATE:** It is updated with the last @IgnacioRodrigues fixes and with a PasswordFieldItem component that allows show and hide the password. 
See it …

Add signup page

---

.editorconfig
.env.development
.env.int
.env.production
.env.qa
src/App.js
src/components/DatahubRequired/DatahubRequired.js
src/components/PrivateRoute.js
src/components/Reports/Reports.js
src/components/Reports/Reports.test.js
src/components/Reports/ReportsBox/ReportsBox.js
src/components/Reports/ReportsPageRanking/ReportsPageRanking.js
src/headerData.json
src/i18n/en.json
src/i18n/es.json
src/index.js
src/services/app-session.ts
src/services/datahub-client.doubles.ts
src/services/datahub-client.ts
src/services/doppler-legacy-client.doubles.ts
src/services/doppler-legacy-client.test.js
src/services/doppler-legacy-client.ts
src/services/pure-di.tsx
src/services/session-manager.ts

Hi team, 
This is again a big PR, I am really sorry.
I have refactoring a little some Reports' components to make them more friendly with the actual backend.
I have also moved AppSession outside of SessionManager to allow inject it in DatahubClient, refactored it to describe sessions with Datahub information and sessions without it, and improved _PrivateRoute_ to take this account.
There are some loose ends:
* What should we do when someone open Reports page and he does not have Datahub information?
* Deal with not verified domains (null verification date)
* Failure when domain list is empty
Could you kindly review it? (I encourage review it commit by commit)

DBR-161 Datahub client

---

src/components/ForgotPassword/ForgotPassword.js
src/components/Login/Login.js
src/components/Signup/Signup.js
src/components/UpgradePlanForm/UpgradePlanForm.js
src/components/form-helpers/form-helpers.js

Hi team, 
I forgot to apply the defined submit button behavior in Signup page and then the same happened with the rest of public pages.
These changes apply the same style with a spinner in Signup, Login and Forgot Password pages, but more important: disable the button in order to avoid multiple submits.

Unify submit buttons behavior

---

src/components/Signup/Signup.js
src/components/Signup/SignupConfirmation.js
src/i18n/en.json
src/i18n/es.json
src/services/doppler-legacy-client.doubles.ts
src/services/doppler-legacy-client.ts

Hi team,
I am adding the methods `registerUser` and `resendRegistrationEmail` to Doppler Legacy Client and also show the confirmation page after server response.
I decided to limit the resendings to only one time. If someone is clear about the desired behavior, please let me know and I can change it in this same PR; if not, we can improve it later.

Add signup methods to Doppler Legacy Client and signup confirmation page

---

public/index.html
src/components/Signup/Signup.js
src/components/form-helpers/form-helpers.js
src/i18n/en.json
src/i18n/es.json
src/services/doppler-legacy-client.doubles.ts
src/services/doppler-legacy-client.ts

Hi team, 
I applied these changes to deal with register user errors, by the moment we accept two kinds of errors:
* Email already exists
* Unexpected errors
Here you have some examples of how it works:
Duplicated email address (cached):
Unexpected error:
Fixes: DBR-174, DBR-186

Accept register user results

---

src/components/Login/Login.js

It simply shows an unexpected error message in Login when the result (of nothing by the moment) is not successful.
(Like #130 but for Login)

feat: deal with unexpected errors in Login

---

src/components/ForgotPassword/ForgotPassword.js

It simply shows an unexpected error message in Forgot Password when the result (of nothing by the moment) is not successful.

feat: deal with unexpected errors in Forgot Password

---

src/App.js
src/App.test.js
src/components/PublicRouteWithLegacyFallback.js
src/components/RedirectToExternalUrl.js
src/components/RedirectToLegacyUrl.js

When root page is open, or after login without redirect indication, the webapp will redirect to default Legacy Doppler page.
To achieve it, I created a couple of components that will be useful also in future features.

DBR-169 - Redirect to default Doppler page

---

src/App.js
src/App.test.js
src/components/PrivateRoute.js

As you know, we are polling Legacy Doppler backend to refresh session status.
We are also doing it in public pages, maybe we could avoid it, but it is not so expensive. By the moment, I decided to continue polling in public pages, but, in order to show it quickly, do not show the loading element when session status is unknown.
Caveat: suppose that your browser is configured in English, you have an open session in Spanish and you open Login page. The first rendering will be in English, and after server response with logged-in user data, it will be translated to Spanish. In my opinion, it is not so bad.

Avoid loading on unknown session status in public pages

---

src/App.js
src/components/RedirectWithQuery.js

Hi Team,
We need to redirect:
* `https://app.fromdoppler.com/#/registrate` to `https://app.fromdoppler.com/#/signup?lang=es`
* `https://app.fromdoppler.com/#/ingresa` to `https://app.fromdoppler.com/#/login?lang=es`
We are also including the rest of the parametes, and now we have a new component to RedirectWithQueryString.

DBR-187 - Redirect 'ingresa' and 'registrate' URLs to canonical ones

---

src/components/Login/Login.js

Hi team!
When we will start using the new Login page in Legacy Doppler, we will need to redirect back to Legacy Doppler.
These changes allow that, webapp will accept something like this: `https://app.fromdoppler.com/#/login?redirect=/Templates/Main/` and after successful login, we will redirect to: `https://app2.fromdoppler.com/Templates/Main/`.

feat: allow redirect to legacy URL after login

---

src/components/form-helpers/form-helpers.js

Hi team!
I think that this change is enough to fix our issue when the user closes the captcha challenge window.
Button state is not submitting for a little time, but it does not care: if the user clicks the button two times the captcha callback will be resolved only one time.

DBR-206 - fix: avoid dead-end when user closes captcha challenge window

---

public/index.html
src/components/ForgotPassword/ForgotPassword.js
src/components/Login/Login.js
src/components/Signup/Signup.js
src/components/form-helpers/form-helpers.js

Hi team (including @santiagopaolucci!)
With the help of @GusBaamonde, I have refactored error messages in order to make them more flexible, see this example:
Now (based on https://github.com/FromDoppler/Doppler-UI-System/pull/94), both _field error messages_ and _general form error messages_ follow the same rules and both accept a resource key or a React component.
Could you take a look?

Error messages refactor

---

src/components/ForgotPassword/ForgotPassword.js
src/components/Login/Login.js
src/components/Signup/Signup.js
src/components/Signup/SignupConfirmation.js
src/components/form-helpers/form-helpers.css
src/components/form-helpers/form-helpers.js
src/i18n/en.json
src/i18n/es.json

Hi team, and mainly @carodipietro, @santiagopaolucci and @GusBaamonde,
I added _reCaptcha_ legal messages in all public pages using a consistent style (based on copyright message in the same pages).
Maybe it is not the best option, but it is the best that I could do without changing the current layout and styles.
Please, let me know if there is a relatively simple improvement. If improve it will take time, I am going to merge (because I need adding the legal messages), but feel free to work on that, and let me know later.
I did not touch contents, only moving them from _signup_ section to _common_ section.
Could you kindly review?

fix: normalize recaptcha legals in all public pages

---

public/index.html
public/zoho-chat.css
public/zoho-chat.js

Add zoho chat, as it is in doppler and sites. 
Changed font handling, and renamed some variables. 
https://cdn.fromdoppler.com/doppler-webapp/int-build521/#/signup

chore: add zoho chat in spanish only

---

public/index.html
src/App.js
src/App.test.js
src/components/PrivateRoute.js
src/components/Reports/Reports.js
src/components/SiteTrackingRequired/SiteTrackingRequired.js
src/headerData.json
src/i18n/en.json
src/i18n/es.json
src/services/datahub-client.doubles.ts
src/services/doppler-legacy-client.doubles.ts
src/services/doppler-legacy-client.ts

Hi team, 
I am reading the backend features exposed by https://github.com/MakingSense/Doppler/pull/5936 and also unified the management of all these states in a single component.
```
Trial no activo y C.Free |----> Mensaje con link a comprar          
Trial no activo y C.Paga |----> Mensaje con opción de activar Trial 
No tiene datahubId |                                          
|      Mensaje con ayuda para activar la   
Desactivó la feature |----> feature, agregar dominios, etc y    
|      link a sección del panel de control 
No tiene dominios |                                          
```
Tomorrow I will add screenshot with the instructions to reproduce the scenarios with local configuration.

DBR-220 - Site tracking user data

---

src/validations.test.js
src/validations.ts

Hi team, 
I found that the last changes in email validation do not allow emails with only a letter before @, I fixed that and added some tests.
CC: @CarlosSampedro, maybe you could think in other scenarios.
CC: @lucianaDilizio, if I am not wrong, you have applied the previous change in another place, you should consider also apply this one.

fix: fix email validation

---

package.json
src/App.test.js
src/components/Footer/Footer.js
src/components/Footer/Footer.test.js
src/components/ForgotPassword/ForgotPassword.js
src/components/Login/Login.js
src/components/Signup/Signup.js
src/components/Signup/SignupConfirmation.js
src/i18n/FormattedMessageMarkdown.css
src/i18n/FormattedMessageMarkdown.js
src/i18n/en.json
src/i18n/es.json
yarn.lock

Hi Team,
Sorry, I could not contain myself and I have added this PR, only for love.
The idea is accepting nice and safe markdown content in place of ugly and insecure HTML content.
The next step is finding a way to define the content (or part of it) without using this ugly JSON, maybe using independent files for entries or using yml.
Could you review it? 
@GusBaamonde, in the future we should do something with `<p>` styles, they do not make honor to parent element styles!

Support markdown content

---

src/components/Login/Login.js
src/components/Login/LoginErrorCancelatedAccount.js
src/i18n/en.json
src/i18n/es.json
src/services/doppler-legacy-client.doubles.ts
src/services/doppler-legacy-client.ts

- Catch blocked account for invalid pass error
- Catch invalid login (common error)
- Delete unnecessary module for HTML formated text.
- Fix _**contact us**_ link in spanish
For test: https://cdn.fromdoppler.com/doppler-webapp/int-build597/#/login

feat: deal with blocked account and invalid login

---

src/components/Login/Login.js
src/services/doppler-legacy-client.doubles.ts
src/services/doppler-legacy-client.ts

For some integrations in Doppler (Tienda Nube and Mercadoshops ), we have to allow login and redirect to continue. 
https://cdn.fromdoppler.com/doppler-webapp/int-build596/#/login

chore: add BE redirect url handling

---

src/components/Reports/ReportsPageRanking/ReportsPageRanking.js
src/services/datahub-client.doubles.ts
src/services/datahub-client.ts

Hi team, 
I am fixing the link in Page Ranking box:
CC: @leoslopez

fix: link to (almost) right URL in Page Ranking

---

public/zoho-chat.css

We won by specificity and eliminated the ::after where the arrow shows, and placed the arrow in the ::before of the box, allowing it to grow and always show.
Look at @andresmoschini @cbernat @silsanchez8 :) what do you think?

feat: improvement of the zoho chat

---

src/App.js
src/components/PublicRouteWithLegacyFallback.js

Add redirects for forgot password as follow:
- English: https://app.fromdoppler.com/#/login/reset-password
- Spanish: https://app.fromdoppler.com/#/ingresa/cambiar-clave
Reviewed this with @carodipietro 
Issue: DBR-266
https://cdn.fromdoppler.com/doppler-webapp/int-build622/#/login/reset-password
https://cdn.fromdoppler.com/doppler-webapp/int-build622/#/ingresa/cambiar-clave

chore: add redirect for forgot password in spanish 

---

public/index.html
src/App.test.js
src/components/Loading/Loading.js

Hi Team,
@CarlosSampedro detected that the loading component's message is in the wrong language for some time.
I knew about that issue, but it seems not important to me, I think that the user has no issue with that word, but it seems that it is not comfortable for some users.
So, since it is not possible knowing the user language early in an elegant and always effective way, I have chosen directly remove the text.
What do you think?

DBR-257 - Remove "loading" word from page loading element

---

public/index.html
src/components/ForgotPassword/ForgotPassword.js
src/components/Login/Login.js
src/components/Signup/Signup.js
src/i18n/en.js
src/i18n/es.js

**Add link to the logo with url by language
It was added in:** 
- Signup (ES/EN)
- Login (ES/EN)
- Forgot Password (ES/EN)

feat: add link to the logo with url by language

---

src/components/ForgotPassword/ForgotPassword.js
src/components/Login/Login.js
src/components/Signup/Signup.js
src/components/UpgradePlanForm/UpgradePlanForm.js

In some places, for example https://davidwalsh.name/react-autofocus, they say that _autoFocus_ is not enough.
However, in some places, for example https://stackoverflow.com/questions/42324423/autofocus-an-input-element-in-react-js#42324485
other said that _autoFocus_ should work.
By the moment, it is working, we can improve it in the future, for example scanning autoFocus fields in FormWithCaptcha or other places.
You could test the build in:
* https://cdn.fromdoppler.com/doppler-webapp/int-build675/#/login
* https://cdn.fromdoppler.com/doppler-webapp/qa-build675/#/login
* https://cdn.fromdoppler.com/doppler-webapp/build675/#/login

feat: add autoFocus property to first field on each form

---

src/components/form-helpers/form-helpers.js

Hi team, 
By the moment, I simply disabled tab stop for password visibility toggle button. 
In the future we could move the tab stop after the input, as Google does:
Thoughts?

feat: do not stop in toggle password visibility icon

---

public/index.html

Bumped library version based on a fix there. 
Currently `<p>` tags have a default line-height value of 22px. Based on my fix, the idea would be to have a dynamic unitless line height value that is proportional to the default line height for 15px of font-size.
NOTE: I've tested this change, and despite of visually changing line heights, I guess it's much better to have a proportional ratio for font-sizes to improve legibility.

fix: issues with line-height and font declaration specificity

---

src/i18n/en.js

@carodipietro noticed that we had a typo in Attract word.
It should fix the issue.

fix: typo in Attract

---

public/index.html

Hi Team, 
This is the counterpart of https://github.com/FromDoppler/Doppler-UI-System/pull/110
From now on, we should start using this kind of version numbers in place of build number. It will improve the traceability, library self-description, and less error-prone code reviews.

chore: start using official UI Library versions

---

src/components/form-helpers/form-helpers.css

Pretty much as the title describes, as per @santiagopaolucci 's request, reCaptcha links color should be the same as the text's default.

fix: recaptcha links should be colored as default text

---

public/index.html
src/components/Loading/Loading.js
src/components/Reports/Reports.js
src/components/Reports/ReportsPageRanking/ReportsPageRanking.js

- Fix spinner in reports page when filter for domains, pages or period
- Use <Loading> component

fix: reports ranking spinner

---

src/App.css
src/components/PublicRouteWithLegacyFallback.js

- Remove zoho help bubble in private pages. only show in public pages
- Cant use ref to access to DOM because the element is create by zoho widget. I dont know if exist a better solution for this case because dont have control for js widget.

fix: remove zoho bubble in private pages

---

public/index.html
public/zoho-chat.css

- Add mediaqueries to adjust zoho chat in mobile
- Move zoho-chat stylesheet to avoid problems with own zoho's styles

feat: adjust zoho chat for mobile

---

.dockerignore

It seems that we were copying all the files (including `node_modules`) to the container that generates the build, so, we were including unnecessary and probably wrong files.
Could you verify and let me know if do you think that other files could be ignored?
(I will merge it soon, but we can improve it later anyway)

fix: add .dockerignore file

---

src/App.js
src/components/Header/Header.js
src/components/Header/HeaderNav/HeaderNav.js
src/components/Integrations/Shopify/Shopify.js
src/components/Integrations/Shopify/Shopify.test.js
src/components/PrivateRoute.js
src/doppler-types.ts
src/index.js
src/services/doppler-legacy-client.ts
src/services/pure-di.tsx
src/services/shopify-client.doubles.ts
src/services/shopify-client.ts

Shopify section:
- Add Shopify client and shopify hardcoded client
- Add tests
- Add view with title only, access via /#/integrations/shopify
- Add header without section
https://cdn.fromdoppler.com/doppler-webapp/build883/#/integrations/shopify

Shopify: manage connected/disconnected states

---

src/components/shared/Promotions/Promotions.js

https://makingsense.slack.com/archives/CGJ72QFQX/p1561667402133100?thread_ts=1561662983.122200&cid=CGJ72QFQX
> irodrigues  [9 minutes ago]
> @fcoronel esta bien que la fuente sea negra https://app.fromdoppler.com/#/signup ?
before: https://cdn.fromdoppler.com/doppler-webapp/build936/#/login
after: https://cdn.fromdoppler.com/doppler-webapp/build937/#/login

fix: Promotions default color

---

public/manifest.json

Remplace name in manifest.json for Doppler.

Change the default name in manifest for Doppler

---

public/index.html
src/components/Header/Header.js
src/headerData-for-client-manager-user.json

- Add fixes for client manager when inactive section, so logo can be seen in shopify
- Also add client manager user json, for quick testing
Related to https://github.com/FromDoppler/Doppler-UI-System/pull/129
https://cdn.fromdoppler.com/doppler-webapp/build942/#/integrations/shopify

Dbr 341 header fixes

---

src/components/Reports/ReportsPageRanking/ReportsPageRanking.js

fix: remove description in reports pages ranking

---

src/index.js

For Google Analytics and Doppler Datahub, add track for first load. To avoid tracking of root --> /.

fix: add navigation tracking on first load

---

package.json
public/index.html
src/index.js
src/utils.js
src/utils.test.js
yarn.lock

- Add datahub script as suggested in https://github.com/MakingSense/Customer-Data-Hub/pull/368
- Added `url-parse` library
- Refactor parse into utils
- Add tests
Pending to do in another PR by @andresmoschini and @fcoronelmakingsense : 
To replace queryString library in the future take in account this example:
`queryString.parse(props.location.search)` --> `urlParse(props.location.search, true)`
http://cdn.fromdoppler.com/doppler-webapp/build1053/#/integrations/shopify

feat: allow custom tracking for datahub

---

src/components/Integrations/Shopify/Shopify.js
src/i18n/en.js
src/i18n/es.js

- Fix disconnected warning as in confluence text
- Fix open external urls in a new tab
http://cdn.fromdoppler.com/doppler-webapp/build1122/#/integrations/shopify

Shopify fixes

---

src/components/Integrations/Shopify/Shopify.js

- `button-medium` is for 95% of user actions.
- `button-big` is for promotional uses (as the case may be)
- `button-small` is for very specific cases (as the case may be)

fix: change shopify button sizes

---

src/components/Integrations/Shopify/Shopify.js

Added redirect to control panel for back button when there is an error.
http://cdn.fromdoppler.com/doppler-webapp/build1147/#/integrations/shopify

fix(shopify): fix back button redirect when error

---

src/components/SiteTrackingRequired/SiteTrackingRequired.js
src/components/SiteTrackingRequired/SiteTrackingRequired.test.js
src/services/doppler-legacy-client.doubles.ts
src/services/doppler-legacy-client.ts

- Add redirect to `ControlPanel/CampaignsPreferences/SiteTrackingSettings` when activated site tracking trial
- Refactor method to manage errors

feat(site tracking trial): add redirect ctrl panel when activated

---

src/components/Integrations/Shopify/Shopify.js
src/services/shopify-client.test.ts
src/services/shopify-client.ts
src/utils.ts

When state changes, react component is re rendered, in this case we are using polling to keep data up to date, and sometimes we received the same data.
- Added new feature in Utils,  `ResponseCache` to allow to cache responses when etag header is exposed. 
- Used this feature in shopify client
- Refactor shopify component to prevent re setting state when not needed.
- Fixed tests
https://cdn.fromdoppler.com/doppler-webapp/build1501/#/integrations/shopify

fix(shopify): prevent re render when data does not change

---

Dockerfile.BUILDS_AND_CDN
build-n-publish.sh

- Add docker file for builds.
- Use dockerfile from build-n-publish script
Output: cdn folder as we used (except for development enviroment)
* production --> buildxxx (https://cdn.fromdoppler.com/doppler-webapp/build15323/#/login)
* int --> int-buildxxx (https://cdn.fromdoppler.com/doppler-webapp/int-build1532/#/login)
* qa --> qa-buildxxx --> (https://cdn.fromdoppler.com/doppler-webapp/qa-build1532/#/login)
* development --> development-buildxxx (before it was dev-buildxxx) (https://cdn.fromdoppler.com/doppler-webapp/development-build1532/#/login)

feat: allow build within docker container

---

src/components/Reports/ReportsDailyVisits/ReportsDailyVisits.js
src/components/shared/C3Chart/C3Chart.styles.js
src/i18n/en.js
src/i18n/es.js
src/services/datahub-client.doubles.ts
src/services/datahub-client.ts

Report daily visit graphic without datahub new data, and with classification for email and no email. 
- Add with emails in datahub double
- Add values into graphic
- Hide graph for with Email and without
- Fine tune format for value to show a label for each case

Daily visits withemail without

---

src/components/Integrations/Shopify/Shopify.js
src/components/Integrations/Shopify/Shopify.test.js
src/i18n/en.js
src/i18n/es.js
src/services/doppler-api-client.test.ts
src/services/doppler-api-client.ts
src/services/pure-di.tsx

When jwtToken is ready for api, experimental feature will not be needed anymore, and in shopify we will always get amount of subscribers by dopplerApi.

Shopify: remove experimental feature set up

---

src/components/Reports/ReportsDailyVisits/ReportsDailyVisits.js
src/components/shared/C3Chart/C3Chart.styles.js

Every time a new `key` is added (example: `witoutEmail`), c3 automatically generates a `class` with the new `key` (example: `c3-target-witoutEmail`) to which we will have to add the corresponding color of the data we want to paint.
The code example is in the image.
Design adjustments were made for a better visualization of the grouped data.
Design validated with @santiagopaolucci 
**Linear graph example**
**Example area chart**
**Example code**

fix: chart adjustment of reports daily visits

---

src/services/datahub-client.doubles.ts
src/services/datahub-client.test.ts
src/services/datahub-client.ts

- Refactor method to can add pagination. Add page size and page number
- Add test for Ranking pages by period
- Refactor double for local

feat(datahub-client): refactor to add pagination in page ranking

---

src/components/Reports/Reports.js
src/components/Reports/ReportsDailyVisits/ReportsDailyVisits.js
src/components/Reports/ReportsHoursVisits/ReportsHoursVisits.js
src/services/datahub-client.doubles.ts
src/services/datahub-client.test.ts
src/services/datahub-client.ts
src/utils.ts

Add explicitly endDate, to avoid getting some extra minutes in datahub. 
**Now:**
**Request:**
**In prod we can see the difference **
**Request:**
https://cdn.fromdoppler.com/doppler-webapp/build1705/#/reports
Issue: DW-79

DW-79: add endDate for daily/hourly visits reports

---

Dockerfile.RELEASES

Fix release error see http://104.131.79.81:8080/job/doppler-webapp/job/publish-releases/197/console
```
Step 25/35 : COPY conf/site${environment}.conf /etc/nginx/conf.d/site.conf
COPY failed: stat /var/lib/docker/tmp/docker-builder038373511/conf/site.conf: no such file or directory
```
Add environment as arg before copy to fix this issue.
Issue: DW-84

fix(deploy): add enviroment arg to use in copy

---

src/components/Reports/Reports.js

Fix this:
Notice that the month is wrong. More details: https://makingsense.slack.com/archives/CGJ72QFQX/p1572470224155300
I will merge without review.

fix: return the right month in getStartOfDate

---

.dockerignore
Dockerfile.swarm
Jenkinsfile
build-n-publish-release-w-docker.sh
conf/site-swarm.conf

Hi team, 
I am working on a simplified CI flow that also generates the right images with the right tags for our new [FromDoppler Docker Hub Organization](https://hub.docker.com/orgs/fromdoppler).
~~It is not ready to be merged, but I want to start testing the process.~~
Well, I think that it is enough ready to be merged.
This does simple steps in each PR, commit, etc:
* Restore
* Test
* Build (with production parameters)
Then, when a tag is detected, it should:
* Build images for demo and production environments, including _version.txt_ file with a content like this: `production-v1.57.3+4f195f865aa57e782913346dd54bee748dd28755`
* Upload those images to docker hub
Pending:
* Test if tag detection is working fine (I cannot test it without merging)
* Assign the right tag to final versions, …

New CI process for our swarm

---

Jenkinsfile
publish-commit-image-to-dockerhub.sh

With this change, I am trying to add the right tags to final version images, for example:
* `docker tag fromdoppler/doppler-webapp:production-commit-94f85efb9c3689f409104ef7cde6813652ca59fb fromdoppler/doppler-webapp:production`
* `docker tag fromdoppler/doppler-webapp:production-commit-94f85efb9c3689f409104ef7cde6813652ca59fb fromdoppler/doppler-webapp:production-v12`
* `docker tag fromdoppler/doppler-webapp:production-commit-94f85efb9c3689f409104ef7cde6813652ca59fb fromdoppler/doppler-webapp:production-v12.34`
* `docker tag fromdoppler/doppler-webapp:production-commit-94f85efb9c3689f409104ef7cde6813652ca59fb fromdoppler/doppler-webapp:production-v12.34.5`
* `docker tag fromdoppler/doppler-webapp:production-commit-94f85efb9c3689f409104ef7cde6813652ca59fb …

fix(build): publish final images to docker hub with the right tags

---

package.json
yarn.lock

Some of the lengthy console warning that we are getting in tests log, are from third party libraries that we use, that haven't updated ther dependencies, this is why yarn allows a configuration in `package.json` we could update dependencies for a particular library. This obviously is temporal. https://yarnpkg.com/lang/en/docs/selective-version-resolutions/  
In tests for: shopify.test ,signup.test, Reports.test, App.test
```
● Console
console.warn node_modules/react-dom/cjs/react-dom.development.js:12338
Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to …
```

fix(test): remove warning for side effect null in react dom

---

build-n-publish-release-w-docker.sh

I am trying to mitigate this problem:

fix(build): move login to our old docker account just before pushing

---

src/components/Reports/ReportsPageRanking/ReportsPageRanking.test.js

- Remove the test to check page ranking without pages because we already have a test to test this scenario.
- When remove this fix 1 'act' warning 💃

fix(ReportsPageRanking.test): remove test because duplicated

---

public/index.html
src/components/Reports/ReportsBox/ReportsBox.js

Related to: https://github.com/FromDoppler/Doppler-UI-System/pull/207

fix: add error in box shadow

---

Jenkinsfile

Added condition in jenkins pipeline, to prevent automatic build. 
If we would want to make a rebuild, we need to wait by blue view to accept the build (because it will timeout in 60 seconds window)
Else it will fail by timeout.

Dw-117 jenkins pipeline conditional build for dependabot 

---

src/headerData.json

- Because local when the browser is spanish in public pages change to english because the user has setting english language

chore(App): change default language to spanish

---

src/doppler-types.ts
src/services/doppler-legacy-client.doubles.ts
src/services/doppler-legacy-client.ts

Logging unexpected errors we found some weird wrongCaptcha error, that needed more data to be understanded. Why? because it's nearly impossible to reproduce, the captcha does not allow to send a wrong captcha to BE and the message is sent from BE. 
In loggly:
Message from BE in doppler --> https://github.com/MakingSense/Doppler/blob/develop/Doppler.Presentation.MVC/Controllers/WebAppPublicController.cs#L312
- trace from FE
- full response from service call

feat(log): add trace and fullResponse in unexpected error to be logged

---

src/components/Login/Login.js
src/components/Login/Login.test.js
src/services/doppler-legacy-client.doubles.ts
src/services/doppler-legacy-client.ts

Add message for login maximum attempts reached, instead of unexpected error message. 
Issue: DW-157

feat(login): map max attemps error into message

---

src/services/doppler-legacy-client.ts

Add map for max login attempts in service that was missing.
In loggly console it was still showing the error:

fix(login): map max login attempts in service

---

src/services/doppler-sites-client.ts

Fix mapping when get banner data from doppler page

fix(doppler-sites-client): get banner map data

---

src/i18n/en.js
src/i18n/es.js

If user has ad blocker enabled, the log does not work. So added a warning in error message.

chore: invalid message warning remove ad blocker

---

src/utils.ts

Add more domains to whitelist for testing if needed for bapro enviroment, and other doppler enviroments, to allow use of redirect as we do in academy.

feat: DW-188-login-bapro

---

src/components/Reports/ReportsFilters/ReportsFilters.js

Removed 2 weeks and 3 weeks options just for now.

DW-195: fix: remove some time filters for now

---

src/components/Reports/SubscriberHistory/SubscriberHistory.js
src/utils.test.js

- the problem is when have and email with `+` the parser convert this in space and dont works. but if we encode the sign `+` works fine

fix(utils): parse email with + sign

---

src/components/Reports/Reports.js

Set default time filter in reports page to today to mitigate datahub performance issue.

feat: DW-202 set default filter to today temporarily

---

src/components/Login/Login.js
src/i18n/en.js
src/i18n/es.js
src/services/doppler-legacy-client.doubles.ts
src/services/doppler-legacy-client.ts

When captcha fails in back end, the error is displayed in the logs, but we are not warning de user about this kind of error, and we do not know what migth be triggering it. 
Informing the user can help us if he/she contacts support. They can provide with steps to reproduce this issue.

DW-158:feat: capture wrong captcha error from BE

---

conf/site-int.conf
conf/site-production.conf
conf/site-qa.conf

This PR is for change the site config to force only accept TLSv1.2 in the web app.
The SSL Lab test right: https://www.ssllabs.com/ssltest/analyze.html?d=app.fromdoppler.com
and should be the same as https://www.ssllabs.com/ssltest/analyze.html?d=app2.fromdoppler.com
this change should solve this problem

fix: set nginx config to only use TLSv1.2

---

public/index.html
src/App.js
src/components/Reports/GDPR/SubscriberGdpr.js
src/components/Reports/GDPR/SubscriberGdpr.test.js
src/components/Reports/SubscriberHistory/SubscriberHistory.js
src/i18n/en.js
src/i18n/es.js
src/services/doppler-api-client.double.ts
src/services/doppler-api-client.ts
src/utils.ts

Add Gdpr permission fields and consent field with its value for a selected Subscriber.
This report will be corner stone for later implementation of a permission's historial listing.
- Add double with data for permission fields
- Add component for report
- Add route
- Add tests 
link for testing https://cdn.fromdoppler.com/doppler-webapp/int-build2188/#/reports/subscriber-gdpr?email=cbernat+c56@getcs.com

Dw-155: gdpr list by subscriber

---

public/index.html
src/components/Header/Header.js
src/components/Reports/GDPR/SubscriberGdpr.js
src/components/Reports/GDPR/SubscriberGdpr.test.js
src/i18n/en.js
src/i18n/es.js
src/services/doppler-api-client.double.ts
src/services/doppler-api-client.test.ts
src/services/doppler-api-client.ts

Now we show all fields for the user, and when de subscriber never agreed nor rejected the permission we show a no response label. Showing all permissions here also allows a user to see the legal text (this cannot be seen if the permission is in use by at least one subscriber)
http://localhost:3000/reports/subscriber-gdpr?email=cbernat@makingsense.com
https://cdn.fromdoppler.com/doppler-webapp/build2205/#/reports/subscriber-gdpr?email=cbernat@makingsense.com

Dw-216 gdpr report with all permission fields for doppler user

---

src/services/doppler-sites-client.ts

- Change request in doppler sites from `fromdoppler.com` to `fromdoppler.com/es` to fix the CORS problem

fix(Promotions): change fromdoppler to fromdoppler/es

---

src/components/Login/Login.js

- When has `redirect=https://doppleracademy.com` in the url call `getBanner` with the `page=doppler-academy` parameter

fix(Login): check redirect parameter behaviour like page parameter

---

verify-n-generate-release-w-docker.sh

In order to avoid issues with jenkins workspace better try to run this into a docker container. Mapping .git folder seems to do the trick.
This approach then can be done in ui library as well. 😄

fix(semanitc-release): fix script to build inside container

---

src/validations.ts

- We had problem in login and signup with the validation email. When put long text and validate with the actual regex the screen is frozen. I update the email regex with new one obtain in the Yup library its for validations too and is common use with formik.
https://github.com/jquense/yup/search?q=rEmail&unscoped_q=rEmail

fix(validations): email regex bucle problem

---

src/components/shared/Promotions/Promotions.js

- check the parameter page before do the request to de doppler sites to prevent many request.

fix(Promotions): don't call the api when page is null

---

src/services/doppler-legacy-client.ts

- Add retry to signup page and forgot password. 
- Refactor to general functionality to add more urls in the future if we need more.

fix(LoginPages): add retry in forgot password and signup

---

src/services/ipinfo-client.test.ts
src/services/ipinfo-client.ts

It wasn't working because I was using http instead https to call ipinfo.io API.

Fix https issue with ipinfo.io

---

src/components/Reports/ReportsFilters/ReportsFilters.js
src/components/Reports/ReportsFilters/ReportsFilters.test.js
src/components/Reports/ReportsNew.js
src/components/Reports/ReportsNew.test.js

- Add filters in the new reports page.
- Add the posibility to select 2 or 3 weeks in the new reports page.

feat(ReportsNew): add domains and date filters

---

src/utils.ts

- Add in white list the `https://qa.doppleracademy.com` url

fix(DopplerAcademy): add qa environment in whitelist

---

.env.development
.env.int
.env.production
.env.qa
README.md
src/components/Offline/Offline.js
src/index.js

This needs better thinking, but I think we should make something out of this. Or research an offline plugin for react. 
The only issue here is that we have zoho chat outside O_o 
https://cdn.fromdoppler.com/doppler-webapp/build2378/#/login--> disabled
https://cdn.fromdoppler.com/doppler-webapp/int-build2378/#/login --> enabled for int only

DW-350: Offline setup

---

src/App.js
src/components/NewFeatures/NewFeatures.js
src/components/Offline/Offline.js

- Added offline page to be accesible via url, in `/offline`
- Added link into new features page
- Fixed classes in offline page that were seen as warnings in console ( class by className, style properties without middle dash: `padding-bottom` changed by `paddingBottom`. 
- Added white background to avoid spinner showing 
- Remove `Campañas parcialmente enviadas` since it's already in production.
https://cdn.fromdoppler.com/doppler-webapp/demo-build2386/#/new-features
https://cdn.fromdoppler.com/doppler-webapp/demo-build2386/#/offline
https://cdn.fromdoppler.com/doppler-webapp/build2386/#/offline

Offline link

---

Dockerfile.BUILDS_AND_CDN
Dockerfile.RELEASES
build-n-publish-release-w-docker.sh
build-n-publish.sh

Add upload to new cdn hosted in `108.166.10.14` to be mapped onto domain `cdn.fromdoppler.com`, to test the map this ip into the domain on host file in windows.
https://cdn.fromdoppler.com/doppler-webapp/build2433/#/login --> working for akamai and new cdn. 
- Add upload for each PR
- Add upload for release

DW-362: chore: add upload to new cdn

---

src/components/Reports/GDPR/SubscriberGdpr.js
src/components/Reports/SubscriberHistory/SubscriberHistory.js

Move Loading element to allow react render better while page is loading. 
To do: 
https://cdn.fromdoppler.com/doppler-webapp/demo-build2452/#/reports/subscriber-history
https://cdn.fromdoppler.com/doppler-webapp/demo-build2452/#/reports/subscriber-gdpr

feat: move Loading element

---

conf/site-local.conf
conf/site-swarm.conf
request-testing.http

We had an issue in production with coudflare strong caching of non static resources like html, but the rule `Origin Cache Control: On` allows to do the caching according to the headers sent by our servers. We didn´t have any headers set, now we will.
For all resources outside static:
For static requests:
- headers on local conf
- headers on swarm production conf
- some testing links that may be used later also

DW-421: set cache headers in nginx

---

src/App.js

Fix issue with subscriber pages redirection.
It was redirecting all URL's like: /reports/XXXX-XXXXX
Now it will redirec only: /reports/subscriber-XXXXX
http://cdn.fromdoppler.com/doppler-webapp/build2536/#/reports/partials-campaigns

fix: change regex for subscriber sections

---

build-n-publish-release-w-docker.sh

Remove old image hosted in @swidzinskiMS 's account. 
Right now we are using `fromdoppler` repository in swarm, this is not needed.
Also this change will make deploy faster!

fix: remove unneccesary image from release script

---

src/components/NewFeatures/NewFeatures.js

It updates plan-calculator url in new-features page.
Also, a margin was added to separate the content box from the footer.

fix: update plan calculator url

---

src/services/doppler-legacy-client.doubles.ts
src/services/doppler-legacy-client.ts
src/services/doppler-plan-client.test.js
src/services/doppler-plan-client.ts
src/services/pure-di.tsx

- Add call to get all raw data in doppler legacy client
- Add service to cache the request and admin petitions:
* get featured plan: get a standard plan data and it´s correspondant in plus and pro based on amount of emails or subscribers
* get plans filtered by type for slider: can get all standard high volume, or all plus high volume, or all plus, here we have two parameters plan type: (free | standard | plus | pro | enterprise), user type: usual user types we have in doppler.

DW-452 add Doppler plan service

---

src/components/Reports/SubscriberSentCampaigns/SubscriberSentCampaigns.js
src/services/doppler-api-client.double.ts
src/services/doppler-api-client.test.ts
src/services/doppler-api-client.ts

Fix issue in subscriber sent campaigns report when the campaign is sending right now and the campaing don't have reports yet.
To fix this, when a user clicks in a campaign that it is sending now, it will be linked to partial-campaigns url.

fix: link to partials-campaigns when sending now

---

public/index.html

Added versioning for js file in ui library for webapp
Replaced old v3.38.0 for current version.

fix: replace version for ui library js script

---

conf/site-local.conf
conf/site-swarm.conf
request-testing.http

To prevent that webapp could be rendered inside an iframe, added x-frame-options header in deny option.

fix(security): prevent clickjacking header

---

src/components/ChangePlan/ChangePlan.js

If the card is showing current plan, it has not to show the legend "since".

fix(ChangePlan): do not show "since" always when current plan

---

src/components/ChangePlan/PlanCalculator.js

Fix issue when the user reach the top of subscribers plans. To avoid problems, the Plan Calculator screen will show the plan type passed by param or the first one in the list of available plan types if the one passed by param does not exist.

fix(PlanCalculator): select existed plan or first one

---

src/components/InvoicesList/InvoicesList.js

Added two fixed decimals to the number columns:
**Changes:**
- Added two fixed decimals for the column: **Amount**, **Paid** and **Balance**
**Task:** [DAT-169](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-169)

feat(invoices): add two fixed decimals to the Amount, Paid and Balance columns

---

src/components/InvoicesList/InvoicesList.js
src/components/shared/Breadcrumb/Breadcrumb.js
src/components/shared/Breadcrumb/Breadcrumb.test.js

The breadcrumb was created as a component into the invoices list:
**Task:** [DAT-176](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-176)

feat(invoices): refactor breadcrumb

---

src/components/ChangePlan/PlanCalculator.js
src/components/ChangePlan/PlanCalculator.test.js
src/components/shared/Slider/Slider.test.js

- Remove unnecessary dependencies. 
- Fix tests errors in Slider tests for unknown intl ids.
**Tests:**
- Check that tabs are showed
- Check that a message is showed when user reach the max plan in the slider
- Check that the message before is not showed in the oposite case
- Check that the discount element is showed if the first plan of the type has discounts to apply
- Check that the discount element is not showed if the first plan of the type doesn't have discounts to apply
- Check that a message is showed when the discount is applied
- Check that a is no showing any message if the price doesn't have applied any discount
- Check that plan price is showed with a discount if applies 
- Check that the slider element is showed
- Check that an error is showed when there is no plans to …

Dw 536 plan calculator tests

---

src/components/DopplerPlus/AgenciesForm.test.js
src/components/Login/LoginErrorAccountNotValidated.js
src/components/Signup/SignupConfirmation.js
src/components/form-helpers/captcha-utils.tsx
src/components/form-helpers/form-helpers.js
src/services/pure-di.tsx

Modify captcha utils to be used as a service that must be injected. This allows to harcode the service in tests. 
```
..............
..............
describe('AgenciesForm component', () => {
afterEach(cleanup);
const dependencies = {
captchaUtilsService: {
useCaptcha: () => {
const Captcha = () => null;
const verifyCaptcha = async () => {
return { success: true, captchaResponseToken: 'hardcodedResponseToken' };
};
const recaptchaRef = null;
return [Captcha, verifyCaptcha, recaptchaRef];
},
},
};
..............
..............
```

fix: prepare reCaptcha for tests

---

src/components/Login/Login.js
src/i18n/en.js
src/i18n/es.js

When user gets to forgot password screen, token has been removed and cached into server, so if user refresh the screen, the session data for password reset has been removed. Then this message it's shown.
Functionality for this in https://github.com/MakingSense/Doppler/pull/7488

feat(login): add a new message for forgot Login

---

src/components/Login/Login.js
src/i18n/en.js
src/i18n/es.js
src/services/doppler-legacy-client.doubles.ts
src/services/doppler-legacy-client.ts

The client manager can have its users disabled, then if the user access into login, we were displaying a blocked account by invalid password. Now it shows the correct message and contact information for that client manager that disabled the user.
Tasks:
- Captured new error code for cm disabled user
- Captured exception message new field
- Separated exception code from message with client manager data
Issue in jira: DW-515

feat(login): add client manager disabled user message

---

src/components/Signup/Signup.js
src/i18n/en.js
src/i18n/es.js

- Add contact to support link only for signup unexpected error.

DW-617: fix: set separate unexpected error for signup only

---

src/services/doppler-legacy-client.ts

After post to login or signup we have a retry policy, but all attempts were made within the same second, spacing seems to be a good idea.
Before we had 200 ms fixed in retry, so for each retry:
1st retry: wait 200ms
2nd retry: wait 400ms
3rd retry: wait 600ms 
With this change:
1st: 700ms
2nd: 1.4s
3rd: 2.1s
@andresmoschini how do you feel this?

fix(retry): DW-616 space a bit more between retries

---

src/components/Signup/Signup.js
src/services/doppler-legacy-client.ts

In signup when confirmation email fails, the server returns anoter fail code that was not listed in webapp.
https://github.com/MakingSense/Doppler/blob/9a9dba9dd2e5558599c6116f2acc7b6432974fbe/Doppler.Presentation.MVC/Controllers/WebAppPublicController.cs#L259
We show for now, invalid domain message for this case, and log an entry with email just in case.
```
{
"account":"cbernat+testsending2@makingsense.com",
"origin":"http://localhost:3000",
"section":"Signup",
"browser":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36",
"message":"Confirmation email send failed"
}
```

DW-713: confirmation email sent error

---

src/components/Login/Login.js
src/services/session-manager.ts
src/utils.test.js
src/utils.ts

- Stop login timeout error for accounts not registered (this can happen in login and does not affect anyone)
- Set all error message description as message, to avoid having all sorts of confusing fields in log

Loggly log cleaning

---

conf/site-swarm.conf

Disables emitting nginx version on error pages and in the “Server” response header field.
Actually:
http://nginx.org/en/docs/http/ngx_http_core_module.html#server_tokens

fix(security): disable nginx emmiting version

---

src/services/doppler-api-client.double.ts
src/services/doppler-api-client.test.ts
src/services/doppler-api-client.ts

As [we discussed with the team](https://makingsense.slack.com/archives/CGJ72QFQX/p1614107973070900), think that these URLs will match better our future scenarios:
* `GET /accounts/${userAccount}/subscribers/${subscriberEmail}/permissions-history` (for the complete history of all subscriber's permission fields, maybe with an option for CSV)
* `GET /accounts/${userAccount}/subscribers/${subscriberEmail}/permissions-history/${fieldName}` (for the history of a single permission field)

chore: update GDPR history related API

---

src/App.test.js
src/components/Signup/Signup.js
src/services/doppler-legacy-client.ts

- get utms from url and save in local storage the history in UtmCokies.
- add utm_source, utm_campaign, utm_medium and utm_term in the model when the user create the account.

feat(Signup): add utms

---

src/components/Reports/GDPRPermissions/SubscriberGdprPermissions.js

The 'consent' field is a legacy field, which behaves differently than permission-type fields, and even has no permission history.

fix: exclude the 'consent' field in the permission list

---

src/components/Reports/GDPRPermissions/PermissionExpandableRow.js
src/components/Reports/GDPRPermissions/PermissionExpandableRow.test.js

If there was an error in the request, it was shown as if there was no history.
Before:
Now:

fix: display an error message when a response error is received

---

src/components/Signup/Signup.js
src/services/pure-di.tsx
src/services/utm-cookies-manager.js
src/services/utm-cookies-manager.test.js

Each time the signup component was rendered, a new entrances was added to this field utmCookies. To fix this I've added that this addition be done only dependent on the first render.
Besides it should only be registered one navigation each time the user access from outside in Signup. 
Example:
**Scenario 1**
- The user navigates to  `/signup?origin=testOrigin&utm_source=test&utm_campaign=testcampaign&utm_medium=testmedium&utm_term=testterm`
_One entrance is registered in UtmCookie and the registered flag is set to true_
- The user then navigates to `/login`
- Then he returns to `/signup` 
_No new entrance is registered_
**Scenario 2**
- The user navigates to  `/signup?origin=testOrigin&utm_source=test&utm_campaign=testcampaign&utm_medium=testmedium&utm_term=testterm`
_One entrance is …

DW-889: fix(utmCookies): add only one entrance for each navigation

---

src/App.test.js
src/components/Signup/Signup.js
src/services/doppler-legacy-client.ts
src/services/utm-cookies-manager.js
src/services/utm-cookies-manager.test.js

**Add gclid parameter** 
**Scenario**
- The user navigates to /signup?origin=testOrigin&utm_source=test&utm_campaign=testcampaign&utm_medium=testmedium&utm_term=testterm&gclid=testgclid
- The url parameter called gclid is registered in utm_cookies
- The user submits the signup form
- It is sent together with the information, the gclid parameter

DW-926 add gclid parameter

---

Jenkinsfile
generate-release-w-docker.sh

In an effort to move to the new process for deployment I've added semantic release tag generation in jenkinsfile.
Tasks:
- Disable old tag generation
- Copy into a new file
- Call this file from jenkins pipeline

fix: add release tag generation in Jenkinsfile

---

Dockerfile.RELEASES

Publish of code to nginx is done in swarm for all environments. This code is obsolete. The codes gives error, and the result is that we have cdn versioning only for integration. Then the copy fails and the process stops.
Fixes:
Remove obsolete code causing error.

DW-937: Remove publish to docker in build-n-publish script.

---

src/components/Header/Header.js
src/components/Header/Notifications.js
src/components/Header/Notifications.test.js

For webapp notifications where only shown for free users. And only one notification per time.
Fixes:
- Fix issue with restricting notifications only for free user
- Allow having displayed more than one Notifications
- Add tests.

DW-963: fix(Notifications): allow more than one Notifications

---

public/index.html

Remove duplicate stylesheet link from **index.html**, it was in header and before  closing body tag. ( This last one was removed).
@cbernat @andresmoschini @GusBaamonde @lucianaDilizio

DW-957-remove-duplicate-zoho-css

---

src/App.test.js
src/components/DopplerPlus/ExclusiveForm.test.js
src/components/ForgotPassword/ForgotPassword.test.js
src/components/form-helpers/form-helpers.js
src/hooks/useTimeout/index.js
src/hooks/useTimeout/index.test.js
src/services/doppler-legacy-client.doubles.ts

Add useTimeout hook in form-helpers and clean errors in console
**escenario:** 
- Run yarn test on console
- All tests pass successfully
**Results:**
- Local
- Jenkins

fix(console): fix console test errors

---

src/components/ChangePlan/ChangePlan.js
src/components/ChangePlan/PlanCalculator.js
src/components/ChangePlan/PlanCalculator.test.js
src/components/shared/Slider/Slider.js
src/utils.test.js
src/utils.ts

- Add a new function to allow format number based on configured language.
- Function also allows define between a simple intl format or compact one. 
ESP
ENG

Dw 544 format numbers in plan calculator

---

src/components/ChangePlan/PlanCalculator.test.js
src/services/plan-service.ts
src/utils.test.js
src/utils.ts

task link: https://makingsense.atlassian.net/browse/DW-545
- The user navigates to /plan-selection/standard
- Plans are displayed in the order: by contacts, by sending and by credits
Results:

fix(PlanCalculator): fix order of plans

---

src/services/doppler-contact-policy-api-client.double.ts
src/services/doppler-contact-policy-api-client.test.ts
src/services/doppler-contact-policy-api-client.ts

Integrate contact-policy API (https://apis.fromdoppler.com/contact-policies/swagger/index.html) with double

feat: add contact policy api double

---

src/components/ChangePlan/PlanCalculator.js
src/components/ChangePlan/PlanCalculator.test.js
src/utils.test.js
src/utils.ts

- Modify `thousandSeparatorNumber` function to show decimals if applies (if amount doesn't have decimals it will show it without them)
- If discount is applied, it will show total without rounding.
- A refactor was also made to make code more readable.
- A refactor was made in utils.test.
- Some new tests were added.

[DW-540] show decimals fix rounding

---

src/components/shared/Promotions/Promotions.js
src/components/shared/Promotions/Promotions.test.js

- Get the default image setting in be if has one, is not continue getting from local.

DW-973 fix(Promotions): get default image from be

---

src/components/ForgotPassword/ForgotPassword.test.js
src/components/Signup/Signup.test.js

fix tests in forgot password adding the dependency of doppler sites client to get the default banner.

fix(ForgotPassword): add dependency doppler sites client

---

src/components/ChangePlan/ChangePlan.js
src/components/ChangePlan/ChangePlan.test.js
src/doppler-types.ts
src/i18n/en.js
src/i18n/es.js
src/services/plan-service.test.js
src/services/plan-service.ts

- fix(change-plan): Always show button to upgrade current plan. _( Also when current plan is the highest plan)_
- fix(plan-service): Remove unused `deadEnd `property from plan-service, tests and code.

DW-992-allow-plan-upgrade

---

src/services/plan-service.test.js
src/services/plan-service.ts

* fix(plan-service): Show subscriber tab when is a montly-deliveries user
* Fix plan-service test.

DW-979-fix-calculator-switch-tabs

---

src/components/ChangePlan/Checkout/ContactInformation/ContactInformation.js

Remove warning in the ContactInformation component.
The warning was:
```
src\components\ChangePlan\Checkout\ContactInformation\ContactInformation.js
Line 54:8:  React Hook useEffect has a missing dependency: 'onComplete'. Either include it or remove the dependency array. If 'onComplete' changes too often, find the parent component that defines it and wrap that definition in useCallback  react-hooks/exhaustive-deps
```
**Task:** [DAT-498](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-498)

[DAT-498] -Remove warning in the ContactInformation component

---

src/App.js
src/components/ChangePlan/Checkout/CheckoutSummary.js

We need to track in google tag manager when the user upgrades from free to paid succesfully. To do this, we will track a redirection to a page. In Upgrade we will do a redirect to this page hidden and then redirect as usual. 
This page in the future will be the summary for checkout process for new plans. 
This page has two ways of operation:
- When legacy parameter is present it will redirect to old doppler with redirect parameter or by default to `Campaigns/Draft`
- When legacy parameter is not present it will remain in this page. 
Pending:

feat(checkout): checkout summary page

---

src/components/Integrations/BigQuery/ControlPanel/AuthorizationForm.js
src/components/Integrations/BigQuery/ControlPanel/AuthorizationForm.test.js
src/components/Integrations/BigQuery/ControlPanel/AuthorizationPage.js
src/components/form-helpers/CloudTagField/index.js
src/i18n/en.js
src/i18n/es.js
src/services/big-query-client.double.ts

**scenario:** 
- the user navigate to /integrations/big-query/plus
- the user can see the authorization form for google account
- the user adds tag with enter event or click to the + button
- when the user add invalid tag (no email) shown error message
- when the user add tag valid but the tag already exist, shown error message
- when the user submit form, shown alert with sent data
tests:

refactor: add tag cloud component to big query

---

src/components/UpgradePlanForm/UpgradePlanForm.js
src/i18n/en.js
src/i18n/es.js

- Change of text button "Send" by "Update Plan" in Spanish "Enviar" by "Actualizar Plan",
- Additionally, I parsed string by int in PlanTypeId when the users Update the plan
Example:

fix: [DAT-516] Fix button text of upgrade popup

---

package.json
src/components/ContactPolicy/ContactPolicy.js
src/components/ContactPolicy/ContactPolicy.test.js
src/components/Loading/Loading.js
src/components/shared/ShowLikeFlash/ShowLikeFlash.test.js
yarn.lock

With the help of @jcamposmk, consulting the documentation of the [react testing library](https://testing-library.com) and analyzing some articles about the [author](https://kentcdodds.com/blog) of the library, we found some recommendations on tests, which may be useful. We would like to know your opinions on this.
- There is no need to call the [cleanup](https://testing-library.com/docs/react-testing-library/api/#cleanup) function as it is called automatically for Jest and other test frameworks.
- The use of [screen](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#not-using-screen) is recommended:
The benefit of using [screen](https://testing-library.com/docs/queries/about/#screen) is you no longer need to keep the render call destructure up-to-date as you …

fix: improve tests

---

src/components/UpgradePlanForm/UpgradePlanForm.js

For last plan popup, we fix text of button, change "Actualizar Plan" by "Enviar"
Before
After

fix: [DAT-516] Fix text button for last plan form

---

.env
src/validations.ts

We have a lot of people commiting in this proyect, and they are not checking the warnings so I think this is a good solution.
For command `yarn build` only, warnings will be treated as errors. 
https://create-react-app.dev/docs/advanced-configuration/

feat(CI): add warning as errors in build

---

.gitignore

This is only for local use, so we should not upload anything from this folder. 
@jcamposmk is it ok this way? You are the expert in this 😄

chore: add husky into gitignore

---

src/components/CloudTags/index.js
src/components/form-helpers/CloudTagCompoundField/index.js
src/components/form-helpers/CloudTagCompoundField/index.test.js

task: https://makingsense.atlassian.net/browse/DW-1094
When `CloudTagCompoundField` component is used, can be passed as prop a callback afterRemove function.

feat: add after remove callback (optional)

---

README.md

task: https://makingsense.atlassian.net/browse/DW-1087
- Recommendations for testing
- Reccomendations for code organization
- Others recommendations
**RESULT:**
- It's recommended to test from the user's point of view, hiding implementation details. [More details](https://testing-library.com/docs/).
- Recommended documentation for [test implementation](https://github.com/FromDoppler/doppler-webapp/pull/1504).
- Test phases: 
- **Arrange:** a series of input data is created to be able to run the tests.
- **Act:** tests are run with the input data.
- **Assert**: the result obtained is analyzed to see if it matches what is expected.
- Pre-commit hook is used in local development (husky+link-staged). [More details](https://github.com/FromDoppler/doppler-webapp/pull/1523).
- There's no QA …

feat: add guide lines to README.md

---

src/components/Header/HeaderUserMenu/HeaderUserMenu.js
src/components/Header/HeaderUserMenu/HeaderUserMenu.test.js

task: https://makingsense.atlassian.net/browse/DW-1145
**scenario:** 
- the user has a prepaid plan
- the user opens the user dropdown 
- the user sees the text "Prepaid Plan" together with the upgrade link
**Before:** 
**After:**

fix(HeaderUserMenu): fix upgrade link when the user has a prepaid plan

---

src/services/plan-service.test.js
src/services/plan-service.ts

* fix(plan-service): Fix monthly deliveries tabs. Do not show Subscribers tab.

DW-1134-fix-monthly-deliveries-plan-tabs

---

src/components/ChangePlan/ChangePlan.js
src/components/ChangePlan/PlanCalculator/PlanCalculator.js
src/components/ChangePlan/PlanCalculator/PlanCalculator.test.js
src/doppler-types.ts
src/services/plan-service.test.js
src/services/plan-service.ts

These planes are not allowed to buy an email plan. 
Contact plan with a monthly subscription will see in plan calculator: Contact and Email tabs
Contact plan with a tree months subscription will see in plan calculator: Contact tab only. 
DW-1138

feat(plans): add currentSubscription filtering

---

src/components/Reports/Reports.js
src/components/Reports/Reports.test.js
src/components/Reports/ReportsBox/ReportsBox.js
src/components/Reports/ReportsBox/ReportsBox.test.js
src/components/Reports/ReportsDailyVisits/ReportsDailyVisits.js
src/components/Reports/ReportsFilters/ReportsFilters.js
src/components/Reports/ReportsFilters/ReportsFilters.test.js
src/components/Reports/ReportsHoursVisits/ReportsHoursVisits.js
src/components/Reports/ReportsTrafficSources/ReportsTrafficSources.js
src/i18n/en.js
src/i18n/es.js
src/services/datahub-client.doubles.ts

**scenario:**
- The user navigates to /reports page when a verificated domain
- The user sees a spinner and after the user sees a spinner for each box with a placeholder content (fake data)
**Before:**
**After:**

refactor: fix spinner on reports page

---

src/components/ChangePlan/PlanCalculator/PlanCalculator.js
src/doppler-types.ts
src/services/doppler-legacy-client.ts
src/services/plan-service.test.js
src/services/plan-service.ts

task: https://makingsense.atlassian.net/browse/DW-1140
**scenarios:** 
**The user has more subscribers than what was offered in the account per contact**
- The user navigates to `/plan-selection/standard/prepaid` with a prepaid account
- The user don't see the contact tab
Example when the user has 120.000 subscribers: 
**The user has less subscribers than what was offered in the account per contact**
- The user navigates to `/plan-selection/standard/prepaid` with a prepaid account
- The user sees the contact tab
Example when the user has 1600 subscribers:
**The user has the same number of subscribers as the maximum offered in the accounts per contact**
- The user navigates to `/plan-selection/standard/prepaid` with a prepaid account
- The user sees the contact tab, but the slider is at …

feat: filter plans by contacts for users with a prepaid account

---

src/components/ChangePlan/ChangePlan.js

**scenario**
- The user navigates to /plan-selection with a prepaid account
- The user sees the plans

fix: fix error in plan selection view

---

src/components/CloudTags/index.js
src/components/CloudTags/index.test.js

Remove green glow from the last tag, that did not indicate nothing in particular to avoid confusion. 
This must be replaced in the future by adding the glow for the last unsaved tags added. 
[Jira ticket link](https://makingsense.atlassian.net/browse/DW-1161)
Before
After

fix(CloudTags): temporarily remove dp-recently-add class

---

src/components/SiteTrackingRequired/SiteTrackingRequired.js
src/components/SiteTrackingRequired/SiteTrackingRequired.test.js
src/i18n/en.js
src/i18n/es.js

Before if a paid user never accesed into advanced reports he saw this:
Now he will see the second screen directly:

DW-1121: fix(SiteTrackingRequired): Remove intermediate screen

---

src/components/ChangePlan/Checkout/PaymentMethod/CreditCard.js
src/components/ChangePlan/Checkout/PaymentMethod/PaymentMethod.js
src/services/doppler-billing-user-api-client.double.ts
src/services/doppler-billing-user-api-client.test.ts
src/services/doppler-billing-user-api-client.ts

We update name of properties to PUT Payment method endpoint
Add mapper
```
{
ccHolderFullName: data.name,
ccNumber: data.number,
ccVerification: data.cvc,
paymentMethodName: data.paymentMethodName,
ccExpYear: data.expiry.split('/')[1],
ccExpMonth: data.expiry.split('/')[0],
ccType: data.ccType
};
```

fix: [DAT-597] Update PaymentMethod properties

---

src/components/ChangePlan/Checkout/PurchaseSummary/PurchaseSummary.js
src/components/ChangePlan/Checkout/PurchaseSummary/PurchaseSummary.test.js

Set placeholder for the 'Purchase Summary' section when the page is loading
Screenshot:
Before:
After:
**Task:** [DAT-629](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-629)

[DAT-629] - Set placeholder for the 'Purchase Summary' section when the page is loading

---

src/components/ChangePlan/Checkout/PaymentMethod/PaymentMethod.js
src/services/doppler-billing-user-api-client.double.ts
src/services/doppler-billing-user-api-client.test.ts
src/services/doppler-billing-user-api-client.ts

We need to send idSelectedPlan in the PUT paymentMethod/current endpoint to send this information to SAP
Example:
`{
"ccHolderFullName":"test",
"ccNumber":"4111 111111111111",
"ccVerification":"123",
"paymentMethodName":"CC",
"ccExpYear":"21",
"ccExpMonth":"12",
"ccType":"visa",
"idSelectedPlan":"37"
}`

chore: [DAT-631] Add idSelectedPlan property in PaymentMethod object

---

src/components/ChangePlanDeprecated/Checkout/Checkout.js
src/components/ChangePlanDeprecated/Checkout/Discounts/Discounts.js
src/components/ChangePlanDeprecated/Checkout/PaymentMethod/PaymentMethod.js
src/components/ChangePlanDeprecated/Checkout/PaymentMethod/Transfer.js
src/components/ChangePlanDeprecated/Checkout/PurchaseSummary/PurchaseSummary.js

Fix issue when the free user has not select payment method. 
Now when the user has not payment method the "Payment method' section is show in update mode and with 'Credit Card' option selected and also initialized the properties.
**Task:** [DAT-675](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-675)

[DAT-675] - The free user cannot select payment method

---

src/components/ChangePlanDeprecated/Checkout/PurchaseSummary/PurchaseSummary.js
src/components/ChangePlanDeprecated/Checkout/PurchaseSummary/PurchaseSummary.test.js
src/i18n/en.js
src/i18n/es.js

Show new purchuse legends when the buy is by credits.
**Before:**
**Credit Card:**
**Transfer:**
**After:**
**Credit Card:**
**Transfer:**
The refenrecen abot the changes in the legends are in: [Nuevo Flujo de Checkout](https://makingsense.atlassian.net/wiki/spaces/DOP/pages/1453785101/Nuevo+Flujo+de+Checkout)
**Task:** [DAT-676](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-676)

feat(checkout): Add purchuse legend when the buy is by credits

---

src/components/ChangePlanDeprecated/Checkout/PurchaseSummary/PurchaseSummary.js

Remove the harcoded values and use the values declared in doppler-types.js.
For example:
**Replace:**
```case 'prepaid':```
**to use:**
```case PLAN_TYPE.byCredit:```
**Task:** [DAT-678](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-678)

[DAT-678] - Remove the harcoded values and use the values declared in doppler-types.js

---

src/components/ChangePlanDeprecated/Checkout/BillingInformation/BillingInformation.js

Fix issue when the user changes the country, the state was left with the previous value instead of the the empty value
**Bug:** [DAT-685](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-685)

fix (checkout): When the user changes the country the state was left with the previous value

---

src/components/ChangePlanDeprecated/Checkout/PaymentMethod/PaymentMethod.js
src/components/ChangePlanDeprecated/Checkout/PaymentMethod/PaymentMethod.test.js

Show or hide payment method options depending of billing country
- If the country is **Argentina**, **"Transfer"** and **"Mercado Pago"** must be **displayed**.
- If the country is **Mexico** or **Colombia**, **"Transfer"** must be **shown** and **"Mercado Pago"** **hidden**.
- Any **other country** must be **hidden** **"Transfer"** and **"Mercado Pago"**.
**Notes:** If the user has selected credit card as payment method  the if the transfer is showing, it should be "disabled"
**Task:** [DAT-684](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-684)
- *Payment method:** Credit Card and **Billing Country:** 'AR'
**Before:**
**After:**
- *Payment method:** Credit Card and **Billing Country:** 'CL'
**Before:**
**After:**
- *Payment …

[DAT-684] - Show or hide payment method options depending of billing country

---

src/components/ChangePlanDeprecated/Checkout/PaymentMethod/CreditCard.js
src/components/ChangePlanDeprecated/Checkout/PaymentMethod/CreditCard.test.js
src/i18n/en.js
src/i18n/es.js

Add available credit cards legend when the credit card section is in update view.
**Before:**
**After:**
**Task:** [DAT-689](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-689)

[DAT-689] - Add available credit cards legend when the credit card section is in update view

---

src/components/Plans/PlanCalculator/NavigatorTabs/NavigatorTabs.js
src/components/Plans/PlanCalculator/NavigatorTabs/NavigatorTabs.test.js

**details task:** https://makingsense.atlassian.net/browse/DW-1270
**CDN int:** https://cdn.fromdoppler.com/doppler-webapp/int-build4165/#/plan-selection/premium/by-credits?promo-code=fake-promo-code&origin=hello_bar
**Result:**

feat: add query params when the user navigates between tabs

---

src/components/ContactPolicy/ContactPolicy.js

**details task:** https://makingsense.atlassian.net/browse/DW-1274
1. The user navigates to /sending-preferences/contact-policy
2. The contact policy is enabled
3. The user adds a list and the save button is clicked 
4. The user delete a list 
5. The save button is enabled

fix: enable button of contact policy when a list is deleted

---

src/components/Plans/PlanCalculator/PlanPrice/PricePerExtraEmail/index.js
src/components/Plans/PlanCalculator/PlanPrice/PriceWithDiscount/index.js

Space between currency and amount in plan calculator
**When a discount is selected**
**When plan type is for emails**

fix: fix space between amount & currency

---

src/components/Plans/PlanCalculator/reducers/plansByTypeReducer.js
src/components/Plans/PlanCalculator/reducers/plansByTypeReducer.test.js

**details task:** https://makingsense.atlassian.net/browse/DW-1289
**Before:**
**After:**

fix: fix the order of discounts in the plan calculator

---

src/components/ChangePlanDeprecated/Checkout/Checkout.test.js
src/components/ChangePlanDeprecated/Checkout/PurchaseSummary/InvoiceRecipients.js
src/components/ChangePlanDeprecated/Checkout/PurchaseSummary/InvoiceRecipients.test.js
src/components/ChangePlanDeprecated/Checkout/PurchaseSummary/PurchaseSummary.js
src/components/ChangePlanDeprecated/Checkout/PurchaseSummary/PurchaseSummary.test.js
src/i18n/en.js
src/i18n/es.js
src/services/doppler-billing-user-api-client.double.ts
src/services/doppler-billing-user-api-client.test.ts
src/services/doppler-billing-user-api-client.ts

Allow client to add or edit the invoice recipients.
**View only:**
**Edition view:**
**Note:** The idea of this PR is only include the changes in the component and fix unit tests, in the future I will create anothers PRs to include the integrations with the API and also include some unit tests.
**Task:** [DAT-622](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-622)

[DAT-622] - Update 'EditAddRecipients' component to supports add or edit.

---

src/services/control-panel-service.test.ts
src/services/control-panel-service.ts

To maintain the same flow as the current control panel I'm adding a few changes.
- hide the plans and specs box
- disable account history, SMS settings, and billing information boxes for free users.
Before:
After:

[DOI-358] Disable control panel boxes for free users and hidde plans&specs box

---

src/components/Plans/PlanCalculator/PlanPrice/PricePerMonth/index.js
src/components/Plans/PlanCalculator/PlanPrice/PricePerMonth/index.test.js

**details task:** https://makingsense.atlassian.net/browse/DW-1305
Remove the "per month" text for credit plans

fix: fix per month label for credits plan

---

src/components/Plans/PlanCalculator/index.js
src/components/Plans/PlanCalculator/reducers/plansByTypeReducer.js
src/components/Plans/PlanCalculator/reducers/plansByTypeReducer.test.js

Hi team!
I think that the state management in the PlanCalculator component is a little complex. In my opinion, we can do it better by taking advantage of the reducers.
In this PR, I moved `selectedPlanIndex` and `selectedPlan` values into the reducer state.
I think that the next step is merging `plansByTypeReducer` and `planTypesReducer` into only one reducer in order to make the logic clear and test it easier.
Another thing that we need to do is make the reducer test easier to understand, but I know that @silsanchez8 has worked on that, so it is out of the scope of this PR.
@jcamposmk, @silsanchez8 could you give it a look?

Refactoring PlanCalculator and plansByTypeReducer

---

src/components/Plans/PlanCalculator/reducers/plansByTypeReducer.js
src/components/Plans/PlanCalculator/reducers/plansByTypeReducer.test.js

* fix(plansByTypeReducer): set previous index discount when select a new plan
* Refactor tests
* Add new tests for secondary paths

DW-1290-get-previous-disccount

---

src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.js
src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.test.js

**Fix checkout url in plan calculator**
**legacy url**
`/ControlPanel/AccountPreferences/UpgradeAccountStep2&IdUserTypePlan=19&fromStep1=True&IdDiscountPlan=8` **to** `/ControlPanel/AccountPreferences/UpgradeAccountStep2?IdUserTypePlan=19&fromStep1=True&IdDiscountPlan=8`
**new url**
`/checkout/premium/subscribers&selected-plan=19&discountId=8` **to** `/checkout/premium/subscribers?selected-plan=19&discountId=8`

fix: fix checkout url in plan calculator

---

.env.int
.env.production
.env.qa
src/components/Dashboard/CampaignSummary/index.js
src/components/Dashboard/CampaignSummary/index.test.js
src/components/Dashboard/CampaignSummary/reducers/campaignSummaryReducer.js
src/components/Dashboard/CampaignSummary/reducers/campaignSummaryReducer.test.js
src/components/Dashboard/Dashboard.test.js
src/index.js
src/services/campaignSummary.test.ts
src/services/campaignSummary.ts
src/services/pure-di.tsx
src/services/reports/index.double.ts
src/services/reports/index.test.ts
src/services/reports/index.ts

**details task:** https://makingsense.atlassian.net/browse/DW-1052
Connects the campaigns summary component with the back

Dw 1052 add campaign report service

---

src/components/Dashboard/CampaignSummary/index.js
src/components/Dashboard/CampaignSummary/index.test.js
src/components/Dashboard/Kpis/KpiGroup.js
src/components/Dashboard/Kpis/KpiGroup.test.js
src/i18n/en.js
src/i18n/es.js

**details task:** https://makingsense.atlassian.net/browse/DW-1056
**description:**
add overlay to the campaign summary section when no campaigns have been sent in the last 30 days

Dw 1056 add overlay

---

src/components/Dashboard/ContactSummary/index.js
src/components/Dashboard/ContactSummary/index.test.js
src/i18n/en.js
src/i18n/es.js

**details task:** https://makingsense.atlassian.net/browse/DW-1061
**description:**
add overlay to the contact summary section when  has no contact

feat: add overlay to contact summary section

---

src/components/Plans/Checkout/PurchaseSummary/InvoiceRecipients.js
src/i18n/en.js
src/i18n/es.js

Missing translations for the placeholder in the ```InvoiceRecipients``` component:
**Screenshot:**
**Before:**
**After:**
**Task:** [DAT-721](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-721)

[DAT-721] - Missing translations for the placeholder

---

src/services/doppler-user-api-client.double.ts
src/services/doppler-user-api-client.ts

I added some new integration status to return from the users API's integrations/status endpoint. To avoid having to add every integration that we implement in the future I made the Integrations status response a dynamic object.

[No ticket] Modify integration status response mapping to be dynamic.

---

src/components/Plans/Checkout/CheckoutSummary.js
src/components/Plans/Checkout/CheckoutSummary.test.js
src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
src/components/Plans/Checkout/Reducers/checkoutSummaryReducer.js
src/components/Plans/Checkout/Reducers/checkoutSummaryReducer.test.js

Pass 'extraCredits' instead of 'promo-code' as parameter to the 'CheckoutSummary' page
**Screenshot:**
**Task:** [DAT-726](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-726)

[DAT-726] - pass 'extraCredits' instead of 'promo-code' as parameter to the 'CheckoutSummary' page

---

src/utils.ts

Hi team!
I need to redirect from the Editor WebApp after the login. Example: `https://app.fromdoppler.com/login?redirect=https://app.fromdoppler.com/editors/templates/1234`
What do you think about this approach?

feat: allow to redirect to external webapps in the same domain

---

src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.test.js

Add thousand separator number in the PurchaseSummary section
**Before:**
**After:**
Task: [DAT-735](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-735)

[DAT-735] - Add thousand separator number

---

src/components/Plans/Checkout/CheckoutSummary.js
src/components/Plans/Checkout/CheckoutSummary.test.js

Add thousand separator number in the 'CheckoutSummary' page
**Before:**
**After:**
**Task:** [DAT-734](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-734)

[DAT-734] - Add thousand separator number in the 'CheckoutSummary' page

---

src/services/control-panel-service.ts

The users API is not returning the correct values for some users. I'm disabling the control panel status untill it's fixed

Disable status icons

---

src/components/Plans/Checkout/PaymentMethod/PaymentMethod.js
src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.js

Only enabled the subscription type if the plan type is by contact and also set the new checkout for the buy is by email only is the ```newCheckoutEnabled``` is true

[DAT-787] Only enabled the subscription type is the plan type is by contact

---

src/components/Plans/PlanCalculator/index.js
src/components/Plans/PlanCalculator/index.test.js

**Jira ticket:** https://makingsense.atlassian.net/browse/DAT-835
When an user enters to /plan-selection/premium/by-emails or /plan-selection/premium/by-credits with a contact plan, the user will be redirect to /plan-selection/premium/by-contact because only is visible the Contacts Tag

feat: add support for plans by contacts

---

src/components/Dashboard/Dashboard.test.js
src/components/TypeformSurvey/index.js
src/components/TypeformSurvey/index.test.js

**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-866
**CDN**:  https://cdn.fromdoppler.com/doppler-webapp/qa-build4488/#/login
**Scenaries**:

feat: add typeform for free users

---

src/services/static-data-client.double.ts
src/services/static-data-client.test.ts
src/services/static-data-client.ts

Add new endpoints to use in the México transfer:
- Get CFDI.
- Get Payment ways.
- Get Payment types
**Task:** [DAT-876](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-876)

[DAT-876] - Add new endpoints to use in the Mexico transfer

---

src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.js

**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-931
When the user buy a plan with a promocode 100%, the user sees the check success icon
**Result**

feat: add icon at mercado pago summary

---

public/index.html

Hi team!
We created a new project with CI/CD for the loader.
With this change, I am testing it: https://github.com/FromDoppler/mfe-loader/pull/1
~What do you think? how should we update this project?~
* ~Should we create a new URL like (`https://cdn.fromdoppler.com/loader/v1.1.0/loader.js`)?~
* ~Should we use the URL with the hash (`https://cdn.fromdoppler.com/mfe-loader/static/js/main.a58832ef.js`)?~
* ~Should update the same URL with the new content (`https://cdn.fromdoppler.com/loader/v1/loader.js`)?~
The chosen option was copying manually the final version file to `https://cdn.fromdoppler.com/mfe-loader/loader-v#.#.#.js` was see more details in https://github.com/FromDoppler/mfe-loader/#how-to-contribute

feat: use the new loader

---

src/components/Plans/PlanCalculator/GoToUpgrade/index.test.js
src/components/Plans/PlanCalculator/index.js

**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-986
**scenarios:**
- The user navigates to `/plan-selection/premium/by-emails` with an exclusive plan by email 
- The user is redirected to `/upgrade-suggestion-form`
**NOTE:** this functionality has not yet been released

feat: redirect user to /upgrade-sueestion-form when has exclusive plan

---

src/services/doppler-legacy-client.ts

**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1005
- The user enters to /plan-selection/premium/by-contacts with a free
- The user does not see the subscription type message

fix: fix suscription message when account type is free

---

src/components/Plans/PlanCalculator/index.js
src/components/Plans/PlanCalculator/reducers/plansByTypeReducer.js
src/components/Plans/PlanCalculator/reducers/plansByTypeReducer.test.js

**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-987
When a user enters the plan calculator with a contact plan with a 3-month subscription, the calculator is initialized

feat: add support for plans by contacts to plan calculator

---

src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.js
src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.test.js
src/components/Plans/PlanCalculator/index.js

**Jira Ticket**: https://makingsense.atlassian.net/browse/DAT-1019
When the user has a monthly subscription type and he wants a trimestral subscription type, the buy continue button is enabled.
**The Bug**

fix: enable button when change the suscription type user

---

src/components/Plans/PlanCalculator/GoToUpgrade/index.js
src/components/Plans/PlanCalculator/GoToUpgrade/index.test.js
src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.js
src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.test.js

**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1013
⚠️⚠️ **Note:** Don't merge before of [DAT-998](https://github.com/FromDoppler/doppler-webapp/pull/2024)
**Scenario**
- The user navigates to /plan-selection/premium/by-emails with a account type by emails
- The user sees Plan Calculator
- The user selects a new plan
- The user click continue button
- The user sees new checkout

Dat 1013 enabled plans by emails - ⚠️⚠️⚠️ don't merge before of DAT-998

---

src/components/Signup/Signup.js

The value of the parameter `UTM_Source` during registration exceeds DB file length, [see Level2's chat](https://makingsense.slack.com/archives/GGW4H4YRL/p1659539173629839?thread_ts=1659467569.669719&cid=GGW4H4YRL).
It is because we receive a URL when we should receive a simple word (`facebook`, `instagram`, `linkedin`, `youtube`, `twitter`, `newsletter`, `mailing`, etc., see [documentation](https://makingsense.atlassian.net/wiki/spaces/DopplerMKT/pages/1329889281/Lineamientos+Tracking+UTMs#UTM-Source-(utm_source))).
The current code tries to read the value from the current URL and if it is not defined it uses the full _referrer_ value (an URL), [the code is ancient](https://github.com/FromDoppler/doppler-webapp/pull/1339/files#diff-97729f1090c23546a0ddc2b5198c7ce68403f05d48ae9e85035e02ec4d …

fix: assume 'direct' when URL does not contain UTM_Source

---

src/components/Plans/PlanCalculator/GoToUpgrade/index.js
src/components/Plans/PlanCalculator/GoToUpgrade/index.test.js
src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.js
src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.test.js

**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1027
⚠️⚠️ **Note:** Don't merge before of 10/08/2022
**Scenario**
- The user navigates to /plan-selection/premium/by-contacts with a account type by contacts
- The user sees Plan Calculator
- The user selects a new plan
- The user click continue button
- The user sees new checkout

Dat 1027 add enable upgrade between plans by contacts - ⚠️⚠️⚠️ don't merge before of 10/08/2022

---

src/services/doppler-legacy-client.ts
src/services/doppler-user-api-client.ts

It's not necessary to use this endpoint anymore because now the features are assumed like true for all users.
[A ticket](https://makingsense.atlassian.net/browse/DOP-1097) was created and associated with the related code.
related to [DOP-1080](https://makingsense.atlassian.net/browse/DOP-1080)

refactor: remove use of "/features" endpoint

---

src/components/Plans/PlanCalculator/GoToUpgrade/index.js
src/components/Plans/PlanCalculator/GoToUpgrade/index.test.js
src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.js
src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.test.js

Add enable upgrade between plans by credits.
**Task:** [DAT-1082](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1082)
**Scenario**
- The user navigates to /plan-selection/premium/by-credits with a account type by credits
- The user sees Plan Calculator
- The user selects a new plan
- The user click continue button
- The user sees new checkout

[DAT-1082] - Add enable upgrade between plans by credits

---

src/components/Dashboard/FirstSteps/index.js

El paso "Crea tu primer campaña" aparece tachado sin que le campaña se haya enviado. 
Este paso debería estar tachado cuando la campaña y enviada.
Bug: [DAT-1097](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1097)

[DAT-1097] - Fix issue in the dashboard in the stepper.

---

src/services/origin-management.tsx

**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1135
**Scenario:**
- the user navigates to `/signup?origin=demo-day`
- the user is registered
- the `origin` parameter is sent to BE  with `demo-day` value

fix: change location for window.location

---

renovate.json

It is to avoid CI consumption because we have a lot of unmergeable dependencies.
See documentation at https://docs.renovatebot.com/configuration-options/#rebasewhen
I think that we can rebase [by adding the tag `rebase`](https://docs.renovatebot.com/configuration-options/#rebaselabel) and also using the [Dependency Dashboard](https://github.com/FromDoppler/doppler-webapp/issues/2110).

Disable Renovate auto-rebase

---

src/components/Signup/Signup.js
src/components/Signup/Signup.test.js

**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1161
Use query params when the user doesn't accept cookies
example: 
- The user navigates to `/signup?utm_source=fromdoppler&utm_medium=email&utm_campaign=demoday-septiembre2022` 
- The user doesn's accept cookies
- The user creates an account
- The request sends the fields UTMSource:fromdoppler, UTMMedium:email, UTMCampaign:demoday-septiembre2022 and UTMCookies: null (because the user doesn't accept cookies)

fix: use query params when the user doesn't accept cookies

---

src/utils.ts

I will use it to redirect back to the same page when the session is expired in reports.

fix: add reports to login redirection white list

---

src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.js

Disabled the continue button when the user only change the renovation type in the update between plans.
**Task:** [DAT-1168](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1168)

[DAT-1168] - Disabled the continue button when the user only change the renovation type in the update between plans

---

src/components/ForgotPassword/ForgotPassword.js
src/components/Login/Login.js
src/components/Signup/ConfirmationContent/index.js
src/components/Signup/ConfirmationContent/index.test.js
src/components/Signup/Signup.js
src/components/Signup/SignupConfirmation.js
src/components/shared/Promotions/Promotions.js
src/components/shared/Promotions/Promotions.test.js
src/hooks/useGetBannerData/bannerDataReducer/index.js
src/hooks/useGetBannerData/bannerDataReducer/index.test.js
src/hooks/useGetBannerData/index.js
src/hooks/useGetBannerData/index.test.js
src/services/doppler-sites-client.ts

**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1201
- The user enters to `Signup` page
- `getBannerData` is executed. Return a new `contentActivation` property
- The user creates an account (`contentActivation` is sent)
- The user is redirected to `/signup/confirmation `
- If there is `contentActivation` then is used as content instead of content by default

Dat 1201 get content activation

---

src/i18n/en.js
src/i18n/es.js

use environment variables for the generation of the Doppler reports url instead of the hardcoded url

fix: use environment variables for the generation of the Doppler reports url

---

src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js

When the purchase summary component was loading it showed: "NaN" on the total tag. Now when is loading it shows 0
Before:
After:

fix: fix not a number ui error on the purchase summary component

---

src/components/ForgotPassword/ForgotPassword.js
src/components/Login/Login.js
src/components/Signup/Signup.js
src/hooks/useGetBannerData/index.js
src/hooks/useGetBannerData/index.test.js

**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1238
When the user enters to `/signup?lang=es`  `/login?lang=es`  or `/login/reset-password?lang=es` with the navigator configured in english, sites api was called with `lang=en` as query param instead of `lang=es`

fix: fix language in useBannerData

---

src/components/Login/Login.js
src/components/PrivateRoute.js
src/doppler-types.ts
src/services/app-session.ts
src/services/doppler-legacy-client.ts
src/services/sessionmfe-session-manager.ts

Integrate app with provisional token. 
The idea about this functionality is that when the user is blocked. The user can access the update payment information page with a provisional token.

[DAT-1133] - Integrate app with provisory token

---

src/components/Integrations/index.js
src/components/Integrations/index.test.js
src/components/Integrations/reducers/IntegrationReducer.js
src/components/Integrations/reducers/IntegrationReducer.test.js

When fetching for the integrations status there is a delay between the rendering of the boxes and the re-ordering by status of them. This already happened in the control panel but since you had to scroll down to get to the integrations sections it wasn't visible.
If the request fails it should show the boxes without the connection icon.
**BEFORE:**
**AFTER**

[DOI-831] Add spinning icon when waiting for status fetch

---

src/services/control-panel-service.ts

Facebook has deprecated the endpoint to create new tabs, so we need to remove the reference to the help's link.

[DOI-881] Remove facebook from integrations

---

src/services/control-panel-service.ts

We need to redirect Jumpseller from the control panel to a new url that uses OAuth2

[DOI-1027] modify jumpseller link

---

src/services/doppler-contact-policy-api-client.double.ts
src/services/doppler-contact-policy-api-client.test.ts
src/services/doppler-contact-policy-api-client.ts

Obtain values from the Doppler api to complete the restriction time section:
@mmosquera the endpoint to be requested is: `https://apisqa.fromdoppler.net/contact-policies/accounts/{email}/settings`, 
and the new fields to be added in the response should be:
```
timeRestriction: {
timeSlotEnabled: boolean,
hourFrom: number,
hourTo: number,
weekdaysEnabled: boolean,
},
```

Dop 1445 get restriction time values from doppler api

---

src/components/ContactPolicy/ContactPolicy.js
src/components/ContactPolicy/ContactPolicy.test.js

**Before**, the error messages related to the input changes was displayed on the bottom, and one message for time to each section:
**Now**, the error messages are displayed near the related inputs, and the messages for each section are displayed simultaneously:

Dop 1445 improve contact policy errors messages

---

src/components/Plans/UpdatePaymentInformation/Reducers/updatePaymentInformationReducer.js
src/components/Plans/UpdatePaymentInformation/Reprocess/index.js
src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformationSummary/index.js
src/components/Plans/UpdatePaymentInformation/UpdatePaymentMethod/index.js
src/components/Plans/UpdatePaymentInformation/UpdatePaymentMethod/index.test.js

Allow to user change the payment method to MercadoPago when the user is canceled and the current payment method is Credit Card
**Task:** [DAT-1684](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1684)
[DAT-1684]: https://makingsense.atlassian.net/browse/DAT-1684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-1684] - Integrate canceled account with mercado pago

---

src/hooks/useDefaultPlanType/index.js
src/hooks/useDefaultPlanType/index.test.js

**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1734
This hook will be used in plan selection view. **Example**: 
The user has a contact plan with a yearly subscription and enters to `/plan-selection/premium/by-email` or `/plan-selection/premium/by-credits`, if this happend then the user will be redirected to `/plan-selection/premium/by-contact` because he can't buy email plan or a credit plan.

feat: create use default plan type hook

---

src/utils.ts

We are getting a CORS error when redirecting to the login from conversations.fromdoppler.
If this works I will add the urls for every environment.

[No ticket] Withelist conversations url for qa

---

src/components/ControlPanel/CollaboratorsSections/index.js
src/i18n/en.js
src/i18n/es.js
src/services/doppler-user-api-client.double.ts
src/services/doppler-user-api-client.test.ts
src/services/doppler-user-api-client.ts

Display returned invitations from the doppler users API endpoint.
Also refresh on any new sent invitation.

[DOI-1511] Get user invitations through doppler-users API

---

src/services/doppler-legacy-client.ts

I renamed the endpoint on Doppler Legacy but forgot to do it here too

[DOI-1558] Modify endpoint name

---

src/components/ControlPanel/CollaboratorsSections/Forms/CollaboratorInviteForm.js
src/components/ControlPanel/CollaboratorsSections/Forms/CollaboratorPermissionsForm.js
src/components/ControlPanel/CollaboratorsSections/Forms/CollaboratorPermissionsForm.test.js
src/components/ControlPanel/CollaboratorsSections/index.js
src/i18n/en.js
src/i18n/es.js
src/services/doppler-user-api-client.double.ts
src/services/doppler-user-api-client.ts

This will add a new step in the modal for collaborators invite, to set the permissions the collaborator will have over the account.
Also the body request to the API is modified.

[DOI-1670] Add collaborators permission configuration step

---

src/services/control-panel-service.ts
src/services/doppler-legacy-client.ts

PR relacionado: https://github.com/MakingSense/Doppler/pull/11194
Escondemos el cuadro de bigbox si el usuario no tiene la feature activa.

Esconder box de big box si no tiene el feature activo

---

src/components/Integrations/Shopify/Shopify.js

Mientras se esta cargando el iframe con el MFE de RFM se muestra un spinner. Cuando la vista hija termina de cargar envía un objeto data type "rfmReady", el cual es recibido por webapp para saber cuando ocultar el spinner y mostrar totalmente el iframe.
[PR del lado de MFE](https://github.com/FromDoppler/doppler-integrations-mfe/pull/274)

RFM loading show spinner
